
package com.extra.services.omsstatus;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Status", targetNamespace = "http://www.extra.com/Services/OmsStatus", wsdlLocation = "http://qa-online-order-processing-v1.uk-e1.cloudhub.io/status/UpdateOrderStatus?wsdl")
public class Status
    extends Service
{

    private final static URL STATUS_WSDL_LOCATION;
    private final static WebServiceException STATUS_EXCEPTION;
    private final static QName STATUS_QNAME = new QName("http://www.extra.com/Services/OmsStatus", "Status");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://qa-online-order-processing-v1.uk-e1.cloudhub.io/status/UpdateOrderStatus?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATUS_WSDL_LOCATION = url;
        STATUS_EXCEPTION = e;
    }

    public Status() {
        super(__getWsdlLocation(), STATUS_QNAME);
    }

    public Status(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATUS_QNAME, features);
    }

    public Status(URL wsdlLocation) {
        super(wsdlLocation, STATUS_QNAME);
    }

    public Status(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATUS_QNAME, features);
    }

    public Status(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Status(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IStatus
     */
    @WebEndpoint(name = "BasicHttpBinding_IStatus")
    public IStatus getBasicHttpBindingIStatus() {
        return super.getPort(new QName("http://www.extra.com/Services/OmsStatus", "BasicHttpBinding_IStatus"), IStatus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStatus
     */
    @WebEndpoint(name = "BasicHttpBinding_IStatus")
    public IStatus getBasicHttpBindingIStatus(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.extra.com/Services/OmsStatus", "BasicHttpBinding_IStatus"), IStatus.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STATUS_EXCEPTION!= null) {
            throw STATUS_EXCEPTION;
        }
        return STATUS_WSDL_LOCATION;
    }

}
