## QA
#db.driver=oracle.jdbc.driver.OracleDriver
#db.username=EXTRADEV
#db.password=wFeJdt6c
#db.url=jdbc:oracle:thin:@exvm-qarmsdb02.extrastores.com:1521/RMSQA.extrastores.com



apple.pricing.url.v2=https://dc-pricing-api.apple.com/pricing-api/api/v2
iPadDeptIds = {'626','606'}



## QA
#apple.id = 2375429
#apple.pricing.clientid=EXT226
#apple.pricing.secret=eZZM7ey9qFlXUvQ0jq6FhNnQ