#SIM DB Details_QA
#sim14.db.jdbc-url=jdbc:oracle:thin:@exvm-qarmsdb01.extrastores.com:1521/SIMQA.extrastores.com
#sim14.db.user=sim14
#sim14.db.password=retQAtrex123

#RMS DB Details
#oms.db.jdbc-url=jdbc:oracle:thin:@exvm-qarmsdb02.extrastores.com:1521/RMSQA.extrastores.com
#oms.db.user=OMSDEV
#oms.db.password=Logic123

#SIM DB Details
sim14.db.jdbc-url=jdbc:oracle:thin:@retprd-scan.extrastores.com:1521/SIMPRD.extrastores.com
sim14.db.user=sim14
sim14.db.password=kcv123retlv

#RMS DB Details
oms.db.jdbc-url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
oms.db.user=OMSDEV
oms.db.password=Z0b0JYUB


#ORDER_EMAIL
ORDER.NOTIFICATION.FROM.EMAIL = ORDER_FROM_EMAIL
ORDER.NOTIFICATION.ORDER.EMAIL.TEMPLATE = ORDER_EMAIL_TEMPLATE
ORDER.NOTIFICATION.ORDER.EMAIL.TEMPLATES = ORDER_EMAIL_TEMPLATES
ORDER.NOTIFICATION.NORMAL = NORMAL
ORDER.NOTIFICATION.REMINDER = REMINDER
ORDER.NOTIFICATION.FROM.PHONE.NUMBER = ORDER_FROM_PHONE_NUMBER
ORDER.NOTIFICATION.ORDER.SMS.TEMPLATE = ORDER_SMS_TEMPLATE
ORDER.NOTIFICATION.ORDER.SMS.TEMPLATES = ORDER_SMS_TEMPLATES

xml.file.loc.store=./xmls/store/
xml.file.loc.inv=./xmls/inventory/
xml.file.loc.trickle=./xmls/trickle/

#API uri

#EmailNotification_URI=https://uat-communication-v1.uk-e1.cloudhub.io/communication/email
#SmsNotification_URI=https://uat-communication-v1.uk-e1.cloudhub.io/communication/sms
#client.and.secret.id.base64.encoded=MDU2MTg4NWI1M2FjNDhmOTk3MmM2MTQxYjY2NzVhYTE6MjJGMTJFMjVFMmYwNGRhMjk2NWU0QjU2NTkwQkZGOTI=

EmailNotification_URI=https://prod-communication-v1.uk-e1.cloudhub.io/communication/email
SmsNotification_URI=https://prod-communication-sms-v2.uk-e1.cloudhub.io/communication/sms/sms
client.and.secret.id.base64.encoded=MDc5NmMyOTc0M2Q1NDZhNGFlODcwYTRkMWQ3YTc3OTk6OEQ4OWM0Q0I0QzU5NDk4MTk5RjhkYjIwOUY3MWExM2Y=


#STORE GENERAL MANAGER
#SERVICE DESK
#OPERATION MANAGER
#SALES MANAGER CE
#SALES MANAGER IT
#CUSTOMER EXPERIENCE SUPERVISOR
#CUSTOMER EXPERIENCE MANAGER
#SALES MANAGER
#OUTLET MANAGER
#TEAM LEADER OUTLET