
package com.oracle.retail.rms.integration.services.inventorybackorderservice.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "IllegalStateWSFaultException", targetNamespace = "http://www.oracle.com/retail/integration/services/exception/v1")
public class IllegalStateWSFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.oracle.retail.integration.services.exception.v1.IllegalStateWSFaultException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public IllegalStateWSFaultException(String message, com.oracle.retail.integration.services.exception.v1.IllegalStateWSFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public IllegalStateWSFaultException(String message, com.oracle.retail.integration.services.exception.v1.IllegalStateWSFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.retail.integration.services.exception.v1.IllegalStateWSFaultException
     */
    public com.oracle.retail.integration.services.exception.v1.IllegalStateWSFaultException getFaultInfo() {
        return faultInfo;
    }

}
