
package com.oracle.retail.rms.integration.services.inventorybackorderservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.invbackordcoldesc.v1.InvBackOrdColDesc;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InventoryBackOrderPortType", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.invbackordcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invbackorddesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.rms.integration.services.inventorybackorderservice.v1.ObjectFactory.class
})
public interface InventoryBackOrderPortType {


    /**
     * 
     * @param invBackOrdColDesc
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalArgumentWSFaultException
     * @throws EntityAlreadyExistsWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "createInvBackOrdColDesc", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", className = "com.oracle.retail.rms.integration.services.inventorybackorderservice.v1.CreateInvBackOrdColDesc")
    @ResponseWrapper(localName = "createInvBackOrdColDescResponse", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", className = "com.oracle.retail.rms.integration.services.inventorybackorderservice.v1.CreateInvBackOrdColDescResponse")
    public InvocationSuccess createInvBackOrdColDesc(
        @WebParam(name = "InvBackOrdColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvBackOrdColDesc/v1")
        InvBackOrdColDesc invBackOrdColDesc)
        throws EntityAlreadyExistsWSFaultException, IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", className = "com.oracle.retail.rms.integration.services.inventorybackorderservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", className = "com.oracle.retail.rms.integration.services.inventorybackorderservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
