
package com.oracle.retail.rms.integration.services.inventorybackorderservice.v1;

import com.logicinfo.oms.beans.OMSUtilCommons;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InventoryBackOrderService", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", wsdlLocation = "http://licrpap14-extra.logicindia.com:17040/InventoryBackOrderBean/InventoryBackOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frms%2Fintegration%2Fservices%2FInventoryBackOrderService%2Fv1%7DInventoryBackOrderService")
public class InventoryBackOrderService
    extends Service
{

    private final static URL INVENTORYBACKORDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.rms.integration.services.inventorybackorderservice.v1.InventoryBackOrderService.class.getName());

    static {
        URL url = null;
        try {
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("RMS_BACK_ORDER");
            URL baseUrl;
            baseUrl = com.oracle.retail.rms.integration.services.inventorybackorderservice.v1.InventoryBackOrderService.class.getResource(".");
          //  url = new URL(baseUrl, "http://licrpap14-extra.logicindia.com:17040/InventoryBackOrderBean/InventoryBackOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frms%2Fintegration%2Fservices%2FInventoryBackOrderService%2Fv1%7DInventoryBackOrderService");
            url = new URL(baseUrl,wsdlUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://licrpap14-extra.logicindia.com:17040/InventoryBackOrderBean/InventoryBackOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frms%2Fintegration%2Fservices%2FInventoryBackOrderService%2Fv1%7DInventoryBackOrderService', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        INVENTORYBACKORDERSERVICE_WSDL_LOCATION = url;
    }

    public InventoryBackOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryBackOrderService() {
        super(INVENTORYBACKORDERSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", "InventoryBackOrderService"));
    }

    /**
     * 
     * @return
     *     returns InventoryBackOrderPortType
     */
    @WebEndpoint(name = "InventoryBackOrderPort")
    public InventoryBackOrderPortType getInventoryBackOrderPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", "InventoryBackOrderPort"), InventoryBackOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryBackOrderPortType
     */
    @WebEndpoint(name = "InventoryBackOrderPort")
    public InventoryBackOrderPortType getInventoryBackOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", "InventoryBackOrderPort"), InventoryBackOrderPortType.class, features);
    }

}
