
package com.oracle.retail.sim.integration.services.storeinventoryservice.v1;

import com.logicinfo.oms.beans.OMSUtilCommons;
import com.logicinfo.oms.ejb.OMSUtilSessionEJB;
import com.logicinfo.oms.util.OMSUtil;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "StoreInventoryService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", wsdlLocation = "http://licrpap14-extra.logicindia.com:17019/StoreInventoryBean/StoreInventoryService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FStoreInventoryService%2Fv1%7DStoreInventoryService")
public class StoreInventoryService
    extends Service
{

    private final static URL STOREINVENTORYSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.sim.integration.services.storeinventoryservice.v1.StoreInventoryService.class.getName());

    static {
        URL url = null;
        try {
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("SIM_STORE_INVENTORY");
            //String port = OMSUtil.getInstance().LoadErrorMessages().getProperty("port");
           System.out.println("inside store inventory service wsdlUrl"+wsdlUrl);
             //   String wsdlUrl = OMSUtilCommons.getWebServiceURL("SIM_STORE_INVENTORY");
            URL baseUrl;
            
            baseUrl = com.oracle.retail.sim.integration.services.storeinventoryservice.v1.StoreInventoryService.class.getResource(".");
            // url = new URL(baseUrl, "http://licrpap14-extra.logicindia.com:17019/StoreInventoryBean/StoreInventoryService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FStoreInventoryService%2Fv1%7DStoreInventoryService");
            url = new URL(baseUrl,wsdlUrl);   
        } catch (MalformedURLException e) {
            //logger.warning("Failed to create URL for the wsdl Location: 'http://licrpap14-extra.logicindia.com:17019/StoreInventoryBean/StoreInventoryService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FStoreInventoryService%2Fv1%7DStoreInventoryService', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        STOREINVENTORYSERVICE_WSDL_LOCATION = url;
    }

    public StoreInventoryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreInventoryService() {
        super(STOREINVENTORYSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", "StoreInventoryService"));
    }

    /**
     * 
     * @return
     *     returns StoreInventoryPortType
     */
    @WebEndpoint(name = "StoreInventoryPort")
    public StoreInventoryPortType getStoreInventoryPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", "StoreInventoryPort"), StoreInventoryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StoreInventoryPortType
     */
    @WebEndpoint(name = "StoreInventoryPort")
    public StoreInventoryPortType getStoreInventoryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", "StoreInventoryPort"), StoreInventoryPortType.class, features);
    }

}
