
package com.oracle.retail.sim.integration.services.storeinventoryservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.invavailcoldesc.v1.InvAvailColDesc;
import com.oracle.retail.integration.base.bo.invavailcrivo.v1.InvAvailCriVo;
import com.oracle.retail.integration.base.bo.strinvcoldesc.v1.StrInvColDesc;
import com.oracle.retail.integration.base.bo.strinvcrivo.v1.StrInvCriVo;
import com.oracle.retail.integration.base.bo.strinvgpcrivo.v1.StrInvGpCriVo;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StoreInventoryPortType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.invavailcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invavailcrivo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invavaildesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strinvcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strinvcrivo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strinvdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strinvgpcrivo.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.sim.integration.services.storeinventoryservice.v1.ObjectFactory.class
})
public interface StoreInventoryPortType {


    /**
     * 
     * @param invAvailCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.invavailcoldesc.v1.InvAvailColDesc
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvAvailColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvAvailColDesc/v1")
    @RequestWrapper(localName = "lookupAvailableInventory", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupAvailableInventory")
    @ResponseWrapper(localName = "lookupAvailableInventoryResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupAvailableInventoryResponse")
    public InvAvailColDesc lookupAvailableInventory(
        @WebParam(name = "InvAvailCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvAvailCriVo/v1")
        InvAvailCriVo invAvailCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strInvCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.strinvcoldesc.v1.StrInvColDesc
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrInvColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrInvColDesc/v1")
    @RequestWrapper(localName = "lookupInventoryInStore", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupInventoryInStore")
    @ResponseWrapper(localName = "lookupInventoryInStoreResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupInventoryInStoreResponse")
    public StrInvColDesc lookupInventoryInStore(
        @WebParam(name = "StrInvCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrInvCriVo/v1")
        StrInvCriVo strInvCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strInvGpCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.strinvcoldesc.v1.StrInvColDesc
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrInvColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrInvColDesc/v1")
    @RequestWrapper(localName = "lookupInventoryInTransferZone", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupInventoryInTransferZone")
    @ResponseWrapper(localName = "lookupInventoryInTransferZoneResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupInventoryInTransferZoneResponse")
    public StrInvColDesc lookupInventoryInTransferZone(
        @WebParam(name = "StrInvGpCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrInvGpCriVo/v1")
        StrInvGpCriVo strInvGpCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strInvGpCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.strinvcoldesc.v1.StrInvColDesc
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrInvColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrInvColDesc/v1")
    @RequestWrapper(localName = "lookupInventoryForBuddyStores", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupInventoryForBuddyStores")
    @ResponseWrapper(localName = "lookupInventoryForBuddyStoresResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.LookupInventoryForBuddyStoresResponse")
    public StrInvColDesc lookupInventoryForBuddyStores(
        @WebParam(name = "StrInvGpCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrInvGpCriVo/v1")
        StrInvGpCriVo strInvGpCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreInventoryService/v1", className = "com.oracle.retail.sim.integration.services.storeinventoryservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
