
#QA
db.username=OMSDEV
db.password=Logic123
db.url=jdbc:oracle:thin:@192.168.41.187:1521/RMSQA.extrastores.com
db.driver=oracle.jdbc.driver.OracleDriver

#prod
#db.username=OMSDEV
#db.password=Z0b0JYUB
#db.url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
#db.driver=oracle.jdbc.driver.OracleDriver

#QA
jood.url = https://qa-customer-profile-v3.uk-e1.cloudhub.io/customer
jood.username = 233712e626774e18a05931beabdfbf3f
jood.password = F612a7F22660441187Fc6C6ed0354BAC

#prod
#jood.url = https://prod-customer-profile-v3.uk-e1.cloudhub.io/customer
#jood.username = 0796c29743d546a4ae870a4d1d7a7799
#jood.password = 8D89c4CB4C59498199F8db209F71a13f

feign.client.config.joodService.loggerLevel = FULL
logging.level.com.extra.jood.service.JoodSyncService= debug