package oracle.retail.sim.common.activityhistory;

import oracle.retail.sim.common.core.SimEnum;

public enum ActivityType implements SimEnum<Integer> {
  LOGIN_SUCCESS(1, "LOGIN_SUCCESS"),
  LOGIN_FAIL(2, "LOGIN_FAIL"),
  LOGOUT(3, "LOGOUT"),
  TRANSFER_DISPATCH(5, "TRANSFER_DISPATCH"),
  TRANSFER_RECEIVE(6, "TRANSFER_RECEIVE"),
  TRANSFER_UPDATE(7, "TRANSFER_UPDATE"),
  RETURN_STOCK_CREATE(9, "RETURN_STOCK_CREATE"),
  RETURN_STOCK_DISPATCH(10, "RETURN_STOCK_DISPATCH"),
  RETURN_STOCK_DELETE(11, "RETURN_STOCK_DELETE"),
  INVENTORY_ADJUSTMENT_CREATE(12, "INVENTORY_ADJUSTMENT_CREATE"),
  INVENTORY_ADJUSTMENT_UPDATE(13, "INVENTORY_ADJUSTMENT_UPDATE"),
  INVENTORY_ADJUSTMENT_COMPLETE(14, "INVENTORY_ADJUSTMENT_COMPLETE"),
  PRICE_LABEL_PRINTED(15, "PRICE_LABEL_PRINTED"),
  PUBLISH_MESSAGE(16, "PUBLISH_MESSAGE"),
  RECEIVE_MESSAGE(17, "RECEIVE_MESSAGE"),
  STOCK_COUNT_LOCATION_COMPLETED(19, "STOCK_COUNT_LOCATION_COMPLETED"),
  DIRECT_DELIVERY_CREATE(81, "DIRECT_DELIVERY_CREATE"),
  DIRECT_DELIVERY_UPDATE(82, "DIRECT_DELIVERY_UPDATE"),
  DIRECT_DELIVERY_CONFIRM(83, "DIRECT_DELIVERY_CONFIRM"),
  ITEM_REQUEST(201, "ITEM_REQUEST"),
  UNIT_RECEIVER_ADJUSTMENT_TRANSFER(300, "UNIT_RECEIVER_ADJUSTMENT_TRANSFER"),
  UNIT_RECEIVER_ADJUSTMENT_DIRECT_DELIVERY(301, "UNIT_RECEIVER_ADJUSTMENT_DIRECT_DELIVERY"),
  UNIT_RECEIVER_ADJUSTMENT_WAREHOUSE_DELIVERY(302, "UNIT_RECEIVER_ADJUSTMENT_WAREHOUSE_DELIVERY"),
  WAREHOUSE_DELIVERY_RECEIPT(303, "WAREHOUSE_DELIVERY_RECEIPT"),
  USER_CREATE(401, "USER_CREATE"),
  USER_EDIT(402, "USER_EDIT"),
  USER_DELETE(403, "USER_DELETE"),
  ROLE_CREATE(404, "ROLE_CREATE"),
  ROLE_EDIT(405, "ROLE_EDIT"),
  ROLE_DELETE(406, "ROLE_DELETE"),
  USER_PASSWORD_CHANGE(407, "USER_PASSWORD_CHANGE"),
  USER_STORE_ADD(408, "USER_STORE_ADD"),
  USER_STORE_DELETE(409, "USER_STORE_DELETE"),
  USER_ROLE_ADD(410, "USER_ROLE_ADD"),
  USER_ROLE_DELETE(411, "USER_ROLE_DELETE"),
  ITEM_BASKET_CREATE(501, "ITEM_BASKET_CREATE"),
  ITEM_BASKET_EDIT(502, "ITEM_BASKET_EDIT"),
  ITEM_BASKET_DELETE(503, "ITEM_BASKET_DELETE"),
  ITEM_BASKET_PRINT(504, "ITEM_BASKET_PRINT"),
  FULFILLMENT_ORDER_ACCESSED(601, "FULFILLMENT_ORDER_ACCESSED"),
  FULFILLMENT_ORDER_FAILURE(602, "FULFILLMENT_ORDER_FAILURE"),
  FULFILLMENT_ORDER_PICK(604, "FULFILLMENT_ORDER_PICK"),
  FULFILLMENT_ORDER_DELIVER(605, "FULFILLMENT_ORDER_DELIVER"),
  FULFILLMENT_ORDER_REVERSE_PICK(606, "FULFILLMENT_ORDER_REVERSE_PICK"),
  FULFILLMENT_ORDER_DELIVERY_CREATE(607, "FULFILLMENT_ORDER_DELIVERY_CREATE"),
  FULFILLMENT_ORDER_DELIVERY_DELETE(608, "FULFILLMENT_ORDER_DELIVERY_DELETE"),
  FULFILLMENT_ORDER_DELIVERY_DISPATCH(609, "FULFILLMENT_ORDER_DELIVERY_DISPATCH"),
  FULFILLMENT_ORDER_DELIVERY_UPDATE(610, "FULFILLMENT_ORDER_DELIVERY_UPDATE"),
  FULFILLMENT_ORDER_PICK_ACCESSED(611, "FULFILLMENT_ORDER_PICK_ACCESSED"),
  FULFILLMENT_ORDER_PICK_CONFIRM(612, "FULFILLMENT_ORDER_PICK_CONFIRM"),
  FULFILLMENT_ORDER_PICK_CREATE(613, "FULFILLMENT_ORDER_PICK_CREATE"),
  FULFILLMENT_ORDER_PICK_DELETE(614, "FULFILLMENT_ORDER_PICK_DELETE"),
  FULFILLMENT_ORDER_PICK_UPDATE(615, "FULFILLMENT_ORDER_PICK_UPDATE"),
  FULFILLMENT_ORDER_REVERSE_PICK_CREATE(616, "FULFILLMENT_ORDER_REVERSE_PICK_CREATE"),
  FULFILLMENT_ORDER_REVERSE_PICK_DELETE(617, "FULFILLMENT_ORDER_REVERSE_PICK_DELETE"),
  FULFILLMENT_ORDER_REVERSE_PICK_UPDATE(618, "FULFILLMENT_ORDER_REVERSE_PICK_UPDATE");
  
  private final int code;
  
  private final String description;
  
  ActivityType(int paramInt1, String paramString1) {
    this.code = paramInt1;
    this.description = paramString1;
  }
  
  public Integer getCode() {
    return Integer.valueOf(this.code);
  }
  
  public String toString() {
    return this.description;
  }
  
  public static ActivityType toValue(Integer paramInteger) {
    if (paramInteger != null)
      for (ActivityType activityType : values()) {
        if (activityType.code == paramInteger.intValue())
          return activityType; 
      }  
    return null;
  }
}


/* Location:              C:\Users\aibrahim\eclipse-workspace\sim-client\lib\sim-common.jar!\oracle\retail\sim\common\activityhistory\ActivityType.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */