log4j.rootLogger=INFO, RFA

#Rolling File Appender
log4j.appender.RFA=org.apache.log4j.RollingFileAppender
log4j.appender.RFA.layout=org.apache.log4j.PatternLayout
log4j.appender.RFA.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %c - %m%n
log4j.appender.RFA.File=/u01/oracle/Weblogic_RSB/user_projects/domains/RSBDomain/servers/AdminServer/OMS_logs/CarreraTransferCreation.log
log4j.appender.RFA.MaxFileSize=100MB
log4j.appender.RFA.MaxBackupIndex=10

log4j.appender.RFA.Threshold = INFO
