spring.datasource.url = jdbc:oracle:thin:@192.168.50.111:1521/rmsprd.extrastores.com
spring.datasource.username = EXTRADEV
spring.datasource.password = wFeJdt6c
spring.datasource.driver-class-name = oracle.jdbc.driver.OracleDriver

apple.id = 1789802
apple.pricing.clientid = EXT802
apple.pricing.secret = myLbfUo0ge9kDIo3BFiLQlPe

apple.pricing.url.v2=https://dc-pricing-api.apple.com/pricing-api/api/v2
iPadDeptIds = {'626','606'}

logging.level.root = INFO
logging.file.name = logs/apple-pricing.log

feign.client.config.appleAPIService.loggerLevel = FULL
logging.level.com.extra.apple.pricing.service.AppleAPIService = debug
