<?xml version='1.0' encoding='UTF-8'?>
<xs:schema version="1.0" targetNamespace="http://com.logicinfo.oms/model/" xmlns:tns="http://com.logicinfo.oms/model/" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="SIMDeliveryDetail">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="numberOfOrders" minOccurs="1" nillable="false">
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:totalDigits value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="orderStatus" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="READY_TO_SHIP"/>
            <xs:enumeration value="UNDELIVERED"/>
            <xs:enumeration value="ALL"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="orderSource" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="E-COMMERCE"/>
            <xs:enumeration value="ORPOS"/>
            <xs:enumeration value="ALL"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="retrieveCustomerDetails" minOccurs="1" nillable="false">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="True"/>
            <xs:enumeration value="False"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="retrieveProductDetails" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:enumeration value="True"/>
            <xs:enumeration value="False"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="customerOrderResponseAddress">
    <xs:sequence>
      <xs:element name="customer_name" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="120"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="collector_name" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="120"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="customer_id" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
            <xs:totalDigits value="14"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="delivery_mobile" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="16"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="email" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="240"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="first_name" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="120"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="language" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="last_name" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="120"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="mobile" minOccurs="0">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="16"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="phone" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="address" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="240"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="city" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="120"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="country_id" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="10"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="district" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="15"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="shipping_address" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="240"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="customerOrderResponseItems">
    <xs:sequence>
      <xs:element name="delivery_id" minOccurs="1" nillable="false">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:totalDigits value="12"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="name" minOccurs="1" nillable="false">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="150"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="line_no" minOccurs="1">
        <xs:simpleType>
          <xs:restriction base="xs:unsignedInt">
          <xs:totalDigits value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="product_sku" minOccurs="1" nillable="false">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="150"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="quantity" minOccurs="1" nillable="false">
        <xs:simpleType>
          <xs:restriction base="xs:int">
            <xs:totalDigits value="12"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="total_value" minOccurs="1" nillable="true">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="05"/>
            <xs:totalDigits value="20"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="retail_currency_code" minOccurs="1" nillable="true">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="3"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="total_weight" minOccurs="1" nillable="true">
        <xs:simpleType>
          <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="05"/>
            <xs:totalDigits value="20"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
      <xs:element name="weight_uom" minOccurs="1" nillable="true">
        <xs:simpleType>
          <xs:restriction base="xs:string">
            <xs:maxLength value="4"/>
          </xs:restriction>
        </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
  <!-- <xs:complexType name="SIMDeliveryDetailResponse"> -->
  <!-- <xs:sequence minOccurs="1" maxOccurs="unbounded"> -->
  <xs:complexType name="SIMDeliveryDetailResponse">
    <xs:sequence>
      <xs:element maxOccurs="unbounded" minOccurs="0" ref="tns:Order"/>
    </xs:sequence>
  </xs:complexType>
  <xs:element name="Order">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="OrderNo" minOccurs="1" nillable="true">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="42"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="OrderValue" minOccurs="1" nillable="true">
          <xs:simpleType>
            <xs:restriction base="xs:decimal">
              <xs:minExclusive value="0"/>
              <xs:fractionDigits value="05"/>
              <xs:totalDigits value="20"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="IsCod" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Y"/>
              <xs:enumeration value="N"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="IsExpressDelivery" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Y"/>
              <xs:enumeration value="N"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="Carrier" minOccurs="1">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:enumeration value="Aramex"/>
              <xs:enumeration value="Smsa"/>
              <xs:enumeration value="Fetchr"/>
              <xs:enumeration value="Ups"/>
              <xs:enumeration value="Dhl"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="store_id" minOccurs="1" nillable="true">
          <xs:simpleType>
            <xs:restriction base="xs:int">
              <xs:totalDigits value="10"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="shipment_id" minOccurs="1" nillable="true">
          <xs:simpleType>
            <xs:restriction base="xs:string">
              <xs:maxLength value="20"/>
            </xs:restriction>
          </xs:simpleType>
        </xs:element>
        <xs:element name="customer_order_address" type="tns:customerOrderResponseAddress" minOccurs="0" maxOccurs="1"/>
        <xs:element name="customer_order_items" type="tns:customerOrderResponseItems" nillable="false" minOccurs="1" maxOccurs="100"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="processOrderReq" type="tns:SIMDeliveryDetail"/>
  <xs:element name="processOrderResp" type="tns:SIMDeliveryDetailResponse"/>
</xs:schema>