db.jndi=jdbc/oms
db.sim.jndi=jdbc/sim


rms.oralce.base.api.url=http://192.168.41.194:7117/FulfillOrderBean/FulfillOrderService
sim.oralce.base.api.url=http://exvm-qaadfapp01.extrastores.com:7511/StoreFulfillmentOrderBean/StoreFulfillmentOrderService
inv.adj.oralce.base.api.url=http://exvm-qaadfapp01.extrastores.com:7511/InventoryAdjustmentBean/InventoryAdjustmentService
inv.boOrd.oralce.base.api.url=http://exvm-qarmsapp01.extrastores.com:7117/InventoryBackOrderBean/InventoryBackOrderService
rms.fulfil.reverse.base.api.url=http://exvm-qaadfapp01.extrastores.com:7511/FulfillmentOrderReversePickBean/FulfillmentOrderReversePickService
rms.fulfil.delivery.base.api.url=http://exvm-qaadfapp01.extrastores.com:7511/FulfillmentOrderDeliveryBean/FulfillmentOrderDeliveryService




#rms.oralce.base.api.url=http://prodrmsapp.extrastores.com:7117/FulfillOrderBean/FulfillOrderService
#sim.oralce.base.api.url=http://prodsimapp.extrastores.com:7511/StoreFulfillmentOrderBean/StoreFulfillmentOrderService
#inv.adj.oralce.base.api.url=http://prodsimapp.extrastores.com:7511/InventoryAdjustmentBean/InventoryAdjustmentService
#inv.boOrd.oralce.base.api.url=http://prodrmsapp.extrastores.com:7117/InventoryBackOrderBean/InventoryBackOrderService
#rms.fulfil.reverse.base.api.url=http://prodsimapp.extrastores.com:7511/FulfillmentOrderReversePickBean/FulfillmentOrderReversePickService
#rms.fulfil.delivery.base.api.url=http://prodsimapp.extrastores.com:7511/FulfillmentOrderDeliveryBean/FulfillmentOrderDeliveryService
