log4j.rootLogger=INFO, RFA 

#Rolling File Appender
log4j.appender.RFA=org.apache.log4j.DailyRollingFileAppender
log4j.appender.RFA.layout=org.apache.log4j.PatternLayout
log4j.appender.RFA.layout.ConversionPattern=[%t] %d{yyyy-MM-dd HH:mm:ss} %c - %m%n
log4j.appender.RFA.File=/u01/oracle/Weblogic_RSB/user_projects/domains/RSBDomain/servers/AdminServer/OMS_logs/oms-cancellation.log
log4j.appender.RFA.DatePattern='.'yyyy-MM-dd


# Set the logger level of File Appender to WARN
log4j.appender.RFA.Threshold = INFO