
package com.oracle.retail.rms.integration.services.fulfillorderservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.fulfilordcfmcol.v1.FulfilOrdCfmCol;
import com.oracle.retail.integration.base.bo.fulfilordcoldesc.v1.FulfilOrdColDesc;
import com.oracle.retail.integration.base.bo.fulfilordcolref.v1.FulfilOrdColRef;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FulfillOrderPortType", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.fulfilordcfmcol.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcfmdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcfmdtl.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcolref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilorddesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilorddtl.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilorddtlref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.locoffulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.custom.bo.eofbrfulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.localization.bo.brfulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.rms.integration.services.fulfillorderservice.v1.ObjectFactory.class
})
public interface FulfillOrderPortType {


    /**
     * 
     * @param fulfilOrdColDesc
     * @return
     *     returns com.oracle.retail.integration.base.bo.fulfilordcfmcol.v1.FulfilOrdCfmCol
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws EntityAlreadyExistsWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "FulfilOrdCfmCol", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FulfilOrdCfmCol/v1")
    @RequestWrapper(localName = "createFulfilOrdColDesc", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", className = "com.oracle.retail.rms.integration.services.fulfillorderservice.v1.CreateFulfilOrdColDesc")
    @ResponseWrapper(localName = "createFulfilOrdColDescResponse", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", className = "com.oracle.retail.rms.integration.services.fulfillorderservice.v1.CreateFulfilOrdColDescResponse")
    public FulfilOrdCfmCol createFulfilOrdColDesc(
        @WebParam(name = "FulfilOrdColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FulfilOrdColDesc/v1")
        FulfilOrdColDesc fulfilOrdColDesc)
        throws EntityAlreadyExistsWSFaultException, IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fulfilOrdColRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws EntityAlreadyExistsWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "cancelFulfilOrdColRef", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", className = "com.oracle.retail.rms.integration.services.fulfillorderservice.v1.CancelFulfilOrdColRef")
    @ResponseWrapper(localName = "cancelFulfilOrdColRefResponse", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", className = "com.oracle.retail.rms.integration.services.fulfillorderservice.v1.CancelFulfilOrdColRefResponse")
    public InvocationSuccess cancelFulfilOrdColRef(
        @WebParam(name = "FulfilOrdColRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FulfilOrdColRef/v1")
        FulfilOrdColRef fulfilOrdColRef)
        throws EntityAlreadyExistsWSFaultException, IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", className = "com.oracle.retail.rms.integration.services.fulfillorderservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", className = "com.oracle.retail.rms.integration.services.fulfillorderservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
