package com.oracle.retail.rms.integration.services.fulfillorderservice.v1;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.4.0.6436

public class FulfillOrderPortClient
{
  public static void main(String [] args)
  {
    FulfillOrderService fulfillOrderService = new FulfillOrderService();
    FulfillOrderPortType fulfillOrderPortType = fulfillOrderService.getFulfillOrderPort();
    // Add your code to call the desired methods.
  }
}
