
package com.oracle.retail.rms.integration.services.fulfillorderservice.v1;

import com.logicinfo.oms.beans.OMSUtilCommons;
import com.logicinfo.oms.ejb.OMSUtilSessionEJB;
import com.logicinfo.oms.util.OMSUtil;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FulfillOrderService", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", wsdlLocation = "http://licrpap14-extra.logicindia.com:17040/FulfillOrderBean/FulfillOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frms%2Fintegration%2Fservices%2FFulfillOrderService%2Fv1%7DFulfillOrderService")
public class FulfillOrderService
    extends Service
{

    private final static URL FULFILLORDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.rms.integration.services.fulfillorderservice.v1.FulfillOrderService.class.getName());

    static {
        URL url = null;
        try {
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("RMS_FULFIL_ORDER");
                       URL baseUrl;
            baseUrl = com.oracle.retail.rms.integration.services.fulfillorderservice.v1.FulfillOrderService.class.getResource(".");
            //url = new URL(baseUrl, "http://licrpap14-extra.logicindia.com:17040/FulfillOrderBean/FulfillOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frms%2Fintegration%2Fservices%2FFulfillOrderService%2Fv1%7DFulfillOrderService");
            url = new URL(baseUrl,wsdlUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://licrpap14-extra.logicindia.com:17040/FulfillOrderBean/FulfillOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frms%2Fintegration%2Fservices%2FFulfillOrderService%2Fv1%7DFulfillOrderService', retrying as a local file");
            logger.warning(e.getMessage());
        }catch (SOAPException e) {
        }
        FULFILLORDERSERVICE_WSDL_LOCATION = url;
    }

    public FulfillOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FulfillOrderService() {
        super(FULFILLORDERSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", "FulfillOrderService"));
    }

    /**
     * 
     * @return
     *     returns FulfillOrderPortType
     */
    @WebEndpoint(name = "FulfillOrderPort")
    public FulfillOrderPortType getFulfillOrderPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", "FulfillOrderPort"), FulfillOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FulfillOrderPortType
     */
    @WebEndpoint(name = "FulfillOrderPort")
    public FulfillOrderPortType getFulfillOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", "FulfillOrderPort"), FulfillOrderPortType.class, features);
    }

}
