#QA
user_name=RMS14
password=retQAtrex123
url=jdbc:oracle:thin:@exvm-qarmsdb02.extrastores.com:1521/RMSQA.extrastores.com
driver=oracle.jdbc.driver.OracleDriver
cancellation.api.url = http://exvm-qaribapp01.extrastores.com:7701/omscancellation/omscancellation


#PROD
#user_name=RMS14
#password=kcv123retlv
#url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
#driver=oracle.jdbc.driver.OracleDriver
#cancellation.api.url = http://192.168.50.132:7701/omscancellation/omscancellation




