
log4j.rootLogger=INFO, RFA 

# Console appender configuration
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
# Pattern to output the caller's file name and line number.
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n


#Rolling File Appender
log4j.appender.RFA=org.apache.log4j.DailyRollingFileAppender
log4j.appender.RFA.layout=org.apache.log4j.PatternLayout
log4j.appender.RFA.layout.ConversionPattern=[%t] %d{yyyy-MM-dd HH:mm:ss} %c - %m%n
log4j.appender.RFA.File=/u01/oracle/Weblogic_RSB/user_projects/domains/RSBDomain/servers/AdminServer/OMS_logs/HybrisCancellation.log
log4j.appender.RFA.DatePattern='.'yyyy-MM-dd


# Set the logger level of File Appender to WARN
log4j.appender.RFA.Threshold = INFO
