#spring.datasource.url=jdbc:oracle:thin:@192.168.41.187:1521/RMSQA.extrastores.com
#spring.datasource.username=rms14
#spring.datasource.password=retQAtrex123

spring.datasource.url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
spring.datasource.username=rms14
spring.datasource.password=kcv123retlv
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver

spring.datasource.hikari.connectionTimeout = 300000000


#zatca.api.url = https://gw-apic-gov.gazt.gov.sa/e-invoicing/simulation
zatca.api.url = https://gw-apic-gov.gazt.gov.sa/e-invoicing/core
## Compilance Certificate generated through Fatoora portal.
#zatca.api.binary-token=TUlJQ0hqQ0NBY09nQXdJQkFnSUdBWVM5ZkZkK01Bb0dDQ3FHU000OUJBTUNNQlV4RXpBUkJnTlZCQU1NQ21WSmJuWnZhV05wYm1jd0hoY05Nakl4TVRJNE1Ea3dOVFE0V2hjTk1qY3hNVEkzTWpFd01EQXdXakJnTVFzd0NRWURWUVFHRXdKVFFURVRNQkVHQTFVRUN3d0tNekF3TkRZNE56Z3hPVEVwTUNjR0ExVUVDZ3dnVlc1cGRHVmtJRVZzWldOMGNtOXVhV056SUVOdmJYQmhibmtnWlZoMGNtRXhFVEFQQmdOVkJBTU1DR1ZZZEhKaFJVZFRNRll3RUFZSEtvWkl6ajBDQVFZRks0RUVBQW9EUWdBRWNDbkJEcS96S1pDdVhCSk9wNmhXb250L0xXV0hYY1Fma1RxQUIyekJqeEFWU2JYOFhRdmZvaFhDZGNpVHhxbFk5M0g5M0VGZHRobkR0VWxHQWZ2TlJLT0J0akNCc3pBTUJnTlZIUk1CQWY4RUFqQUFNSUdpQmdOVkhSRUVnWm93Z1pla2daUXdnWkV4UFRBN0JnTlZCQVFNTkRFdFpWaDBjbUY4TWkweE1ERjhNeTAzWlRSaVpqQm1ZUzAyWldaaUxURXhaV1F0WVRGbFlpMHdNalF5WVdNeE1qQXdNREl4SHpBZEJnb0praWFKay9Jc1pBRUJEQTh6TURBME5qZzNPREU1TURBd01ETXhEVEFMQmdOVkJBd01CREV4TURBeER6QU5CZ05WQkJvTUJrdElUMEpCVWpFUE1BMEdBMVVFRHd3R2NtVjBZV2xzTUFvR0NDcUdTTTQ5QkFNQ0Ewa0FNRVlDSVFENGNwQ2JlWGg1ckttZ01NbExKS1paSDFWM2FlZyt5QVNNY3JPbG1FOVl4UUloQU9zcUhlVWljbHlpbmwySjdLM2FXdmVjdVRzYlF1dGxkZ0JBRW1WcUdTcHg=
#zatca.api.secret=wgIa0z+IS4WQUroaY2csHb1Fhc0e+9KJgtsTbWWBS2M=
#zatca.api.private-key=MIGNAgEAMBAGByqGSM49AgEGBSuBBAAKBHYwdAIBAQQgw12wPayZPDknJ0U9FeMH8SVKnFzvAIrFZ+uViBnMClSgBwYFK4EEAAqhRANCAARwKcEOr/MpkK5cEk6nqFaie38tZYddxB+ROoAHbMGPEBVJtfxdC9+iFcJ1yJPGqVj3cf3cQV22GcO1SUYB+81E
## Production test certificate from developer portal
zatca.api.binary-token = TUlJRU96Q0NBK0tnQXdJQkFnSVRmd0FBQTJ6dGFCYVltaGtJMWdBQkFBQURiREFLQmdncWhrak9QUVFEQWpCaU1SVXdFd1lLQ1pJbWlaUHlMR1FCR1JZRmJHOWpZV3d4RXpBUkJnb0praWFKay9Jc1pBRVpGZ05uYjNZeEZ6QVZCZ29Ka2lhSmsvSXNaQUVaRmdkbGVIUm5ZWHAwTVJzd0dRWURWUVFERXhKUVVscEZTVTVXVDBsRFJWTkRRVEl0UTBFd0hoY05Nakl4TWpJMk1EWXhOVFE1V2hjTk1qY3hNakkxTURZeE5UUTVXakJnTVFzd0NRWURWUVFHRXdKVFFURXBNQ2NHQTFVRUNoTWdWVzVwZEdWa0lFVnNaV04wY205dWFXTnpJRU52YlhCaGJua2daVmgwY21FeEV6QVJCZ05WQkFzVENqTXdNRFEyT0RjNE1Ua3hFVEFQQmdOVkJBTVRDR1ZZZEhKaFJVZFRNRll3RUFZSEtvWkl6ajBDQVFZRks0RUVBQW9EUWdBRW9Dayt1LzBHalJoUHhaSjFVVGVVNmI4aEN4Y2VGSWJWd0YyVXM3RmVhL3FXRmFlL3lGUVJaaTl0aktpVkhIWDJ3QlJ6NXNOTnJBSGdPdllDQllQYU02T0NBbm93Z2dKMk1JR2lCZ05WSFJFRWdab3dnWmVrZ1pRd2daRXhQVEE3QmdOVkJBUU1OREV0WlZoMGNtRjhNaTB4TURGOE15MDRZVGsyTVRJd1lTMDROR1V3TFRFeFpXUXRZVEZsWWkwd01qUXlZV014TWpBd01ESXhIekFkQmdvSmtpYUprL0lzWkFFQkRBOHpNREEwTmpnM09ERTVNREF3TURNeERUQUxCZ05WQkF3TUJERXhNREF4RHpBTkJnTlZCQm9NQmt0SVQwSkJVakVQTUEwR0ExVUVEd3dHY21WMFlXbHNNQjBHQTFVZERnUVdCQlQyeEozQnFqTmNYSFZmZHYwREZkRjMrS1QzM2pBZkJnTlZIU01FR0RBV2dCUlp5SEtlZVRWcDZyelpsZFRYNEdScEFnWVFHVEJPQmdOVkhSOEVSekJGTUVPZ1FhQS9oajFvZEhSd09pOHZZM0pzTWk1NllYUmpZUzVuYjNZdWMyRXZRMlZ5ZEVWdWNtOXNiQzlRVWxwRlNVNVdUMGxEUlZORFFUSXRRMEVvTVNrdVkzSnNNSUdvQmdnckJnRUZCUWNCQVFTQm16Q0JtREFwQmdnckJnRUZCUWN3QVlZZGFIUjBjRG92TDJOeWJESXVlbUYwWTJFdVoyOTJMbk5oTDI5amMzQXdhd1lJS3dZQkJRVUhNQUtHWDJoMGRIQTZMeTloYVdFeUxucGhkR05oTG1kdmRpNXpZUzlEWlhKMFJXNXliMnhzTDFCU1drVnBiblp2YVdObFUwTkJNaTVsZUhSbllYcDBMbWR2ZGk1c2IyTmhiRjlRVWxwRlNVNVdUMGxEUlZORFFUSXRRMEVvTVNrdVkzSjBNQTRHQTFVZER3RUIvd1FFQXdJSGdEQThCZ2tyQmdFRUFZSTNGUWNFTHpBdEJpVXJCZ0VFQVlJM0ZRaUJocWdkaE5EN0VvYnRuU1NIenZzWjA4QlZab2Y2cFdXRjJZUStBZ0ZrQWdFUU1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TURCZ2dyQmdFRkJRY0RBakFuQmdrckJnRUVBWUkzRlFvRUdqQVlNQW9HQ0NzR0FRVUZCd01ETUFvR0NDc0dBUVVGQndNQ01Bb0dDQ3FHU000OUJBTUNBMGNBTUVRQ0lDdS9IRGJJNUsxVDljRyswVkllOHo1TWlpa29aNDVJbDJHVGY3QThLenpaQWlCNFY1OVoyY0ZpWkpOdDdUemIyL0c3TFM0UVlBVEJDeUVLclI4VTR5Z1BUZz09
zatca.api.secret = T2kAh+JhX1+rRl5WE7PPRginlFofmBFlha0VnW97JRY=
zatca.api.private-key= MIGNAgEAMBAGByqGSM49AgEGBSuBBAAKBHYwdAIBAQQgV31CLXMeGJg81kf3jim9zp0JvVgOcg9gaN9997Ngrb+gBwYFK4EEAAqhRANCAASgKT67/QaNGE/FknVRN5TpvyELFx4UhtXAXZSzsV5r+pYVp7/IVBFmL22MqJUcdfbAFHPmw02sAeA69gIFg9oz

zatca.api.seller.street-name = Malik Ibn Qays
zatca.api.seller.building-num = 8868
zatca.api.seller.additional-num = 3176
zatca.api.seller.city-div = ArRawabi
zatca.api.seller.city = AL KHOBAR
zatca.api.seller.postal = 34421
zatca.api.seller.country = SA
zatca.api.seller.vat = 300468781900003
zatca.api.seller.reg-name = United Electronics Company eXtra
zatca.api.seller.ebs-crn = {Extra: '2051029841', UCFS: '2051224103'}

zatca.xml.validate = true

b2b.pos.stores = {'19001','19002','19003','19004'}

feign.client.config.bipService.loggerLevel = none
logging.level.com.extra.einvoicing.service.client.IBIPReportService= warn

feign.client.config.zatcaAPI.loggerLevel = none
logging.level.com.extra.einvoicing.service.client.IZatcaInterfaceAPI= warn

feign.client.config.emailService.loggerLevel = FULL
logging.level.com.extra.einvoicing.service.client.IEmailService= debug

feign.client.config.default.connectTimeout = 160000000
feign.client.config.default.readTimeout = 160000000

#report.bip.url = http://exvm-qacoapp02.extrastores.com:8111/xmlpserver/services/PublicReportService
report.bip.url = http://prodbip-app3.extrastores.com:8111/xmlpserver/services/PublicReportService
report.bip.username = bip.admin
report.bip.password = Logic123
report.bip.path = {AP:'/Extra Reports/IT/VAT/EBS_VAT_EINVOICE.xdo', UCFS: '/Extra Reports/IT/VAT/UCFS_EBS_VAT_EINVOICE.xdo', AR: '/Extra Reports/IT/VAT/EBS_VAT_AR_CP.xdo', POS: '/Extra Reports/IT/VAT/POS_B2B_REP.xdo'}
report.bip.email-body = Dear Supplier, kindly find attached Claim notification that has been booked against you account. Please do not reply to this autogenerated email.
report.bip.email-from = bis.reports@extra.com
report.bip.email-server = extrastores.com
report.bip.email-subject = TAX VAT notification invoice# %S
report.bip.email-cc = {AP: 'asikumar.ibrahim@logicinfo.com'}
report.bip.email-to = {AP: 'asikumar.ibrahim@logicinfo.com'}

report.bip.pos.email-to = sami.m@extra.com,valencia.d@extra.com

## Email Configuration
email.config.url = https://dev-mule4-email-v2-cc-changes.uk-e1.cloudhub.io/communication
email.config.header.req-id = 644e1dd7-2a7f-18fb-b8ed-ed78c3f92c2b
email.config.header.application-id = E-COMMERCE
email.config.username = 0796c29743d546a4ae870a4d1d7a7799
email.config.password = 8D89c4CB4C59498199F8db209F71a13f

##Log Configuration
logging.level.root = info
logging.file.name = ./log/einvoicing.log
#logging.pattern.console =

## Scheduler Configuration

schedule.ebs.cron = 0 */1 * * NOV THU

schedule.pos.cron = 0 */1 * * NOV THU

schedule.canret.cron = 0 */1 * * NOV THU

schedule.report.cron = 0 */1 * * NOV THU

schedule.siebel.cron = 0 */1 * * NOV THU

schedule.email.cron = 0 */1 * * * *