package oracle.retail.sim.service.ejb;

import java.util.List;
import java.util.Map;
import javax.ejb.Remote;
import oracle.retail.sim.common.business.FunctionalArea;
import oracle.retail.sim.common.core.CompressedObject;
import oracle.retail.sim.common.core.SimSession;
import oracle.retail.sim.common.report.ReportResponse;
import oracle.retail.sim.common.report.StorePrinter;
import oracle.retail.sim.common.reportformat.ReportTypeFormat;
import oracle.retail.sim.common.uin.SerialNumberValue;
import oracle.retail.sim.common.uin.UINDetail;
import oracle.retail.sim.common.uin.UINDetailLookupQueryFilter;
import oracle.retail.sim.common.uin.UINDetailVO;
import oracle.retail.sim.common.uin.UINGenerateVO;
import oracle.retail.sim.common.uin.UINHistoryVO;
import oracle.retail.sim.common.uin.UINLabelVO;
import oracle.retail.sim.common.uin.UINModifyVO;
import oracle.retail.sim.common.uin.UINProblemDetail;
import oracle.retail.sim.common.uin.UINProblemDetailQueryFilter;
import oracle.retail.sim.common.uin.UINSaleType;
import oracle.retail.sim.common.uin.UINSelectVO;
import oracle.retail.sim.common.uin.UINStatus;
import oracle.retail.sim.common.uin.UINStoreDept;
import oracle.retail.sim.common.uin.UINStoreItem;
import oracle.retail.sim.common.uin.UINType;

@Remote
public interface UINInterface {
  CompressedObject<Map<String, List<Long>>> createAndPrintUINAgsnDetails(CompressedObject<Map<String, Integer>> paramCompressedObject, CompressedObject<Long> paramCompressedObject1, CompressedObject<FunctionalArea> paramCompressedObject2, CompressedObject<StorePrinter> paramCompressedObject3, CompressedObject<ReportTypeFormat> paramCompressedObject4, CompressedObject<SimSession> paramCompressedObject5) throws Exception;
  
  CompressedObject<Map<String, List<Long>>> createUINAgsnDetails(CompressedObject<Long> paramCompressedObject, CompressedObject<Map<String, Integer>> paramCompressedObject1, CompressedObject<FunctionalArea> paramCompressedObject2, CompressedObject<SimSession> paramCompressedObject3) throws Exception;
  
  CompressedObject<?> createUINDetail(CompressedObject<Long> paramCompressedObject, CompressedObject<List<UINModifyVO>> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
  
  CompressedObject<UINStatus> createUINProblemDetail(CompressedObject<UINDetail> paramCompressedObject, CompressedObject<UINSaleType> paramCompressedObject1, CompressedObject<String> paramCompressedObject2, CompressedObject<String> paramCompressedObject3, CompressedObject<SimSession> paramCompressedObject4) throws Exception;
  
  CompressedObject<List<SerialNumberValue>> findAutoGeneratedSerialNumbers(CompressedObject<String> paramCompressedObject, CompressedObject<Long> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
  
  CompressedObject<Map<String, Long>> findReportFormatIds(CompressedObject<List<String>> paramCompressedObject, CompressedObject<Long> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
  
  CompressedObject<SerialNumberValue> findSerialNumberValue(CompressedObject<String> paramCompressedObject1, CompressedObject<String> paramCompressedObject2, CompressedObject<SimSession> paramCompressedObject) throws Exception;
  
  CompressedObject<SerialNumberValue> findSerialNumberValueOrCreate(CompressedObject<Long> paramCompressedObject, CompressedObject<String> paramCompressedObject1, CompressedObject<String> paramCompressedObject2, CompressedObject<UINType> paramCompressedObject3, CompressedObject<FunctionalArea> paramCompressedObject4, CompressedObject<SimSession> paramCompressedObject5) throws Exception;
  
  CompressedObject<List<SerialNumberValue>> findSerialNumberValues(CompressedObject<String> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<UINDetail> findUINDetail(CompressedObject<String> paramCompressedObject1, CompressedObject<String> paramCompressedObject2, CompressedObject<SimSession> paramCompressedObject) throws Exception;
  
  CompressedObject<List<UINDetailVO>> findUINDetailVOs(CompressedObject<String> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<List<UINDetailVO>> findUINDetailVOs2(CompressedObject<UINDetailLookupQueryFilter> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<List<UINHistoryVO>> findUINHistoryVOs(CompressedObject<String> paramCompressedObject1, CompressedObject<String> paramCompressedObject2, CompressedObject<SimSession> paramCompressedObject) throws Exception;
  
  CompressedObject<Map<Long, UINLabelVO>> findUINLabels(CompressedObject<SimSession> paramCompressedObject) throws Exception;
  
  CompressedObject<List<UINProblemDetail>> findUINProblemDetails(CompressedObject<UINProblemDetailQueryFilter> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<List<UINSelectVO>> findUINSelectVOs(CompressedObject<String> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<List<UINStoreDept>> findUINStoreDepartments(CompressedObject<Long> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<List<String>> generateUINDetail(CompressedObject<UINGenerateVO> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<Boolean> isUINRequiredAtAutoStore(CompressedObject<Long> paramCompressedObject, CompressedObject<List<String>> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
  
  CompressedObject<ReportResponse> printUINAgsnDetails(CompressedObject<Map<String, List<String>>> paramCompressedObject, CompressedObject<Long> paramCompressedObject1, CompressedObject<StorePrinter> paramCompressedObject2, CompressedObject<ReportTypeFormat> paramCompressedObject3, CompressedObject<SimSession> paramCompressedObject4) throws Exception;
  
  CompressedObject<UINDetail> readUINDetail(CompressedObject<Long> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<String> readUINLabel(CompressedObject<String> paramCompressedObject, CompressedObject<Long> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
  
  CompressedObject<UINStoreItem> readUINStoreItem(CompressedObject<String> paramCompressedObject, CompressedObject<Long> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
  
  CompressedObject<?> updateProblemDetailsToResolved(CompressedObject<List<UINProblemDetail>> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<?> updateStoreDepartments(CompressedObject<List<UINStoreDept>> paramCompressedObject, CompressedObject<SimSession> paramCompressedObject1) throws Exception;
  
  CompressedObject<?> updateUINDetail(CompressedObject<Long> paramCompressedObject, CompressedObject<List<UINModifyVO>> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
  
  CompressedObject<?> updateUINDetailStatus(CompressedObject<Long> paramCompressedObject, CompressedObject<UINStatus> paramCompressedObject1, CompressedObject<SimSession> paramCompressedObject2) throws Exception;
}


/* Location:              C:\Users\aibrahim\eclipse-workspace\sim-client\lib\sim-common.jar!\oracle\retail\sim\service\ejb\UINInterface.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */