#SIM DB Details
#sim14.db.jdbc-url=jdbc:oracle:thin:@exvm-qarmsdb01.extrastores.com:1521/SIMQA.extrastores.com
#sim14.db.user=sim14
#sim14.db.password=retQAtrex123

#WMS DB Details
#wms.db.jdbc-url=jdbc:oracle:thin:@exvm-qarmsdb01.extrastores.com:1521/WMSQA.extrastores.com
#wms.db.user=WMS14
#wms.db.password=retQAtrex123

#SIM DB Details
sim14.db.jdbc-url=jdbc:oracle:thin:@retprd-scan.extrastores.com:1521/SIMPRD.extrastores.com
sim14.db.user=sim14
sim14.db.password=kcv123retlv

#WMS DB Details
wms.db.jdbc-url=jdbc:oracle:thin:@retprd-scan.extrastores.com:1521/WMSPRD.extrastores.com
wms.db.user=siddheshwar
wms.db.password=siddheshwar22


#ORDER_EMAIL
ORDER.NOTIFICATION.FROM.EMAIL = ORDER_FROM_EMAIL
ORDER.NOTIFICATION.ORDER.EMAIL.TEMPLATE = ORDER_EMAIL_TEMPLATE
ORDER.NOTIFICATION.NORMAL = NORMAL
ORDER.NOTIFICATION.REMINDER = REMINDER
ORDER.NOTIFICATION.FROM.PHONE.NUMBER = ORDER_FROM_PHONE_NUMBER
ORDER.NOTIFICATION.ORDER.SMS.TEMPLATE = ORDER_SMS_TEMPLATE

xml.file.loc.store=./xmls/store/
xml.file.loc.inv=./xmls/inventory/
xml.file.loc.trickle=./xmls/trickle/

#Inactive tracing order details Api call PROD
sim.invalide.tracking.id.update.api.url=https://prod-shipment-cancellation-v1.uk-e1.cloudhub.io/shipment/v1/cancel
client.id=0796c29743d546a4ae870a4d1d7a7799
cient.secret=8D89c4CB4C59498199F8db209F71a13f
client.and.secret.id.base64.encoded=MDc5NmMyOTc0M2Q1NDZhNGFlODcwYTRkMWQ3YTc3OTk6OEQ4OWM0Q0I0QzU5NDk4MTk5RjhkYjIwOUY3MWExM2Y=

#Inactive tracing order details Api call QA
#sim.invalide.tracking.id.update.api.url=https://qa-shipment-cancellation-v1.uk-e1.cloudhub.io/shipment/v1/cancel
#client.id=c958cf954d7b46d794b1c879cd5a2b0b
#cient.secret=2999737d83d2424AA08098DB10d51eB8
#client.and.secret.id.base64.encoded=Yzk1OGNmOTU0ZDdiNDZkNzk0YjFjODc5Y2Q1YTJiMGI6Mjk5OTczN2Q4M2QyNDI0QUEwODA5OERCMTBkNTFlQjg
											                            
		                            
#Inactive tracing order details Api call UAT
#sim.invalide.tracking.id.update.api.url=https://uat-shipment-cancellation-v1.uk-e1.cloudhub.io/shipment/v1/cancel
#client.id=0561885b53ac48f9972c6141b6675aa1
#cient.secret=22F12E25E2f04da2965e4B56590BFF92
#client.and.secret.id.base64.encoded=MDU2MTg4NWI1M2FjNDhmOTk3MmM2MTQxYjY2NzVhYTE6MjJGMTJFMjVFMmYwNGRhMjk2NWU0QjU2NTkwQkZGOTI=
											                            
		 
