
package com.oracle.retail.sim.integration.services.storetostoretransferservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StoreToStoreTransferService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", wsdlLocation = "http://exvm-qaadfapp01.extrastores.com:7511/StoreToStoreTransferBean/StoreToStoreTransferService?wsdl")
public class StoreToStoreTransferService
    extends Service
{

    private final static URL STORETOSTORETRANSFERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STORETOSTORETRANSFERSERVICE_EXCEPTION;
    private final static QName STORETOSTORETRANSFERSERVICE_QNAME = new QName("http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", "StoreToStoreTransferService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exvm-qaadfapp01.extrastores.com:7511/StoreToStoreTransferBean/StoreToStoreTransferService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STORETOSTORETRANSFERSERVICE_WSDL_LOCATION = url;
        STORETOSTORETRANSFERSERVICE_EXCEPTION = e;
    }

    public StoreToStoreTransferService() {
        super(__getWsdlLocation(), STORETOSTORETRANSFERSERVICE_QNAME);
    }

    public StoreToStoreTransferService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STORETOSTORETRANSFERSERVICE_QNAME, features);
    }

    public StoreToStoreTransferService(URL wsdlLocation) {
        super(wsdlLocation, STORETOSTORETRANSFERSERVICE_QNAME);
    }

    public StoreToStoreTransferService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STORETOSTORETRANSFERSERVICE_QNAME, features);
    }

    public StoreToStoreTransferService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreToStoreTransferService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StoreToStoreTransferPortType
     */
    @WebEndpoint(name = "StoreToStoreTransferPort")
    public StoreToStoreTransferPortType getStoreToStoreTransferPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", "StoreToStoreTransferPort"), StoreToStoreTransferPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StoreToStoreTransferPortType
     */
    @WebEndpoint(name = "StoreToStoreTransferPort")
    public StoreToStoreTransferPortType getStoreToStoreTransferPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", "StoreToStoreTransferPort"), StoreToStoreTransferPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STORETOSTORETRANSFERSERVICE_EXCEPTION!= null) {
            throw STORETOSTORETRANSFERSERVICE_EXCEPTION;
        }
        return STORETOSTORETRANSFERSERVICE_WSDL_LOCATION;
    }

}
