package oracle.retail.sim.service.uin;

import java.util.List;
import java.util.Map;
import oracle.retail.sim.common.business.FunctionalArea;
import oracle.retail.sim.common.report.ReportResponse;
import oracle.retail.sim.common.report.StorePrinter;
import oracle.retail.sim.common.reportformat.ReportTypeFormat;
import oracle.retail.sim.common.uin.SerialNumberValue;
import oracle.retail.sim.common.uin.UINDetail;
import oracle.retail.sim.common.uin.UINDetailLookupQueryFilter;
import oracle.retail.sim.common.uin.UINDetailVO;
import oracle.retail.sim.common.uin.UINGenerateVO;
import oracle.retail.sim.common.uin.UINHistoryVO;
import oracle.retail.sim.common.uin.UINLabelVO;
import oracle.retail.sim.common.uin.UINModifyVO;
import oracle.retail.sim.common.uin.UINProblemDetail;
import oracle.retail.sim.common.uin.UINProblemDetailQueryFilter;
import oracle.retail.sim.common.uin.UINSaleType;
import oracle.retail.sim.common.uin.UINSelectVO;
import oracle.retail.sim.common.uin.UINStatus;
import oracle.retail.sim.common.uin.UINStoreDept;
import oracle.retail.sim.common.uin.UINStoreItem;
import oracle.retail.sim.common.uin.UINType;

public abstract class UINServices {
  public abstract boolean isUINRequiredAtAutoStore(Long paramLong, List<String> paramList) throws Exception;
  
  public abstract List<UINStoreDept> findUINStoreDepartments(Long paramLong) throws Exception;
  
  public abstract void updateStoreDepartments(List<UINStoreDept> paramList) throws Exception;
  
  public abstract Map<Long, UINLabelVO> findUINLabels() throws Exception;
  
  public abstract UINStoreItem readUINStoreItem(String paramString, Long paramLong) throws Exception;
  
  public abstract SerialNumberValue findSerialNumberValue(String paramString1, String paramString2) throws Exception;
  
  public abstract List<SerialNumberValue> findSerialNumberValues(String paramString) throws Exception;
  
  public abstract List<SerialNumberValue> findAutoGeneratedSerialNumbers(String paramString, Long paramLong) throws Exception;
  
  public abstract SerialNumberValue findSerialNumberValueOrCreate(Long paramLong, String paramString1, String paramString2, UINType paramUINType, FunctionalArea paramFunctionalArea) throws Exception;
  
  public abstract UINDetail findUINDetail(String paramString1, String paramString2) throws Exception;
  
  public abstract UINDetail readUINDetail(Long paramLong) throws Exception;
  
  public abstract String readUINLabel(String paramString, Long paramLong) throws Exception;
  
  public abstract void updateUINDetailStatus(Long paramLong, UINStatus paramUINStatus) throws Exception;
  
  public abstract List<UINSelectVO> findUINSelectVOs(String paramString) throws Exception;
  
  public abstract List<UINDetailVO> findUINDetailVOs(UINDetailLookupQueryFilter paramUINDetailLookupQueryFilter) throws Exception;
  
  public abstract List<UINDetailVO> findUINDetailVOs(String paramString) throws Exception;
  
  public abstract List<UINProblemDetail> findUINProblemDetails(UINProblemDetailQueryFilter paramUINProblemDetailQueryFilter) throws Exception;
  
  public abstract void updateProblemDetailsToResolved(List<UINProblemDetail> paramList) throws Exception;
  
  public abstract List<UINHistoryVO> findUINHistoryVOs(String paramString1, String paramString2) throws Exception;
  
  public abstract List<String> generateUINDetail(UINGenerateVO paramUINGenerateVO) throws Exception;
  
  public abstract void createUINDetail(Long paramLong, List<UINModifyVO> paramList) throws Exception;
  
  public abstract void updateUINDetail(Long paramLong, List<UINModifyVO> paramList) throws Exception;
  
  public abstract Map<String, List<Long>> createAndPrintUINAgsnDetails(Map<String, Integer> paramMap, Long paramLong, FunctionalArea paramFunctionalArea, StorePrinter paramStorePrinter, ReportTypeFormat paramReportTypeFormat) throws Exception;
  
  public abstract Map<String, List<Long>> createUINAgsnDetails(Long paramLong, Map<String, Integer> paramMap, FunctionalArea paramFunctionalArea) throws Exception;
  
  public abstract ReportResponse printUINAgsnDetails(Map<String, List<String>> paramMap, Long paramLong, StorePrinter paramStorePrinter, ReportTypeFormat paramReportTypeFormat) throws Exception;
  
  public abstract UINStatus createUINProblemDetail(UINDetail paramUINDetail, UINSaleType paramUINSaleType, String paramString1, String paramString2) throws Exception;
  
  public abstract Map<String, Long> findReportFormatIds(List<String> paramList, Long paramLong) throws Exception;
}


/* Location:              C:\Users\aibrahim\eclipse-workspace\sim-client\lib\sim-common.jar!\oracle\retail\sim\servic\\uin\UINServices.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */