user_name=EXTRADEV
password=wFeJdt6c
url=jdbc:oracle:thin:@exvm-qarmsdb02.extrastores.com:1521/RMSQA.extrastores.com
driver=oracle.jdbc.driver.OracleDriver

#user_name=EXTRADEV
#password=wFeJdt6c
#url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
#driver=oracle.jdbc.driver.OracleDriver


##XTRAINT
##wFeJdt6c
##jdbc:oracle:thin:@retprdb2.extrastores.com:1521/RMSPRD.extrastores.com

##OMSDEV
##wFeJdt6c
##jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com

##OMSDEV
##Logic123
##jdbc:oracle:thin:@exvm-qarmsdb02.extrastores.com:1521/RMSQA.extrastores.com