oms.datasource.url = jdbc:oracle:thin:@192.168.50.111:1521/rmsprd.extrastores.com
oms.datasource.username = OMSDEV
oms.datasource.password = Z0b0JYUB


sim.datasource.url = jdbc:oracle:thin:@//retprd-scan.extrastores.com:1521/SIMPRD.extrastores.com
sim.datasource.username = sim14
sim.datasource.password = kcv123retlv


notification.email.from.address = no-reply@extra.com
notification.email.from.name = eXtra
notification.sms.sender.name = eXtra
notification.gateway.email.url = https://prod-communication-v1.uk-e1.cloudhub.io/communication/email
notification.gateway.sms.url = https://prod-communication-sms-v2.uk-e1.cloudhub.io/communication/sms/sms
notification.gateway.request.id = 644e1dd7-2a7f-18fb-b8ed-ed78c3f92c2b
notification.gateway.auth.token = MDc5NmMyOTc0M2Q1NDZhNGFlODcwYTRkMWQ3YTc3OTk6OEQ4OWM0Q0I0QzU5NDk4MTk5RjhkYjIwOUY3MWExM2Y=
notification.gateway.app.id = E-COMMERCE
notification.replacement.text=you can track your shipment from .~ويمكنك تتبع الشحنة من هنا