
package com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FulfillmentOrderDeliveryService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", wsdlLocation = "http://exvm-qaadfapp01.extrastores.com:7511/FulfillmentOrderDeliveryBean/FulfillmentOrderDeliveryService?WSDL")
public class FulfillmentOrderDeliveryService
    extends Service
{

    private final static URL FULFILLMENTORDERDELIVERYSERVICE_WSDL_LOCATION;
    private final static WebServiceException FULFILLMENTORDERDELIVERYSERVICE_EXCEPTION;
    private final static QName FULFILLMENTORDERDELIVERYSERVICE_QNAME = new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", "FulfillmentOrderDeliveryService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exvm-qaadfapp01.extrastores.com:7511/FulfillmentOrderDeliveryBean/FulfillmentOrderDeliveryService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FULFILLMENTORDERDELIVERYSERVICE_WSDL_LOCATION = url;
        FULFILLMENTORDERDELIVERYSERVICE_EXCEPTION = e;
    }

    public FulfillmentOrderDeliveryService() {
        super(__getWsdlLocation(), FULFILLMENTORDERDELIVERYSERVICE_QNAME);
    }

    public FulfillmentOrderDeliveryService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FULFILLMENTORDERDELIVERYSERVICE_QNAME, features);
    }

    public FulfillmentOrderDeliveryService(URL wsdlLocation) {
        super(wsdlLocation, FULFILLMENTORDERDELIVERYSERVICE_QNAME);
    }

    public FulfillmentOrderDeliveryService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FULFILLMENTORDERDELIVERYSERVICE_QNAME, features);
    }

    public FulfillmentOrderDeliveryService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FulfillmentOrderDeliveryService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FulfillmentOrderDeliveryPortType
     */
    @WebEndpoint(name = "FulfillmentOrderDeliveryPort")
    public FulfillmentOrderDeliveryPortType getFulfillmentOrderDeliveryPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", "FulfillmentOrderDeliveryPort"), FulfillmentOrderDeliveryPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FulfillmentOrderDeliveryPortType
     */
    @WebEndpoint(name = "FulfillmentOrderDeliveryPort")
    public FulfillmentOrderDeliveryPortType getFulfillmentOrderDeliveryPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", "FulfillmentOrderDeliveryPort"), FulfillmentOrderDeliveryPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FULFILLMENTORDERDELIVERYSERVICE_EXCEPTION!= null) {
            throw FULFILLMENTORDERDELIVERYSERVICE_EXCEPTION;
        }
        return FULFILLMENTORDERDELIVERYSERVICE_WSDL_LOCATION;
    }

}
