<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://com.logicinfo.oms/model/" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://com.logicinfo.oms/model/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/" >
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="OMSCOCancellationV1.xsd" namespace="http://com.logicinfo.oms/model/"/>
    </xsd:schema>
  </types>
  <message name="coCancellationRequest">
    <part name="input" element="tns:cancelOrder"/>
  </message>
  <message name="coCancellationResponse">
    <part name="return" element="tns:cancelOrderResponse"/>
  </message>
 
  <portType name="OMSCOCancellationWebService">
    <operation name="processCancellationOrder">
      <input message="tns:coCancellationRequest"/>
      <output message="tns:coCancellationResponse"/>
    </operation>
  </portType>
  <binding name="OMSCOCancellationWebServicePortSOAP12Binding" type="tns:OMSCOCancellationWebService">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="processCancellationOrder">
      <soap12:operation style="document"  soapAction=""/>
      <input>
        <soap12:body use="literal"/>
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="OMSCOCancellationWebService">
    <port name="OMSCOCancellationWebService" binding="tns:OMSCOCancellationWebServicePortSOAP12Binding">
      <soap12:address location="http://www.example.com"/>
    </port>
  </service>
</definitions>
