
package com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1;


import com.logicinfo.oms.beans.OMSUtilCommons;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "StoreFulfillmentOrderService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", wsdlLocation = "http://licrpap14-extra.logicindia.com:17019/StoreFulfillmentOrderBean/StoreFulfillmentOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FStoreFulfillmentOrderService%2Fv1%7DStoreFulfillmentOrderService")
public class StoreFulfillmentOrderService
    extends Service
{

    private final static URL STOREFULFILLMENTORDERSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.StoreFulfillmentOrderService.class.getName());

    static
    {
        URL url = null;
        try 
        {
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("SIM_STORE_FULFILL_ORDER");
           
            URL baseUrl;
            baseUrl = com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.StoreFulfillmentOrderService.class.getResource(".");
            // url = new URL(baseUrl, "http://licrpap14-extra.logicindia.com:17019/StoreFulfillmentOrderBean/StoreFulfillmentOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FStoreFulfillmentOrderService%2Fv1%7DStoreFulfillmentOrderService");
            url = new URL(baseUrl,wsdlUrl);
        } 
        catch (MalformedURLException e)
        {
            //logger.warning("Failed to create URL for the wsdl Location: 'http://licrpap14-extra.logicindia.com:17019/StoreFulfillmentOrderBean/StoreFulfillmentOrderService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FStoreFulfillmentOrderService%2Fv1%7DStoreFulfillmentOrderService', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        STOREFULFILLMENTORDERSERVICE_WSDL_LOCATION = url;
    }

    public StoreFulfillmentOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreFulfillmentOrderService() {
        super(STOREFULFILLMENTORDERSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", "StoreFulfillmentOrderService"));
    }

    /**
     * 
     * @return
     *     returns StoreFulfillmentOrderPortType
     */
    @WebEndpoint(name = "StoreFulfillmentOrderPort")
    public StoreFulfillmentOrderPortType getStoreFulfillmentOrderPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", "StoreFulfillmentOrderPort"), StoreFulfillmentOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StoreFulfillmentOrderPortType
     */
    @WebEndpoint(name = "StoreFulfillmentOrderPort")
    public StoreFulfillmentOrderPortType getStoreFulfillmentOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", "StoreFulfillmentOrderPort"), StoreFulfillmentOrderPortType.class, features);
    }

}
