log4j.rootLogger=INFO, CA, FA 

#Console Appender
log4j.appender.CA=org.apache.log4j.ConsoleAppender
log4j.appender.CA.layout=org.apache.log4j.PatternLayout
log4j.appender.CA.layout.ConversionPattern==%d{yyyy-MM-dd HH:mm:ss} %-4r [%t] %-5p %c %x - %m%n

#File Appender
log4j.appender.FA=org.apache.log4j.FileAppender
log4j.appender.FA.File=D:/Pradeep/Logic/Projects/eXtra/WebServices/OMSHomeDeliveryStatusUpdate/logs/OMSHomeDeliveryStatusUpdate.log
#log4j.appender.FA.File=./logs/OMSCustomerOrder.log
#log4j.appender.FA.File=/u01/app/orrib/product/10.3.6/user_projects/domains/RSB_DOMAIN/servers/oms_server/logs/OMSHomeDeliveryStatusUpdate.log
#log4j.appender.FA.File=/u00/oracle/Weblogic_RSB/user_projects/domains/RSBDomain/servers/AdminServer/logs/OMSHomeDeliveryStatusUpdate.log
#log4j.appender.FA.File=${RSB.LOGS}/OMSHomeDeliveryStatusUpdate.log
#log4j.appender.FA.File=$(DOMAIN_HOME1)/OMSHomeDeliveryStatusUpdate.log
#log4j.appender.FA.File=$(RSBLOGS)/oms_server/logs/OMSHomeDeliveryStatusUpdate.log
#/u01/app/orrib/product/10.3.6/user_projects/domains/RSB_DOMAIN/servers/oms_server/logs
log4j.appender.FA.layout=org.apache.log4j.PatternLayout
log4j.appender.FA.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-4r [%t] [%-5p] %c - %m%n
#log4j.appender.FA.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n
#log4j.appender.FA.layout.ConversionPattern=%d [%t] %-5p %c - %m%n

# Set the logger level of File Appender to WARN
log4j.appender.FA.Threshold = WARN
log4j.appender.CA.Threshold = INFO