<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.extra</groupId>
	<artifactId>oms-customerorder-service</artifactId>
	<packaging>war</packaging>
	<version>0.0.1</version>
	<name>CustomerOrderService</name>
	<url>http://maven.apache.org</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java-version>1.7</java-version>
		<org.slf4j-version>1.7.5</org.slf4j-version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.oracle</groupId>
			<artifactId>ojdbc7</artifactId>
			<version>12.1.0.2</version>
		</dependency>

		<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.17</version>
		</dependency>

		<!-- Servlet+JSP+JSTL -->
		<dependency>
			<groupId>javax.servlet</groupId>
			<artifactId>javax.servlet-api</artifactId>
			<version>3.1.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.extra</groupId>
			<artifactId>oms-util</artifactId>
			<version>0.0.1</version>
		</dependency>
		<dependency>
			<groupId>com.extra</groupId>
			<artifactId>oracle</artifactId>
			<version>0.0.1</version>
		</dependency>
	</dependencies>
	<build>
		<finalName>CustomerOrderService</finalName>
		<sourceDirectory>${project.basedir}/src</sourceDirectory>
		<testSourceDirectory></testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>2.20.1</version>
				<configuration>
					<skipTests>true</skipTests>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>2.3.2</version>
				<configuration>
					<source>1.7</source>
					<target>1.7</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<repositories>
		<repository>
			<id>hand-china-repo</id>
			<name>HandChinaRepo</name>
			<url>http://nexus.saas.hand-china.com/content/repositories/rdc/</url>
		</repository>
	</repositories>
</project>