
package com.oracle.retail.rms.integration.services.fulfillorderservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FulfillOrderService", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", wsdlLocation = "http://192.168.41.194:7117/FulfillOrderBean/FulfillOrderService?wsdl")
public class FulfillOrderService
    extends Service
{

    private final static URL FULFILLORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException FULFILLORDERSERVICE_EXCEPTION;
    private final static QName FULFILLORDERSERVICE_QNAME = new QName("http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", "FulfillOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.41.194:7117/FulfillOrderBean/FulfillOrderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FULFILLORDERSERVICE_WSDL_LOCATION = url;
        FULFILLORDERSERVICE_EXCEPTION = e;
    }

    public FulfillOrderService() {
        super(__getWsdlLocation(), FULFILLORDERSERVICE_QNAME);
    }

    public FulfillOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FULFILLORDERSERVICE_QNAME, features);
    }

    public FulfillOrderService(URL wsdlLocation) {
        super(wsdlLocation, FULFILLORDERSERVICE_QNAME);
    }

    public FulfillOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FULFILLORDERSERVICE_QNAME, features);
    }

    public FulfillOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FulfillOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FulfillOrderPortType
     */
    @WebEndpoint(name = "FulfillOrderPort")
    public FulfillOrderPortType getFulfillOrderPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", "FulfillOrderPort"), FulfillOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FulfillOrderPortType
     */
    @WebEndpoint(name = "FulfillOrderPort")
    public FulfillOrderPortType getFulfillOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1", "FulfillOrderPort"), FulfillOrderPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FULFILLORDERSERVICE_EXCEPTION!= null) {
            throw FULFILLORDERSERVICE_EXCEPTION;
        }
        return FULFILLORDERSERVICE_WSDL_LOCATION;
    }

}
