
package com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FulfillmentOrderReversePickService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", wsdlLocation = "http://exvm-qaadfapp01.extrastores.com:7511/FulfillmentOrderReversePickBean/FulfillmentOrderReversePickService?WSDL")
public class FulfillmentOrderReversePickService
    extends Service
{

    private final static URL FULFILLMENTORDERREVERSEPICKSERVICE_WSDL_LOCATION;
    private final static WebServiceException FULFILLMENTORDERREVERSEPICKSERVICE_EXCEPTION;
    private final static QName FULFILLMENTORDERREVERSEPICKSERVICE_QNAME = new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", "FulfillmentOrderReversePickService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exvm-qaadfapp01.extrastores.com:7511/FulfillmentOrderReversePickBean/FulfillmentOrderReversePickService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FULFILLMENTORDERREVERSEPICKSERVICE_WSDL_LOCATION = url;
        FULFILLMENTORDERREVERSEPICKSERVICE_EXCEPTION = e;
    }

    public FulfillmentOrderReversePickService() {
        super(__getWsdlLocation(), FULFILLMENTORDERREVERSEPICKSERVICE_QNAME);
    }

    public FulfillmentOrderReversePickService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FULFILLMENTORDERREVERSEPICKSERVICE_QNAME, features);
    }

    public FulfillmentOrderReversePickService(URL wsdlLocation) {
        super(wsdlLocation, FULFILLMENTORDERREVERSEPICKSERVICE_QNAME);
    }

    public FulfillmentOrderReversePickService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FULFILLMENTORDERREVERSEPICKSERVICE_QNAME, features);
    }

    public FulfillmentOrderReversePickService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FulfillmentOrderReversePickService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FulfillmentOrderReversePickPortType
     */
    @WebEndpoint(name = "FulfillmentOrderReversePickPort")
    public FulfillmentOrderReversePickPortType getFulfillmentOrderReversePickPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", "FulfillmentOrderReversePickPort"), FulfillmentOrderReversePickPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FulfillmentOrderReversePickPortType
     */
    @WebEndpoint(name = "FulfillmentOrderReversePickPort")
    public FulfillmentOrderReversePickPortType getFulfillmentOrderReversePickPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", "FulfillmentOrderReversePickPort"), FulfillmentOrderReversePickPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FULFILLMENTORDERREVERSEPICKSERVICE_EXCEPTION!= null) {
            throw FULFILLMENTORDERREVERSEPICKSERVICE_EXCEPTION;
        }
        return FULFILLMENTORDERREVERSEPICKSERVICE_WSDL_LOCATION;
    }

}
