
package com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.forpcremodvo.v1.ForpCreModVo;
import com.oracle.retail.integration.base.bo.forpdesc.v1.ForpDesc;
import com.oracle.retail.integration.base.bo.forphdrcoldesc.v1.ForpHdrColDesc;
import com.oracle.retail.integration.base.bo.forpmodvo.v1.ForpModVo;
import com.oracle.retail.integration.base.bo.forpref.v1.ForpRef;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;
import com.oracle.retail.integration.base.bo.strfordref.v1.StrFordRef;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FulfillmentOrderReversePickPortType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.forpcremodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.forpdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.forphdrcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.forphdrdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.forpmodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.forpref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strfordref.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.ObjectFactory.class
})
public interface FulfillmentOrderReversePickPortType {


    /**
     * 
     * @param forpModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "updateFulfillmentOrderReversePick", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.UpdateFulfillmentOrderReversePick")
    @ResponseWrapper(localName = "updateFulfillmentOrderReversePickResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.UpdateFulfillmentOrderReversePickResponse")
    public InvocationSuccess updateFulfillmentOrderReversePick(
        @WebParam(name = "ForpModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpModVo/v1")
        ForpModVo forpModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strFordRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.forphdrcoldesc.v1.ForpHdrColDesc
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "ForpHdrColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpHdrColDesc/v1")
    @RequestWrapper(localName = "lookupReversePickHeaders", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.LookupReversePickHeaders")
    @ResponseWrapper(localName = "lookupReversePickHeadersResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.LookupReversePickHeadersResponse")
    public ForpHdrColDesc lookupReversePickHeaders(
        @WebParam(name = "StrFordRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrFordRef/v1")
        StrFordRef strFordRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param forpRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.forpdesc.v1.ForpDesc
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "ForpDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpDesc/v1")
    @RequestWrapper(localName = "readReversePickDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.ReadReversePickDetail")
    @ResponseWrapper(localName = "readReversePickDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.ReadReversePickDetailResponse")
    public ForpDesc readReversePickDetail(
        @WebParam(name = "ForpRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpRef/v1")
        ForpRef forpRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param forpCreModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.forpref.v1.ForpRef
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "ForpRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpRef/v1")
    @RequestWrapper(localName = "createReversePick", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.CreateReversePick")
    @ResponseWrapper(localName = "createReversePickResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.CreateReversePickResponse")
    public ForpRef createReversePick(
        @WebParam(name = "ForpCreModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpCreModVo/v1")
        ForpCreModVo forpCreModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param forpRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "deleteReversePick", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.DeleteReversePick")
    @ResponseWrapper(localName = "deleteReversePickResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.DeleteReversePickResponse")
    public InvocationSuccess deleteReversePick(
        @WebParam(name = "ForpRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpRef/v1")
        ForpRef forpRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param forpRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "confirmReversePick", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.ConfirmReversePick")
    @ResponseWrapper(localName = "confirmReversePickResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.ConfirmReversePickResponse")
    public InvocationSuccess confirmReversePick(
        @WebParam(name = "ForpRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/ForpRef/v1")
        ForpRef forpRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
