<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1" name="FulfillOrderService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1" schemaLocation="FulfillOrderService1.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/services/exception/v1" schemaLocation="FulfillOrderService9.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/localization/bo/BrFulfilOrdCustDesc/v1" schemaLocation="FulfillOrderService10.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/custom/bo/EOfBrFulfilOrdCustDesc/v1" schemaLocation="FulfillOrderService11.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/LocOfFulfilOrdCustDesc/v1" schemaLocation="FulfillOrderService12.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1" schemaLocation="FulfillOrderService13.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdRef/v1" schemaLocation="FulfillOrderService14.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdDtlRef/v1" schemaLocation="FulfillOrderService15.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdDtl/v1" schemaLocation="FulfillOrderService16.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdDesc/v1" schemaLocation="FulfillOrderService2.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdCustDesc/v1" schemaLocation="FulfillOrderService3.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdColRef/v1" schemaLocation="FulfillOrderService4.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdColDesc/v1" schemaLocation="FulfillOrderService5.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdCfmDtl/v1" schemaLocation="FulfillOrderService6.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdCfmDesc/v1" schemaLocation="FulfillOrderService7.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/FulfilOrdCfmCol/v1" schemaLocation="FulfillOrderService8.xsd"/>
    </xsd:schema>
  </types>
  <message name="createFulfilOrdColDesc">
    <part name="parameters" element="tns:createFulfilOrdColDesc"/>
  </message>
  <message name="createFulfilOrdColDescResponse">
    <part name="parameters" element="tns:createFulfilOrdColDescResponse"/>
  </message>
  <message name="IllegalArgumentWSFaultException">
    <part xmlns:ns1="http://www.oracle.com/retail/integration/services/exception/v1" name="fault" element="ns1:IllegalArgumentWSFaultException"/>
  </message>
  <message name="EntityAlreadyExistsWSFaultException">
    <part xmlns:ns2="http://www.oracle.com/retail/integration/services/exception/v1" name="fault" element="ns2:EntityAlreadyExistsWSFaultException"/>
  </message>
  <message name="IllegalStateWSFaultException">
    <part xmlns:ns3="http://www.oracle.com/retail/integration/services/exception/v1" name="fault" element="ns3:IllegalStateWSFaultException"/>
  </message>
  <message name="ValidationWSFaultException">
    <part xmlns:ns4="http://www.oracle.com/retail/integration/services/exception/v1" name="fault" element="ns4:ValidationWSFaultException"/>
  </message>
  <message name="cancelFulfilOrdColRef">
    <part name="parameters" element="tns:cancelFulfilOrdColRef"/>
  </message>
  <message name="cancelFulfilOrdColRefResponse">
    <part name="parameters" element="tns:cancelFulfilOrdColRefResponse"/>
  </message>
  <message name="ping">
    <part name="parameters" element="tns:ping"/>
  </message>
  <message name="pingResponse">
    <part name="parameters" element="tns:pingResponse"/>
  </message>
  <portType name="FulfillOrderPortType">
    <operation name="createFulfilOrdColDesc">
      <input wsaw:Action="http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1/FulfillOrderPortType/createFulfilOrdColDescRequest" message="tns:createFulfilOrdColDesc"/>
      <output message="tns:createFulfilOrdColDescResponse"/>
      <fault message="tns:IllegalArgumentWSFaultException" name="IllegalArgumentWSFaultException"/>
      <fault message="tns:EntityAlreadyExistsWSFaultException" name="EntityAlreadyExistsWSFaultException"/>
      <fault message="tns:IllegalStateWSFaultException" name="IllegalStateWSFaultException"/>
      <fault message="tns:ValidationWSFaultException" name="ValidationWSFaultException"/>
    </operation>
    <operation name="cancelFulfilOrdColRef">
      <input wsaw:Action="http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1/FulfillOrderPortType/cancelFulfilOrdColRefRequest" message="tns:cancelFulfilOrdColRef"/>
      <output message="tns:cancelFulfilOrdColRefResponse"/>
      <fault message="tns:IllegalArgumentWSFaultException" name="IllegalArgumentWSFaultException"/>
      <fault message="tns:EntityAlreadyExistsWSFaultException" name="EntityAlreadyExistsWSFaultException"/>
      <fault message="tns:IllegalStateWSFaultException" name="IllegalStateWSFaultException"/>
      <fault message="tns:ValidationWSFaultException" name="ValidationWSFaultException"/>
    </operation>
    <operation name="ping">
      <input wsaw:Action="http://www.oracle.com/retail/rms/integration/services/FulfillOrderService/v1/FulfillOrderPortType/pingRequest" message="tns:ping"/>
      <output message="tns:pingResponse"/>
    </operation>
  </portType>
  <binding name="FulfillOrderPortBinding" type="tns:FulfillOrderPortType">
    <wsaw:UsingAddressing/>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="createFulfilOrdColDesc">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="IllegalArgumentWSFaultException">
        <soap:fault name="IllegalArgumentWSFaultException" use="literal"/>
      </fault>
      <fault name="EntityAlreadyExistsWSFaultException">
        <soap:fault name="EntityAlreadyExistsWSFaultException" use="literal"/>
      </fault>
      <fault name="IllegalStateWSFaultException">
        <soap:fault name="IllegalStateWSFaultException" use="literal"/>
      </fault>
      <fault name="ValidationWSFaultException">
        <soap:fault name="ValidationWSFaultException" use="literal"/>
      </fault>
    </operation>
    <operation name="cancelFulfilOrdColRef">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="IllegalArgumentWSFaultException">
        <soap:fault name="IllegalArgumentWSFaultException" use="literal"/>
      </fault>
      <fault name="EntityAlreadyExistsWSFaultException">
        <soap:fault name="EntityAlreadyExistsWSFaultException" use="literal"/>
      </fault>
      <fault name="IllegalStateWSFaultException">
        <soap:fault name="IllegalStateWSFaultException" use="literal"/>
      </fault>
      <fault name="ValidationWSFaultException">
        <soap:fault name="ValidationWSFaultException" use="literal"/>
      </fault>
    </operation>
    <operation name="ping">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="FulfillOrderService">
    <port name="FulfillOrderPort" binding="tns:FulfillOrderPortBinding">
      <soap:address location="http://licrpap14-extra.logicindia.com:17040/FulfillOrderBean/FulfillOrderService"/>
    </port>
  </service>
</definitions>