
package com.oracle.retail.sim.integration.services.storetostoretransferservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.bolmtvcoldesc.v1.BolMtvColDesc;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;
import com.oracle.retail.integration.base.bo.nothing.v1.Nothing;
import com.oracle.retail.integration.base.bo.ststsfapvmodvo.v1.StsTsfApvModVo;
import com.oracle.retail.integration.base.bo.ststsfdesc.v1.StsTsfDesc;
import com.oracle.retail.integration.base.bo.ststsfhdrcoldesc.v1.StsTsfHdrColDesc;
import com.oracle.retail.integration.base.bo.ststsfhdrcrivo.v1.StsTsfHdrCriVo;
import com.oracle.retail.integration.base.bo.ststsfrcvmodvo.v1.StsTsfRcvModVo;
import com.oracle.retail.integration.base.bo.ststsfref.v1.StsTsfRef;
import com.oracle.retail.integration.base.bo.ststsfreqmodvo.v1.StsTsfReqModVo;
import com.oracle.retail.integration.base.bo.ststsfshpmodvo.v1.StsTsfShpModVo;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "StoreToStoreTransferPortType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.bolmtvcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.bolmtvdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.nothing.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfapvmodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfhdrcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfhdrcrivo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfhdrdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfrcvmodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfreqmodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.ststsfshpmodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.ObjectFactory.class
})
public interface StoreToStoreTransferPortType {


    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "approveTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.ApproveTransfer")
    @ResponseWrapper(localName = "approveTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.ApproveTransferResponse")
    public InvocationSuccess approveTransfer(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "cancelTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.CancelTransfer")
    @ResponseWrapper(localName = "cancelTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.CancelTransferResponse")
    public InvocationSuccess cancelTransfer(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "dispatchTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.DispatchTransfer")
    @ResponseWrapper(localName = "dispatchTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.DispatchTransferResponse")
    public InvocationSuccess dispatchTransfer(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "receiveTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.ReceiveTransfer")
    @ResponseWrapper(localName = "receiveTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.ReceiveTransferResponse")
    public InvocationSuccess receiveTransfer(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "rejectTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.RejectTransfer")
    @ResponseWrapper(localName = "rejectTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.RejectTransferResponse")
    public InvocationSuccess rejectTransfer(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "requestTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.RequestTransfer")
    @ResponseWrapper(localName = "requestTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.RequestTransferResponse")
    public InvocationSuccess requestTransfer(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "submitTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SubmitTransfer")
    @ResponseWrapper(localName = "submitTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SubmitTransferResponse")
    public InvocationSuccess submitTransfer(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param nothing
     * @return
     *     returns com.oracle.retail.integration.base.bo.bolmtvcoldesc.v1.BolMtvColDesc
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "BolMtvColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/BolMtvColDesc/v1")
    @RequestWrapper(localName = "lookupBillOfLadingMotives", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.LookupBillOfLadingMotives")
    @ResponseWrapper(localName = "lookupBillOfLadingMotivesResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.LookupBillOfLadingMotivesResponse")
    public BolMtvColDesc lookupBillOfLadingMotives(
        @WebParam(name = "Nothing", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/Nothing/v1")
        Nothing nothing)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.ststsfdesc.v1.StsTsfDesc
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StsTsfDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfDesc/v1")
    @RequestWrapper(localName = "readTransferDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.ReadTransferDetail")
    @ResponseWrapper(localName = "readTransferDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.ReadTransferDetailResponse")
    public StsTsfDesc readTransferDetail(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfHdrCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.ststsfhdrcoldesc.v1.StsTsfHdrColDesc
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StsTsfHdrColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfHdrColDesc/v1")
    @RequestWrapper(localName = "lookupTransferHeader", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.LookupTransferHeader")
    @ResponseWrapper(localName = "lookupTransferHeaderResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.LookupTransferHeaderResponse")
    public StsTsfHdrColDesc lookupTransferHeader(
        @WebParam(name = "StsTsfHdrCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfHdrCriVo/v1")
        StsTsfHdrCriVo stsTsfHdrCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "cancelTransferSubmission", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.CancelTransferSubmission")
    @ResponseWrapper(localName = "cancelTransferSubmissionResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.CancelTransferSubmissionResponse")
    public InvocationSuccess cancelTransferSubmission(
        @WebParam(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
        StsTsfRef stsTsfRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfReqModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.ststsfref.v1.StsTsfRef
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
    @RequestWrapper(localName = "saveTransferRequest", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SaveTransferRequest")
    @ResponseWrapper(localName = "saveTransferRequestResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SaveTransferRequestResponse")
    public StsTsfRef saveTransferRequest(
        @WebParam(name = "StsTsfReqModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfReqModVo/v1")
        StsTsfReqModVo stsTsfReqModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfApvModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "savePendingTransferRequest", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SavePendingTransferRequest")
    @ResponseWrapper(localName = "savePendingTransferRequestResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SavePendingTransferRequestResponse")
    public InvocationSuccess savePendingTransferRequest(
        @WebParam(name = "StsTsfApvModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfApvModVo/v1")
        StsTsfApvModVo stsTsfApvModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfShpModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.ststsfref.v1.StsTsfRef
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StsTsfRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRef/v1")
    @RequestWrapper(localName = "saveInProgressTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SaveInProgressTransfer")
    @ResponseWrapper(localName = "saveInProgressTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SaveInProgressTransferResponse")
    public StsTsfRef saveInProgressTransfer(
        @WebParam(name = "StsTsfShpModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfShpModVo/v1")
        StsTsfShpModVo stsTsfShpModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param stsTsfRcvModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "saveInReceivingTransfer", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SaveInReceivingTransfer")
    @ResponseWrapper(localName = "saveInReceivingTransferResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.SaveInReceivingTransferResponse")
    public InvocationSuccess saveInReceivingTransfer(
        @WebParam(name = "StsTsfRcvModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StsTsfRcvModVo/v1")
        StsTsfRcvModVo stsTsfRcvModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreToStoreTransferService/v1", className = "com.oracle.retail.sim.integration.services.storetostoretransferservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
