
package com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;
import com.oracle.retail.integration.base.bo.nothing.v1.Nothing;
import com.oracle.retail.integration.base.bo.nslqtytypcoldesc.v1.NslQtyTypColDesc;
import com.oracle.retail.integration.base.bo.stradjdesc.v1.StrAdjDesc;
import com.oracle.retail.integration.base.bo.stradjhdrcoldesc.v1.StrAdjHdrColDesc;
import com.oracle.retail.integration.base.bo.stradjhdrcrivo.v1.StrAdjHdrCriVo;
import com.oracle.retail.integration.base.bo.stradjmodvo.v1.StrAdjModVo;
import com.oracle.retail.integration.base.bo.stradjref.v1.StrAdjRef;
import com.oracle.retail.integration.base.bo.stradjrsncoldesc.v1.StrAdjRsnColDesc;
import com.oracle.retail.integration.base.bo.stradjtphdcoldesc.v1.StrAdjTpHdColDesc;
import com.oracle.retail.integration.base.bo.stradjtphdcrivo.v1.StrAdjTpHdCriVo;
import com.oracle.retail.integration.base.bo.stradjtpldesc.v1.StrAdjTplDesc;
import com.oracle.retail.integration.base.bo.stradjtplref.v1.StrAdjTplRef;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "InventoryAdjustmentPortType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.nothing.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.nslqtytypcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.nslqtytypdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjhdrcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjhdrcrivo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjhdrdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjmodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjrsncoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjrsndesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjtphdcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjtphdcrivo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjtphddesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjtpldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.stradjtplref.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.ObjectFactory.class
})
public interface InventoryAdjustmentPortType {


    /**
     * 
     * @param strAdjRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "confirmInventoryAdjustment", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.ConfirmInventoryAdjustment")
    @ResponseWrapper(localName = "confirmInventoryAdjustmentResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.ConfirmInventoryAdjustmentResponse")
    public InvocationSuccess confirmInventoryAdjustment(
        @WebParam(name = "StrAdjRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjRef/v1")
        StrAdjRef strAdjRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strAdjRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "cancelInventoryAdjustment", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.CancelInventoryAdjustment")
    @ResponseWrapper(localName = "cancelInventoryAdjustmentResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.CancelInventoryAdjustmentResponse")
    public InvocationSuccess cancelInventoryAdjustment(
        @WebParam(name = "StrAdjRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjRef/v1")
        StrAdjRef strAdjRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strAdjModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.stradjref.v1.StrAdjRef
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrAdjRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjRef/v1")
    @RequestWrapper(localName = "saveAndConfirmInventoryAdjustment", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.SaveAndConfirmInventoryAdjustment")
    @ResponseWrapper(localName = "saveAndConfirmInventoryAdjustmentResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.SaveAndConfirmInventoryAdjustmentResponse")
    public StrAdjRef saveAndConfirmInventoryAdjustment(
        @WebParam(name = "StrAdjModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjModVo/v1")
        StrAdjModVo strAdjModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param nothing
     * @return
     *     returns com.oracle.retail.integration.base.bo.stradjrsncoldesc.v1.StrAdjRsnColDesc
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrAdjRsnColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjRsnColDesc/v1")
    @RequestWrapper(localName = "lookupInventoryAdjustmentReason", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupInventoryAdjustmentReason")
    @ResponseWrapper(localName = "lookupInventoryAdjustmentReasonResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupInventoryAdjustmentReasonResponse")
    public StrAdjRsnColDesc lookupInventoryAdjustmentReason(
        @WebParam(name = "Nothing", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/Nothing/v1")
        Nothing nothing)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param nothing
     * @return
     *     returns com.oracle.retail.integration.base.bo.nslqtytypcoldesc.v1.NslQtyTypColDesc
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "NslQtyTypColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/NslQtyTypColDesc/v1")
    @RequestWrapper(localName = "lookupNonSellableQuantityType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupNonSellableQuantityType")
    @ResponseWrapper(localName = "lookupNonSellableQuantityTypeResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupNonSellableQuantityTypeResponse")
    public NslQtyTypColDesc lookupNonSellableQuantityType(
        @WebParam(name = "Nothing", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/Nothing/v1")
        Nothing nothing)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strAdjTpHdCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.stradjtphdcoldesc.v1.StrAdjTpHdColDesc
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrAdjTpHdColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjTpHdColDesc/v1")
    @RequestWrapper(localName = "lookupInventoryAdjustmentTemplateHeader", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupInventoryAdjustmentTemplateHeader")
    @ResponseWrapper(localName = "lookupInventoryAdjustmentTemplateHeaderResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupInventoryAdjustmentTemplateHeaderResponse")
    public StrAdjTpHdColDesc lookupInventoryAdjustmentTemplateHeader(
        @WebParam(name = "StrAdjTpHdCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjTpHdCriVo/v1")
        StrAdjTpHdCriVo strAdjTpHdCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strAdjTplRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.stradjtpldesc.v1.StrAdjTplDesc
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrAdjTplDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjTplDesc/v1")
    @RequestWrapper(localName = "readInventoryAdjustmentTemplateDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.ReadInventoryAdjustmentTemplateDetail")
    @ResponseWrapper(localName = "readInventoryAdjustmentTemplateDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.ReadInventoryAdjustmentTemplateDetailResponse")
    public StrAdjTplDesc readInventoryAdjustmentTemplateDetail(
        @WebParam(name = "StrAdjTplRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjTplRef/v1")
        StrAdjTplRef strAdjTplRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strAdjHdrCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.stradjhdrcoldesc.v1.StrAdjHdrColDesc
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrAdjHdrColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjHdrColDesc/v1")
    @RequestWrapper(localName = "lookupInventoryAdjustmentHeader", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupInventoryAdjustmentHeader")
    @ResponseWrapper(localName = "lookupInventoryAdjustmentHeaderResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.LookupInventoryAdjustmentHeaderResponse")
    public StrAdjHdrColDesc lookupInventoryAdjustmentHeader(
        @WebParam(name = "StrAdjHdrCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjHdrCriVo/v1")
        StrAdjHdrCriVo strAdjHdrCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strAdjRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.stradjdesc.v1.StrAdjDesc
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrAdjDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjDesc/v1")
    @RequestWrapper(localName = "readInventoryAdjustmentDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.ReadInventoryAdjustmentDetail")
    @ResponseWrapper(localName = "readInventoryAdjustmentDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.ReadInventoryAdjustmentDetailResponse")
    public StrAdjDesc readInventoryAdjustmentDetail(
        @WebParam(name = "StrAdjRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjRef/v1")
        StrAdjRef strAdjRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strAdjModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.stradjref.v1.StrAdjRef
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrAdjRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjRef/v1")
    @RequestWrapper(localName = "saveInventoryAdjustment", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.SaveInventoryAdjustment")
    @ResponseWrapper(localName = "saveInventoryAdjustmentResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.SaveInventoryAdjustmentResponse")
    public StrAdjRef saveInventoryAdjustment(
        @WebParam(name = "StrAdjModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrAdjModVo/v1")
        StrAdjModVo strAdjModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", className = "com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
