
package com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1;

import com.logicinfo.oms.beans.OMSUtilCommons;
import com.logicinfo.oms.ejb.OMSUtilSessionEJB;
import com.logicinfo.oms.util.OMSUtil;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "InventoryAdjustmentService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", wsdlLocation = "http://licrpap14-extra.logicindia.com:17019/InventoryAdjustmentBean/InventoryAdjustmentService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FInventoryAdjustmentService%2Fv1%7DInventoryAdjustmentService")
public class InventoryAdjustmentService
    extends Service
{

    private final static URL INVENTORYADJUSTMENTSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.InventoryAdjustmentService.class.getName());

    static {
        URL url = null;
        try {
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("SIM_INVENTORY_ADJ");
            URL baseUrl;
            baseUrl = com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1.InventoryAdjustmentService.class.getResource(".");
            // url = new URL(baseUrl, "http://licrpap14-extra.logicindia.com:17019/InventoryAdjustmentBean/InventoryAdjustmentService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FInventoryAdjustmentService%2Fv1%7DInventoryAdjustmentService");
            url = new URL(baseUrl,wsdlUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://licrpap14-extra.logicindia.com:17019/InventoryAdjustmentBean/InventoryAdjustmentService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FInventoryAdjustmentService%2Fv1%7DInventoryAdjustmentService', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        INVENTORYADJUSTMENTSERVICE_WSDL_LOCATION = url;
    }

    public InventoryAdjustmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryAdjustmentService() {
        super(INVENTORYADJUSTMENTSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", "InventoryAdjustmentService"));
    }

    /**
     * 
     * @return
     *     returns InventoryAdjustmentPortType
     */
    @WebEndpoint(name = "InventoryAdjustmentPort")
    public InventoryAdjustmentPortType getInventoryAdjustmentPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", "InventoryAdjustmentPort"), InventoryAdjustmentPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryAdjustmentPortType
     */
    @WebEndpoint(name = "InventoryAdjustmentPort")
    public InventoryAdjustmentPortType getInventoryAdjustmentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", "InventoryAdjustmentPort"), InventoryAdjustmentPortType.class, features);
    }

}
