<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:tns="http://www.oracle.com/retail/integration/base/bo/InvBackOrdDesc/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0" targetNamespace="http://www.oracle.com/retail/integration/base/bo/InvBackOrdDesc/v1">
  <xs:element name="InvBackOrdDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="item" type="xs:string"/>
        <xs:element name="loc_type" type="tns:loc_type"/>
        <xs:element name="location" type="xs:long"/>
        <xs:element name="channel_id" type="xs:int" minOccurs="0"/>
        <xs:element name="backorder_qty" type="xs:decimal"/>
        <xs:element name="unit_of_measure" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="loc_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="S"/>
      <xs:enumeration value="W"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>