ssh.host = sftp2.procco.net
ssh.port = 28822
ssh.username = extraegypt.uat
ssh.password = 7NdyKFDu1Qhc
ssh.remote-path = /ExtraEgypt-UATContracts

db.url = jdbc:oracle:thin:@exvm-qarmsdb01.extrastores.com:1521/RMSQA.extrastores.com
db.username = OMSDEV
db.password = Logic123