package com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.4.0.6436

public class PendingReturnsPortClient
{
  public static void main(String [] args)
  {
    PendingReturnsService pendingReturnsService = new PendingReturnsService();
    PendingReturnsPortType pendingReturnsPortType = pendingReturnsService.getPendingReturnsPort();
    // Add your code to call the desired methods.
  }
}
