
package com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1;

import com.logicinfo.oms.beans.OMSUtilCommons;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "PendingReturnsService", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", wsdlLocation = "http://licrpap14-extra.logicindia.com:17053/PendingReturnsBean/PendingReturnsService?wsdl#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frwms%2Fintegration%2Fservices%2FPendingReturnsService%2Fv1%7DPendingReturnsService")
public class PendingReturnsService
    extends Service
{

    private final static URL PENDINGRETURNSSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendingReturnsService.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("RWMS_PENDING_RETURNS");
            baseUrl = com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendingReturnsService.class.getResource(".");
         //   url = new URL(baseUrl, "http://licrpap14-extra.logicindia.com:17053/PendingReturnsBean/PendingReturnsService?wsdl#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frwms%2Fintegration%2Fservices%2FPendingReturnsService%2Fv1%7DPendingReturnsService");
         url = new URL(baseUrl,wsdlUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://licrpap14-extra.logicindia.com:17053/PendingReturnsBean/PendingReturnsService?wsdl#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Frwms%2Fintegration%2Fservices%2FPendingReturnsService%2Fv1%7DPendingReturnsService', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        PENDINGRETURNSSERVICE_WSDL_LOCATION = url;
    }

    public PendingReturnsService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PendingReturnsService() {
        super(PENDINGRETURNSSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", "PendingReturnsService"));
    }

    /**
     * 
     * @return
     *     returns PendingReturnsPortType
     */
    @WebEndpoint(name = "PendingReturnsPort")
    public PendingReturnsPortType getPendingReturnsPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", "PendingReturnsPort"), PendingReturnsPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PendingReturnsPortType
     */
    @WebEndpoint(name = "PendingReturnsPort")
    public PendingReturnsPortType getPendingReturnsPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", "PendingReturnsPort"), PendingReturnsPortType.class, features);
    }

}
