
package com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;
import com.oracle.retail.integration.base.bo.pendrtrndesc.v1.PendRtrnDesc;
import com.oracle.retail.integration.base.bo.pendrtrnref.v1.PendRtrnRef;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "PendingReturnsPortType", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.pendrtrndesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.pendrtrnref.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.ObjectFactory.class
})
public interface PendingReturnsPortType {


    /**
     * 
     * @param pendRtrnDesc
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "pendReturnDtlModify", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendReturnDtlModify")
    @ResponseWrapper(localName = "pendReturnDtlModifyResponse", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendReturnDtlModifyResponse")
    public InvocationSuccess pendReturnDtlModify(
        @WebParam(name = "PendRtrnDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/PendRtrnDesc/v1")
        PendRtrnDesc pendRtrnDesc)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param pendRtrnRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "pendReturnDtlDelete", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendReturnDtlDelete")
    @ResponseWrapper(localName = "pendReturnDtlDeleteResponse", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendReturnDtlDeleteResponse")
    public InvocationSuccess pendReturnDtlDelete(
        @WebParam(name = "PendRtrnRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/PendRtrnRef/v1")
        PendRtrnRef pendRtrnRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param pendRtrnDesc
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "pendReturnDtlCreate", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendReturnDtlCreate")
    @ResponseWrapper(localName = "pendReturnDtlCreateResponse", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PendReturnDtlCreateResponse")
    public InvocationSuccess pendReturnDtlCreate(
        @WebParam(name = "PendRtrnDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/PendRtrnDesc/v1")
        PendRtrnDesc pendRtrnDesc)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/rwms/integration/services/PendingReturnsService/v1", className = "com.oracle.retail.rwms.integration.services.pendingreturnsservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
