
package com.oracle.retail.rms.integration.services.inventorybackorderservice.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "EntityAlreadyExistsWSFaultException", targetNamespace = "http://www.oracle.com/retail/integration/services/exception/v1")
public class EntityAlreadyExistsWSFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.oracle.retail.integration.services.exception.v1.EntityAlreadyExistsWSFaultException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public EntityAlreadyExistsWSFaultException(String message, com.oracle.retail.integration.services.exception.v1.EntityAlreadyExistsWSFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public EntityAlreadyExistsWSFaultException(String message, com.oracle.retail.integration.services.exception.v1.EntityAlreadyExistsWSFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.retail.integration.services.exception.v1.EntityAlreadyExistsWSFaultException
     */
    public com.oracle.retail.integration.services.exception.v1.EntityAlreadyExistsWSFaultException getFaultInfo() {
        return faultInfo;
    }

}
