
package com.oracle.retail.rms.integration.services.inventorybackorderservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventoryBackOrderService", targetNamespace = "http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", wsdlLocation = "http://exvm-qarmsapp01.extrastores.com:7117/InventoryBackOrderBean/InventoryBackOrderService?WSDL")
public class InventoryBackOrderService
    extends Service
{

    private final static URL INVENTORYBACKORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException INVENTORYBACKORDERSERVICE_EXCEPTION;
    private final static QName INVENTORYBACKORDERSERVICE_QNAME = new QName("http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", "InventoryBackOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exvm-qarmsapp01.extrastores.com:7117/InventoryBackOrderBean/InventoryBackOrderService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTORYBACKORDERSERVICE_WSDL_LOCATION = url;
        INVENTORYBACKORDERSERVICE_EXCEPTION = e;
    }

    public InventoryBackOrderService() {
        super(__getWsdlLocation(), INVENTORYBACKORDERSERVICE_QNAME);
    }

    public InventoryBackOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORYBACKORDERSERVICE_QNAME, features);
    }

    public InventoryBackOrderService(URL wsdlLocation) {
        super(wsdlLocation, INVENTORYBACKORDERSERVICE_QNAME);
    }

    public InventoryBackOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORYBACKORDERSERVICE_QNAME, features);
    }

    public InventoryBackOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryBackOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventoryBackOrderPortType
     */
    @WebEndpoint(name = "InventoryBackOrderPort")
    public InventoryBackOrderPortType getInventoryBackOrderPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", "InventoryBackOrderPort"), InventoryBackOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryBackOrderPortType
     */
    @WebEndpoint(name = "InventoryBackOrderPort")
    public InventoryBackOrderPortType getInventoryBackOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/rms/integration/services/InventoryBackOrderService/v1", "InventoryBackOrderPort"), InventoryBackOrderPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORYBACKORDERSERVICE_EXCEPTION!= null) {
            throw INVENTORYBACKORDERSERVICE_EXCEPTION;
        }
        return INVENTORYBACKORDERSERVICE_WSDL_LOCATION;
    }

}
