package oracle.retail.sim.client.swing.event;

import java.awt.KeyEventDispatcher;
import java.awt.event.KeyEvent;

/******************************************************************************************
 * This class implements the standard KeyEventDispatcher and handles special processes of FUNCTION
 * key. It calls back to the dispatcher asking for the function key to be processed and then
 * consumes the event keeping it from being processed by the rest of the event queue.
 * <p>
 * Copyright 2004, 2013, Oracle. All rights reserved.
 ******************************************************************************************/

public class HotKeyEventDispatcher implements KeyEventDispatcher {
    private HotKeyDispatcher dispatcher;

    /******************************************************************************************
     * Constructs a new hot key queue.
     * <p>
     * @param dispatcher The dispatcher that should process the hot keys.
     ******************************************************************************************/
    public HotKeyEventDispatcher(HotKeyDispatcher dispatcher) {
        this.dispatcher = dispatcher;
    }

    /******************************************************************************************
     * Override the dispatchKeyEvent() method to tell the listener to process the hot keys.
     * <p>
     * @param event The KeyEvent generated by the system.
     ******************************************************************************************/
    public boolean dispatchKeyEvent(KeyEvent event) {
        if (event.getID() == KeyEvent.KEY_RELEASED && !event.isAltDown()) {
            int keycode = event.getKeyCode();
            switch (keycode) {
                case KeyEvent.VK_F1:
                case KeyEvent.VK_F2:
                case KeyEvent.VK_F3:
                case KeyEvent.VK_F4:
                case KeyEvent.VK_F5:
                case KeyEvent.VK_F6:
                case KeyEvent.VK_F7:
                case KeyEvent.VK_F8:
                case KeyEvent.VK_F9:
                case KeyEvent.VK_F10:
                case KeyEvent.VK_F11:
                case KeyEvent.VK_F12:
                    return dispatcher.hotKeyPressed(keycode);
            }
        }
        return false;
    }
}
