#rms.datasource.url=jdbc:oracle:thin:@exvm-qarmsdb02.extrastores.com:1521/RMSQA.extrastores.com
#rms.datasource.username=RMS14
#rms.datasource.password=retQAtrex123



rms.datasource.url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
rms.datasource.username=RMS14
rms.datasource.password=kcv123retlv