user_name=RMS14
password=retQAtrex123
url=jdbc:oracle:thin:@exvm-qarmsdb01.extrastores.com:1521/RMSQA.extrastores.com
driver=oracle.jdbc.driver.OracleDriver


#user_name=RMS14
#password=kcv123retlv
#url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
#driver=oracle.jdbc.driver.OracleDriver


#user_name=EXTRADEV
#password=Extra123
##RMS14
##retQAtrex123
##jdbc:oracle:thin:@exvm-qarmsdb02.extrastores.com:1521/RMSQA.extrastores.com