package com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.4.0.6436

public class FulfillmentOrderDeliveryPortClient
{
  public static void main(String [] args)
  {
    FulfillmentOrderDeliveryService fulfillmentOrderDeliveryService = new FulfillmentOrderDeliveryService();
    FulfillmentOrderDeliveryPortType fulfillmentOrderDeliveryPortType = fulfillmentOrderDeliveryService.getFulfillmentOrderDeliveryPort();
    // Add your code to call the desired methods.
  }
}
