
package com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.fodcremodvo.v1.FodCreModVo;
import com.oracle.retail.integration.base.bo.foddesc.v1.FodDesc;
import com.oracle.retail.integration.base.bo.fodhdrcoldesc.v1.FodHdrColDesc;
import com.oracle.retail.integration.base.bo.fodmodvo.v1.FodModVo;
import com.oracle.retail.integration.base.bo.fodref.v1.FodRef;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;
import com.oracle.retail.integration.base.bo.strfordref.v1.StrFordRef;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "FulfillmentOrderDeliveryPortType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.fodcremodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.foddesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fodhdrcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fodhdrdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fodmodvo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fodref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strfordref.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.ObjectFactory.class
})
public interface FulfillmentOrderDeliveryPortType {


    /**
     * 
     * @param fodRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "cancelFulfillmentOrderDelivery", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.CancelFulfillmentOrderDelivery")
    @ResponseWrapper(localName = "cancelFulfillmentOrderDeliveryResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.CancelFulfillmentOrderDeliveryResponse")
    public InvocationSuccess cancelFulfillmentOrderDelivery(
        @WebParam(name = "FodRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodRef/v1")
        FodRef fodRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fodRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "dispatchFulfillmentOrderDelivery", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.DispatchFulfillmentOrderDelivery")
    @ResponseWrapper(localName = "dispatchFulfillmentOrderDeliveryResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.DispatchFulfillmentOrderDeliveryResponse")
    public InvocationSuccess dispatchFulfillmentOrderDelivery(
        @WebParam(name = "FodRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodRef/v1")
        FodRef fodRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fodRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "submitFulfillmentOrderDelivery", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.SubmitFulfillmentOrderDelivery")
    @ResponseWrapper(localName = "submitFulfillmentOrderDeliveryResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.SubmitFulfillmentOrderDeliveryResponse")
    public InvocationSuccess submitFulfillmentOrderDelivery(
        @WebParam(name = "FodRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodRef/v1")
        FodRef fodRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fodModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "updateFulfillmentOrderDelivery", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.UpdateFulfillmentOrderDelivery")
    @ResponseWrapper(localName = "updateFulfillmentOrderDeliveryResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.UpdateFulfillmentOrderDeliveryResponse")
    public InvocationSuccess updateFulfillmentOrderDelivery(
        @WebParam(name = "FodModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodModVo/v1")
        FodModVo fodModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strFordRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.fodhdrcoldesc.v1.FodHdrColDesc
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "FodHdrColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodHdrColDesc/v1")
    @RequestWrapper(localName = "lookupFulfillmentOrderDeliveryHeaders", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.LookupFulfillmentOrderDeliveryHeaders")
    @ResponseWrapper(localName = "lookupFulfillmentOrderDeliveryHeadersResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.LookupFulfillmentOrderDeliveryHeadersResponse")
    public FodHdrColDesc lookupFulfillmentOrderDeliveryHeaders(
        @WebParam(name = "StrFordRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrFordRef/v1")
        StrFordRef strFordRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fodRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.foddesc.v1.FodDesc
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "FodDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodDesc/v1")
    @RequestWrapper(localName = "readFulfillmentOrderDeliveryDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.ReadFulfillmentOrderDeliveryDetail")
    @ResponseWrapper(localName = "readFulfillmentOrderDeliveryDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.ReadFulfillmentOrderDeliveryDetailResponse")
    public FodDesc readFulfillmentOrderDeliveryDetail(
        @WebParam(name = "FodRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodRef/v1")
        FodRef fodRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fodCreModVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.fodref.v1.FodRef
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "FodRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodRef/v1")
    @RequestWrapper(localName = "createFulfillmentOrderDelivery", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.CreateFulfillmentOrderDelivery")
    @ResponseWrapper(localName = "createFulfillmentOrderDeliveryResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.CreateFulfillmentOrderDeliveryResponse")
    public FodRef createFulfillmentOrderDelivery(
        @WebParam(name = "FodCreModVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodCreModVo/v1")
        FodCreModVo fodCreModVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fodRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "cancelFulfillmentOrderDeliverySubmission", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.CancelFulfillmentOrderDeliverySubmission")
    @ResponseWrapper(localName = "cancelFulfillmentOrderDeliverySubmissionResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.CancelFulfillmentOrderDeliverySubmissionResponse")
    public InvocationSuccess cancelFulfillmentOrderDeliverySubmission(
        @WebParam(name = "FodRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FodRef/v1")
        FodRef fodRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderDeliveryService/v1", className = "com.oracle.retail.sim.integration.services.fulfillmentorderdeliveryservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
