<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:tns="http://www.oracle.com/retail/integration/base/bo/FodHdrDesc/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0" targetNamespace="http://www.oracle.com/retail/integration/base/bo/FodHdrDesc/v1">
  <xs:element name="FodHdrDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="int_fulfill_order_delivery_id" type="xs:long"/>
        <xs:element name="fulfill_order_id" type="xs:long"/>
        <xs:element name="status" type="tns:fod_status"/>
        <xs:element name="create_date" type="xs:dateTime"/>
        <xs:element name="dispatch_date" type="xs:dateTime" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="fod_status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IN_PROGRESS"/>
      <xs:enumeration value="SUBMITTED"/>
      <xs:enumeration value="COMPLETED"/>
      <xs:enumeration value="CANCELED"/>
      <xs:enumeration value="UNKNOWN"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>