package oracle.retail.sim.client.screen.itemticket;

import java.awt.GridBagLayout;
import java.util.ArrayList;
import java.util.List;
import oracle.retail.sim.client.application.Application;
import oracle.retail.sim.client.core.RHeaderPanel;
import oracle.retail.sim.client.core.SimNavigation;
import oracle.retail.sim.client.swing.dialog.RDialog;
import oracle.retail.sim.client.swing.editor.RDisplayLabelEditor;
import oracle.retail.sim.client.swing.event.RActionEvent;
import oracle.retail.sim.client.swing.event.REventListener;
import oracle.retail.sim.client.swing.panel.RPanel;
import oracle.retail.sim.client.swing.table.SimTable;
import oracle.retail.sim.client.swing.table.SimTableAttribute;
import oracle.retail.sim.client.swing.table.SimTableDefinition;
import oracle.retail.sim.client.swing.table.SimTablePane;
import oracle.retail.sim.client.swing.util.GridTool;
import oracle.retail.sim.client.swing.widget.RButton;
import oracle.retail.sim.client.util.SimClientStateKey;
import oracle.retail.sim.common.business.BusinessException;
import oracle.retail.sim.common.business.CommonMessageText;
import oracle.retail.sim.common.uin.SerialNumberValue;

/********************************************************************************************************
 * This dialog handles selecting UINs for a Retail Item.
 * <p>
 * Copyright 2004, 2013, Oracle. All rights reserved.
 *******************************************************************************************************/

public class ItemTicketSelectUinDialog extends RDialog implements REventListener {
    private static final long serialVersionUID = -4402337753570856048L;

    private ItemTicketSelectUinModel model = new ItemTicketSelectUinModel();

    private RDisplayLabelEditor itemEditor = new RDisplayLabelEditor("Item");
    private RDisplayLabelEditor itemDescEditor = new RDisplayLabelEditor("Item Description");

    private SimTable uinTable = new SimTable(new SelectUINTableDefinition());
    private SimTablePane uinTablePane = new SimTablePane(uinTable);

    private RButton applyButton = new RButton(SimNavigation.DIALOG_APPLY);
    private RButton cancelButton = new RButton(SimNavigation.DIALOG_CANCEL);

    /****************************************************************************************************
     * Build Dialog
     ***************************************************************************************************/
    public ItemTicketSelectUinDialog() {
        super(Application.getFrame());
        setStatusBarVisible(false);
        setTitle("Select UINs");
        setSize(450, 430);
        initContent();
        layoutContent();
        centerOnOwner();
    }

    private void initContent() {
        applyButton.registerAction(this, SimNavigation.DIALOG_APPLY);
        cancelButton.registerAction(this, SimNavigation.DIALOG_CANCEL);

        uinTable.setMultipleRowSelectionMode();

        setDefaultButton(applyButton);
    }

    private void layoutContent() {
        addButton(applyButton);
        addButton(cancelButton);

        RHeaderPanel headerPanel = new RHeaderPanel(2);
        headerPanel.add(itemEditor);
        headerPanel.add(itemDescEditor);

        RPanel mainPanel = new RPanel(new GridBagLayout());
        mainPanel.add(headerPanel, GridTool.constraints(0, 0, 1, 1, 1, 0, 0, 3, 0, 0, 5, 0));
        mainPanel.add(uinTablePane, GridTool.constraints(0, 1, 1, 1, 1, 1, 0, 3, 0, 0, 0, 0));

        setContentPane(mainPanel);
    }

    public void setItemTicketLineItemWrapper(ItemTicketLineItemWrapper itemTicketLineItemWrapper) throws Exception {
        model.setItemTicketWrapper(itemTicketLineItemWrapper);
        itemEditor.setData(itemTicketLineItemWrapper.getItemId());
        itemDescEditor.setData(itemTicketLineItemWrapper.getDescription());
        uinTable.setRows(model.findAutoGeneratedSerialNumbers());
    }

    public void stopEditing() {
        uinTable.stopEditing();
    }

    /****************************************************************************************************
     * Handle Actions
     ***************************************************************************************************/
    public void performActionEvent(RActionEvent event) {
        String command = event.getEventCommand();
        try {
            stopEditing();
            if (command.equals(SimNavigation.DIALOG_APPLY)) {
                doApply();
            } else if (command.equals(SimNavigation.DIALOG_CANCEL)) {
                doCancel();
            }
        } catch (Throwable exception) {
            displayException(exception);
        }
    }

    /****************************************************************************************************
     * Apply Action
     ***************************************************************************************************/

    private void doApply() throws Exception {
        if (uinTable.getSelectedRowCount() == 0) {
            displayException(new BusinessException(CommonMessageText.NO_ROWS_SELECTED));
            return;
        }
        List<SerialNumberValue> serialNumbers = uinTable.getAllSelectedRowData();
        model.saveSerialNumbers(serialNumbers);
        notifyREventListeners(new RActionEvent(this, SimClientStateKey.ITEM_TICKET_APPLY_SELECTED_UIN, model.getSerialNumbers()));
        closeWindow();
    }

    /****************************************************************************************************
     * Cancel Action
     ***************************************************************************************************/
    private void doCancel() {
        uinTable.clearRows();
        closeWindow();
    }

    /****************************************************************************************************
     * Select UIN Table Definition
     ***************************************************************************************************/

    private class SelectUINTableDefinition extends SimTableDefinition {

        public Class getDataClass() {
            return SerialNumberValue.class;
        }

        public List<SimTableAttribute> getAttributes() {
            List<SimTableAttribute> attributes = new ArrayList<>(1);
            attributes.add(new SimTableAttribute("UIN", "uin"));
            return attributes;
        }
    }
}
