package oracle.retail.sim.client.screen.itemticket;

import java.util.List;
import oracle.retail.sim.client.core.SimScreenModel;
import oracle.retail.sim.common.uin.SerialNumberValue;
import oracle.retail.sim.service.core.ClientServiceFactory;

/********************************************************************************************************
 * Item Ticket Select UIN Model
 * <p>
 * Copyright 2004, 2013, Oracle. All rights reserved.
 *******************************************************************************************************/

public class ItemTicketSelectUinModel extends SimScreenModel {
    private ItemTicketLineItemWrapper itemTicketLineItemWrapper;

    public ItemTicketLineItemWrapper getItemTicketWrapper() {
        return itemTicketLineItemWrapper;
    }

    public void setItemTicketWrapper(ItemTicketLineItemWrapper itemTicketLineItemWrapper) {
        this.itemTicketLineItemWrapper = itemTicketLineItemWrapper;
    }

    public List<SerialNumberValue> findAutoGeneratedSerialNumbers() throws Exception {
        return ClientServiceFactory.getUINServices().findAutoGeneratedSerialNumbers(itemTicketLineItemWrapper.getItemId(), getStoreId());
    }

    public void saveSerialNumbers(List<SerialNumberValue> serialNumberValues) throws Exception {
        for (SerialNumberValue serialNumber : serialNumberValues) {
            itemTicketLineItemWrapper.addSerialNumber(serialNumber);
        }
    }

    public List<SerialNumberValue> getSerialNumbers() {
        return itemTicketLineItemWrapper.getSerialNumbers();
    }

}
