package oracle.retail.sim.common.configutil;

public class StoreConfigKeys {
  public static final String REPLENISHMENT_WITHIN_DAY_MAX_FILL_PCT = "REPLENISHMENT_WITHIN_DAY_MAX_FILL_PCT";
  
  public static final String REPLENISHMENT_END_OF_DAY_MAX_FILL_PCT = "REPLENISHMENT_END_OF_DAY_MAX_FILL_PCT";
  
  public static final String REPLENISHMENT_ITEM_OUT_OF_STOCK_STANDARD_UOM = "REPLENISHMENT_ITEM_OUT_OF_STOCK_STANDARD_UOM";
  
  public static final String REPLENISHMENT_ITEM_OUT_OF_STOCK_PCT = "REPLENISHMENT_ITEM_OUT_OF_STOCK_PCT";
  
  public static final String REPLENISHMENT_DELIVERY_BAY_INVENTORY = "REPLENISHMENT_DELIVERY_BAY_INVENTORY";
  
  public static final String SEND_SHELF_EDGE_LABELS_TO_TICKETING_FOR_PRICE_CHANGE = "SEND_SHELF_EDGE_LABELS_TO_TICKETING_FOR_PRICE_CHANGE";
  
  public static final String SEND_ITEM_TICKETS_TO_TICKETING_FOR_PRICE_CHANGE = "SEND_ITEM_TICKETS_TO_TICKETING_FOR_PRICE_CHANGE";
  
  public static final String SEND_SHELF_EDGE_LABELS_TO_TICKETING_FOR_DESC_CHANGE = "SEND_SHELF_EDGE_LABELS_TO_TICKETING_FOR_DESC_CHANGE";
  
  public static final String SEND_ITEM_TICKETS_TO_TICKETING_FOR_DESC_CHANGE = "SEND_ITEM_TICKETS_TO_TICKETING_FOR_DESC_CHANGE";
  
  public static final String SEND_SHELF_EDGE_LABELS_TO_TICKETING_FOR_QR_CODE_CHANGE = "SEND_SHELF_EDGE_LABELS_TO_TICKETING_FOR_QR_CODE_CHANGE";
  
  public static final String SEND_ITEM_TICKETS_TO_TICKETING_FOR_QR_CODE_CHANGE = "SEND_ITEM_TICKETS_TO_TICKETING_FOR_QR_CODE_CHANGE";
  
  public static final String AUTO_DEFAULT_LABEL = "ASSIGN_SHELF_LABELS";
  
  public static final String FUL_ORDER_DISPATCH_VALIDATE = "FUL_ORDER_DISPATCH_VALIDATE";
  
  public static final String PICKING_REQUIRED_FOR_CUSTOMER_ORDERS = "PICKING_REQUIRED_FOR_CUSTOMER_ORDERS";
  
  public static final String PRESHIPMENT_NOTIFICATION = "PRESHIPMENT_NOTIFICATION";
  
  public static final String RESERVE_CUSTOMER_ORDER_INVENTORY_UPON_RECEIVING = "RESERVE_CUSTOMER_ORDER_INVENTORY_UPON_RECEIVING";
  
  public static final String DEFAULT_CUSTOMER_ORDER_PICKING_METHOD = "DEFAULT_CUSTOMER_ORDER_PICKING_METHOD";
  
  public static final String DEFAULT_NUMBER_OF_BINS = "DEFAULT_NUMBER_OF_BINS";
  
  public static final String OVERRIDE_BIN_QUANTITY = "OVERRIDE_BIN_QUANTITY";
  
  public static final String GENERATE_BINS = "GENERATE_BINS";
  
  public static final String HANDHELD_PICKING_MODE = "HANDHELD_PICKING_MODE";
  
  public static final String ITEM_SUBSTITUTION_STORE_DISCRETION = "ITEM_SUBSTITUTION_STORE_DISCRETION";
  
  public static final String AUTO_PICK_ON_RECEIVE_DIRECT_DELIVERY = "AUTO_PICK_ON_RECEIVE_DIRECT_DELIVERY";
  
  public static final String AUTO_PICK_ON_RECEIVE_TRANSFER = "AUTO_PICK_ON_RECEIVE_TRANSFER";
  
  public static final String AUTO_PICK_ON_RECEIVE_WAREHOUSE_DELIVERY = "AUTO_PICK_ON_RECEIVE_WAREHOUSE_DELIVERY";
  
  public static final String AUTO_PICK_MIXED_CARTONS = "AUTO_PICK_MIXED_CARTONS";
  
  public static final String STOCK_COUNT_DEFAULT_TIMEFRAME = "STOCK_COUNT_DEFAULT_TIMEFRAME";
  
  public static final String DISPLAY_LATE_ADJUSTMENT_MESSAGE = "DISPLAY_LATE_ADJUSTMENT_MESSAGE";
  
  public static final String DISPLAY_SEQUENCE_FIELDS = "DISPLAY_SEQUENCE_FIELDS";
  
  public static final String DISPLAY_ITEM_REQUEST_DELIVERY_TIMESLOT = "DISPLAY_ITEM_REQUEST_DELIVERY_TIMESLOT";
  
  public static final String ITEM_BASKET_PRINTING = "ITEM_BASKET_PRINTING";
  
  public static final String REPORT_FORMAT_ITEM_BASKET = "REPORT_FORMAT_ITEM_BASKET";
  
  public static final String DIRECT_DELIVERY_REMOVE_DAMAGES = "DIRECT_DELIVERY_REMOVE_DAMAGES";
  
  public static final String DIRECT_DELIVERY_REMOVE_OVER_RECEIVE = "DIRECT_DELIVERY_REMOVE_OVER_RECEIVE";
  
  public static final String DIRECT_DELIVERY_DEFAULT_DELIVERY_QUANTITIES = "DIRECT_DELIVERY_DEFAULT_DELIVERY_QUANTITIES";
  
  public static final String DIRECT_DELIVERY_INVOICE_ENTRY = "DIRECT_DELIVERY_INVOICE_ENTRY";
  
  public static final String STORE_AUTO_RECEIVE = "STORE_AUTO_RECEIVE";
  
  public static final String STORE_AUTO_RECEIVE_NUMBER_OF_DAYS = "STORE_AUTO_RECEIVE_NUMBER_OF_DAYS";
  
  public static final String WAREHOUSE_AUTO_RECEIVE = "WAREHOUSE_AUTO_RECEIVE";
  
  public static final String WAREHOUSE_AUTO_RECEIVE_NUMBER_OF_DAYS = "WAREHOUSE_AUTO_RECEIVE_NUMBER_OF_DAYS";
  
  public static final String EXTERNAL_FINISHER_AUTO_RECEIVE = "EXTERNAL_FINISHER_AUTO_RECEIVE";
  
  public static final String EXTERNAL_FINISHER_AUTO_RECEIVE_NUMBER_OF_DAYS = "EXTERNAL_FINISHER_AUTO_RECEIVE_NUMBER_OF_DAYS";
  
  public static final String ENABLE_ITEM_DISPOSITION_IN_TRANSACTION_UPDATES = "ENABLE_ITEM_DISPOSITION_IN_TRANSACTION_UPDATES";
  
  public static final String UIN_PROCESSING_ENABLED = "UIN_PROCESSING_ENABLED";
  
  public static final String USE_ADVANCED_ITEM_ENTRY = "USE_ADVANCED_ITEM_ENTRY";
  
  public static final String AUTO_APPLY_ADVANCED_ITEM_ENTRY = "AUTO_APPLY_ADVANCED_ITEM_ENTRY";
  
  public static final String OMS_CUSTOMER_ORDER_DELIVERY_VALIDATION = "OMS_CUSTOMER_ORDER_DELIVERY_VALIDATION";
  
  public static final String MANIFEST_CUSTOMER_ORDER_DELIVERIES = "MANIFEST_CUSTOMER_ORDER_DELIVERIES";
  
  public static final String MANIFEST_RETURNS_SUPPLIER = "MANIFEST_RETURNS_SUPPLIER";
  
  public static final String MANIFEST_RETURNS_WAREHOUSE = "MANIFEST_RETURNS_WAREHOUSE";
  
  public static final String MANIFEST_RETURNS_FINISHER = "MANIFEST_RETURNS_FINISHER";
  
  public static final String MANIFEST_STORE_TO_STORE_TRANSFER = "MANIFEST_STORE_TO_STORE_TRANSFER";
  
  public static final String RETURN_VALIDATE_DISPATCH = "RETURN_VALIDATE_DISPATCH";
  
  public static final String PRESHIPMENT_NOTIFICATION_RETURN = "PRESHIPMENT_NOTIFICATION_RETURN";
  
  public static final String RETURN_CARRIER_DEFAULT = "RETURN_CARRIER_DEFAULT";
  
  public static final String PRESHIPMENT_NOTIFICATION_TRANSFER = "PRESHIPMENT_NOTIFICATION_TRANSFER";
  
  public static final String TRANSFER_DISPATCH_VALIDATE = "TRANSFER_DISPATCH_VALIDATE";
  
  public static final String STORE_TO_STORE_CARRIER_DEFAULT = "STORE_TO_STORE_CARRIER_DEFAULT";
  
  public static final String MANIFEST_WEIGHT_UOM = "MANIFEST_WEIGHT_UOM";
}


/* Location:              C:\Users\aibrahim\eclipse-workspace\sim-client\lib\sim-common.jar!\oracle\retail\sim\common\configutil\StoreConfigKeys.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */