
package com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "IllegalArgumentWSFaultException", targetNamespace = "http://www.oracle.com/retail/integration/services/exception/v1")
public class IllegalArgumentWSFaultException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private com.oracle.retail.integration.services.exception.v1.IllegalArgumentWSFaultException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public IllegalArgumentWSFaultException(String message, com.oracle.retail.integration.services.exception.v1.IllegalArgumentWSFaultException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public IllegalArgumentWSFaultException(String message, com.oracle.retail.integration.services.exception.v1.IllegalArgumentWSFaultException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.oracle.retail.integration.services.exception.v1.IllegalArgumentWSFaultException
     */
    public com.oracle.retail.integration.services.exception.v1.IllegalArgumentWSFaultException getFaultInfo() {
        return faultInfo;
    }

}
