
package com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.fulfilordcfmcol.v1.FulfilOrdCfmCol;
import com.oracle.retail.integration.base.bo.fulfilordcoldesc.v1.FulfilOrdColDesc;
import com.oracle.retail.integration.base.bo.fulfilordcolref.v1.FulfilOrdColRef;
import com.oracle.retail.integration.base.bo.strforddesc.v1.StrFordDesc;
import com.oracle.retail.integration.base.bo.strfordhdrcoldesc.v1.StrFordHdrColDesc;
import com.oracle.retail.integration.base.bo.strfordhdrcrivo.v1.StrFordHdrCriVo;
import com.oracle.retail.integration.base.bo.strfordref.v1.StrFordRef;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StoreFulfillmentOrderPortType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.fulfilordcfmcol.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcfmdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcfmdtl.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcolref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilorddesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilorddtl.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilorddtlref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.fulfilordref.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.locoffulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strforddesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strfordhdrcoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strfordhdrcrivo.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strfordhdrdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.strfordref.v1.ObjectFactory.class,
    com.oracle.retail.integration.custom.bo.eofbrfulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.localization.bo.brfulfilordcustdesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.ObjectFactory.class
})
public interface StoreFulfillmentOrderPortType {


    /**
     * 
     * @param strFordHdrCriVo
     * @return
     *     returns com.oracle.retail.integration.base.bo.strfordhdrcoldesc.v1.StrFordHdrColDesc
     * @throws IllegalArgumentWSFaultException
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrFordHdrColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrFordHdrColDesc/v1")
    @RequestWrapper(localName = "lookupFulfillmentOrderHeaders", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.LookupFulfillmentOrderHeaders")
    @ResponseWrapper(localName = "lookupFulfillmentOrderHeadersResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.LookupFulfillmentOrderHeadersResponse")
    public StrFordHdrColDesc lookupFulfillmentOrderHeaders(
        @WebParam(name = "StrFordHdrCriVo", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrFordHdrCriVo/v1")
        StrFordHdrCriVo strFordHdrCriVo)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param strFordRef
     * @return
     *     returns com.oracle.retail.integration.base.bo.strforddesc.v1.StrFordDesc
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "StrFordDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrFordDesc/v1")
    @RequestWrapper(localName = "readFulfillmentOrderDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.ReadFulfillmentOrderDetail")
    @ResponseWrapper(localName = "readFulfillmentOrderDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.ReadFulfillmentOrderDetailResponse")
    public StrFordDesc readFulfillmentOrderDetail(
        @WebParam(name = "StrFordRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/StrFordRef/v1")
        StrFordRef strFordRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fulfilOrdColDesc
     * @return
     *     returns com.oracle.retail.integration.base.bo.fulfilordcfmcol.v1.FulfilOrdCfmCol
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @WebResult(name = "FulfilOrdCfmCol", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FulfilOrdCfmCol/v1")
    @RequestWrapper(localName = "createFulfillmentOrderDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.CreateFulfillmentOrderDetail")
    @ResponseWrapper(localName = "createFulfillmentOrderDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.CreateFulfillmentOrderDetailResponse")
    public FulfilOrdCfmCol createFulfillmentOrderDetail(
        @WebParam(name = "FulfilOrdColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FulfilOrdColDesc/v1")
        FulfilOrdColDesc fulfilOrdColDesc)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param fulfilOrdColRef
     * @throws IllegalArgumentWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalStateWSFaultException
     */
    @WebMethod
    @RequestWrapper(localName = "cancelFulfillmentOrderDetail", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.CancelFulfillmentOrderDetail")
    @ResponseWrapper(localName = "cancelFulfillmentOrderDetailResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.CancelFulfillmentOrderDetailResponse")
    public void cancelFulfillmentOrderDetail(
        @WebParam(name = "FulfilOrdColRef", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/FulfilOrdColRef/v1", mode = WebParam.Mode.INOUT)
        Holder<FulfilOrdColRef> fulfilOrdColRef)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", className = "com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
