
package com.oracle.retail.sim.integration.services.storefulfillmentorderservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "StoreFulfillmentOrderService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", wsdlLocation = "http://exvm-qaadfapp01.extrastores.com:7511/StoreFulfillmentOrderBean/StoreFulfillmentOrderService?wsdl")
public class StoreFulfillmentOrderService
    extends Service
{

    private final static URL STOREFULFILLMENTORDERSERVICE_WSDL_LOCATION;
    private final static WebServiceException STOREFULFILLMENTORDERSERVICE_EXCEPTION;
    private final static QName STOREFULFILLMENTORDERSERVICE_QNAME = new QName("http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", "StoreFulfillmentOrderService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exvm-qaadfapp01.extrastores.com:7511/StoreFulfillmentOrderBean/StoreFulfillmentOrderService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOREFULFILLMENTORDERSERVICE_WSDL_LOCATION = url;
        STOREFULFILLMENTORDERSERVICE_EXCEPTION = e;
    }

    public StoreFulfillmentOrderService() {
        super(__getWsdlLocation(), STOREFULFILLMENTORDERSERVICE_QNAME);
    }

    public StoreFulfillmentOrderService(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOREFULFILLMENTORDERSERVICE_QNAME, features);
    }

    public StoreFulfillmentOrderService(URL wsdlLocation) {
        super(wsdlLocation, STOREFULFILLMENTORDERSERVICE_QNAME);
    }

    public StoreFulfillmentOrderService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOREFULFILLMENTORDERSERVICE_QNAME, features);
    }

    public StoreFulfillmentOrderService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StoreFulfillmentOrderService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns StoreFulfillmentOrderPortType
     */
    @WebEndpoint(name = "StoreFulfillmentOrderPort")
    public StoreFulfillmentOrderPortType getStoreFulfillmentOrderPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", "StoreFulfillmentOrderPort"), StoreFulfillmentOrderPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StoreFulfillmentOrderPortType
     */
    @WebEndpoint(name = "StoreFulfillmentOrderPort")
    public StoreFulfillmentOrderPortType getStoreFulfillmentOrderPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/StoreFulfillmentOrderService/v1", "StoreFulfillmentOrderPort"), StoreFulfillmentOrderPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (STOREFULFILLMENTORDERSERVICE_EXCEPTION!= null) {
            throw STOREFULFILLMENTORDERSERVICE_EXCEPTION;
        }
        return STOREFULFILLMENTORDERSERVICE_WSDL_LOCATION;
    }

}
