<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>oms-util</artifactId>
	<packaging>pom</packaging>
	<name>OMSUtil</name>
	<url>http://maven.apache.org</url>
	<description>This POM is only for import in eclipse, not for build. Use ant
		script for build the application</description>

	<parent>
		<groupId>com.extra</groupId>
		<artifactId>oms-parent</artifactId>
		<version>0.0.1</version>
		<relativePath>../oms-parent/pom.xml</relativePath>
	</parent>

	<dependencies>
		<dependency>
			<groupId>com.extra</groupId>
			<artifactId>oms-common</artifactId>
			<version>1.1.0</version>
		</dependency>

		<dependency>
			<groupId>com.sun.xml.ws</groupId>
			<artifactId>jaxws-ri</artifactId>
			<version>2.3.2</version>
			<type>pom</type>
		</dependency>
	</dependencies>

	<build>
		<finalName>OMSUtil</finalName>
		<sourceDirectory>${project.basedir}/src</sourceDirectory>
		<testSourceDirectory>${project.basedir}/test</testSourceDirectory>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-install-plugin</artifactId>
				<version>2.5.2</version>
				<executions>
					<execution>
						<phase>install</phase>
						<goals>
							<goal>install-file</goal>
						</goals>
						<configuration>
							<file>${project.basedir}/deploy/OMSUtilEJB-2.48.jar</file>
							<groupId>${project.groupId}</groupId>
							<artifactId>${project.artifactId}</artifactId>
							<version>${project.version}</version>
							<packaging>jar</packaging>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>