
package retail.siebel.com.integration;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "inboundordercreationbpelprocess_client_ep", targetNamespace = "http://com.siebel.retail/integration/", wsdlLocation = "http://ex-uat-mw1.extrastores.com:8001/soa-infra/services/IBT_Development/OMSToSiebelOrderCreation/inboundordercreationbpelprocess_client_ep?WSDL#%7Bhttp%3A%2F%2Fcom.siebel.retail%2Fintegration%2F%7Dinboundordercreationbpelprocess_client_ep")
public class InboundordercreationbpelprocessClientEp
    extends Service
{

    private final static URL INBOUNDORDERCREATIONBPELPROCESSCLIENTEP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(retail.siebel.com.integration.InboundordercreationbpelprocessClientEp.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            baseUrl = retail.siebel.com.integration.InboundordercreationbpelprocessClientEp.class.getResource(".");
            url = new URL(baseUrl, "http://ex-uat-mw1.extrastores.com:8001/soa-infra/services/IBT_Development/OMSToSiebelOrderCreation/inboundordercreationbpelprocess_client_ep?WSDL#%7Bhttp%3A%2F%2Fcom.siebel.retail%2Fintegration%2F%7Dinboundordercreationbpelprocess_client_ep");
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://ex-uat-mw1.extrastores.com:8001/soa-infra/services/IBT_Development/OMSToSiebelOrderCreation/inboundordercreationbpelprocess_client_ep?WSDL#%7Bhttp%3A%2F%2Fcom.siebel.retail%2Fintegration%2F%7Dinboundordercreationbpelprocess_client_ep', retrying as a local file");
            logger.warning(e.getMessage());
        }
        INBOUNDORDERCREATIONBPELPROCESSCLIENTEP_WSDL_LOCATION = url;
    }

    public InboundordercreationbpelprocessClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InboundordercreationbpelprocessClientEp() {
        super(INBOUNDORDERCREATIONBPELPROCESSCLIENTEP_WSDL_LOCATION, new QName("http://com.siebel.retail/integration/", "inboundordercreationbpelprocess_client_ep"));
    }

    /**
     * 
     * @return
     *     returns SiebelOrderFeedWebservice
     */
    @WebEndpoint(name = "SiebelOrderFeedWebservice_pt")
    public SiebelOrderFeedWebservice getSiebelOrderFeedWebservicePt() {
        return super.getPort(new QName("http://com.siebel.retail/integration/", "SiebelOrderFeedWebservice_pt"), SiebelOrderFeedWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiebelOrderFeedWebservice
     */
    @WebEndpoint(name = "SiebelOrderFeedWebservice_pt")
    public SiebelOrderFeedWebservice getSiebelOrderFeedWebservicePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.siebel.retail/integration/", "SiebelOrderFeedWebservice_pt"), SiebelOrderFeedWebservice.class, features);
    }

}
