
package retail.siebel.com.integration;


import com.logicinfo.oms.beans.OMSUtilCommons;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "omsorderupdatebpelprocess_client_ep", targetNamespace = "http://com.siebel.retail/integration/", wsdlLocation = "http://ex-uat-mw1.extrastores.com:8001/soa-infra/services/IBT_Development/OrderStatusUpdate/omsorderupdatebpelprocess_client_ep?WSDL#%7Bhttp%3A%2F%2Fcom.siebel.retail%2Fintegration%2F%7Domsorderupdatebpelprocess_client_ep")
public class OmsorderupdatebpelprocessClientEp
    extends Service
{

    private final static URL OMSORDERUPDATEBPELPROCESSCLIENTEP_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(retail.siebel.com.integration.OmsorderupdatebpelprocessClientEp.class.getName());

    static {
        URL url = null;
        try 
        {
            URL baseUrl;
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("SIEBEL_STATUS_UPDATE");
            logger.info("siebel url "+wsdlUrl);
            baseUrl = retail.siebel.com.integration.OmsorderupdatebpelprocessClientEp.class.getResource(".");
            url = new URL(baseUrl,wsdlUrl);
        } 
        catch (MalformedURLException e)
        {
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        OMSORDERUPDATEBPELPROCESSCLIENTEP_WSDL_LOCATION = url;
    }

    public OmsorderupdatebpelprocessClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OmsorderupdatebpelprocessClientEp() {
        super(OMSORDERUPDATEBPELPROCESSCLIENTEP_WSDL_LOCATION, new QName("http://com.siebel.retail/integration/", "omsorderupdatebpelprocess_client_ep"));
    }

    /**
     * 
     * @return
     *     returns SiebelStatusUpdateWebService
     */
    @WebEndpoint(name = "SiebelStatusUpdateWebService_pt")
    public SiebelStatusUpdateWebService getSiebelStatusUpdateWebServicePt() {
        return super.getPort(new QName("http://com.siebel.retail/integration/", "SiebelStatusUpdateWebService_pt"), SiebelStatusUpdateWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SiebelStatusUpdateWebService
     */
    @WebEndpoint(name = "SiebelStatusUpdateWebService_pt")
    public SiebelStatusUpdateWebService getSiebelStatusUpdateWebServicePt(WebServiceFeature... features) {
        return super.getPort(new QName("http://com.siebel.retail/integration/", "SiebelStatusUpdateWebService_pt"), SiebelStatusUpdateWebService.class, features);
    }

}
