
package retail.siebel.com.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SiebelOrderFeedWebservice", targetNamespace = "http://com.siebel.retail/integration/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SiebelOrderFeedWebservice {


    /**
     * 
     * @param part
     * @return
     *     returns retail.siebel.com.integration.CustomerOrderHeaderLevelResponse
     */
    @WebMethod
    @WebResult(name = "NewCustomerOrderHeaderLevelResponse", targetNamespace = "http://com.siebel.retail/integration/", partName = "part")
    public CustomerOrderHeaderLevelResponse publishToSiebel(
        @WebParam(name = "NewCustomerOrderHeaderLevel", targetNamespace = "http://com.siebel.retail/integration/", partName = "part")
        CustomerOrderHeaderLevel part);

}
