package retail.siebel.com.integration;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.4.0.6436

public class SiebelStatusUpdateWebService_ptClient
{
  public static void main(String [] args)
  {
    OmsorderupdatebpelprocessClientEp omsorderupdatebpelprocessClientEp = new OmsorderupdatebpelprocessClientEp();
    SiebelStatusUpdateWebService siebelStatusUpdateWebService = omsorderupdatebpelprocessClientEp.getSiebelStatusUpdateWebServicePt();
    // Add your code to call the desired methods.
  }
}
