
package retail.siebel.com.integration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SiebelStatusUpdateWebService", targetNamespace = "http://com.siebel.retail/integration/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SiebelStatusUpdateWebService {


    /**
     * 
     * @param input
     * @return
     *     returns retail.siebel.com.integration.SiebelStatusUpdateResponse
     */
    @WebMethod
    @WebResult(name = "SiebelStatusUpdateResponse", targetNamespace = "http://com.siebel.retail/integration/", partName = "return")
    public SiebelStatusUpdateResponse processSiebelStatusUpdate(
        @WebParam(name = "SiebelStatusUpdateInfo", targetNamespace = "http://com.siebel.retail/integration/", partName = "input")
        SiebelStatusUpdateInfo input);

}
