<?xml version='1.0' encoding='UTF-8'?>
<definitions name="OMSCustomerOrderStatusUpdate" targetNamespace="http://com.siebel.retail/integration/" xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns1="http://schemas.oracle.com/bpel/extension" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://com.siebel.retail/integration/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <documentation>
    <abstractWSDL>http://ex-uat-mw1.extrastores.com:8001/soa-infra/services/IBT_Development/OrderStatusUpdate!1.0/SiebelStatusUpdateWebService.wsdl</abstractWSDL>
  </documentation>
  <import namespace="http://schemas.oracle.com/bpel/extension" location="omsorderupdatebpelprocess_client_epRuntimeFault.wsdl"/>
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="SiebelStatusUpdate.xsd" namespace="http://com.siebel.retail/integration/"/>
    </xsd:schema>
  </types>
  <message name="processSiebelStatusUpdate">
    <part name="input" element="tns:SiebelStatusUpdateInfo"/>
  </message>
  <message name="processSiebelStatusUpdateResponse">
    <part name="return" element="tns:SiebelStatusUpdateResponse"/>
  </message>
  <message name="RuntimeFaultMessage">
    <part name="return" element="tns:SiebelStatusUpdateResponse"/>
  </message>
  <portType name="SiebelStatusUpdateWebService">
    <operation name="processSiebelStatusUpdate">
      <input message="tns:processSiebelStatusUpdate"/>
      <output message="tns:processSiebelStatusUpdateResponse"/>
    </operation>
  </portType>
  <binding name="SiebelStatusUpdateWebServicePortBinding" type="tns:SiebelStatusUpdateWebService">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="processSiebelStatusUpdate">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="omsorderupdatebpelprocess_client_ep">
    <port name="SiebelStatusUpdateWebService_pt" binding="tns:SiebelStatusUpdateWebServicePortBinding">
      <soap:address location="http://ex-uat-mw1.extrastores.com:8001/soa-infra/services/IBT_Development/OrderStatusUpdate/omsorderupdatebpelprocess_client_ep"/>
    </port>
  </service>
</definitions>