
package com.oracle.retail.sim.integration.services.inventoryadjustmentservice.v1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventoryAdjustmentService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", wsdlLocation = "http://exvm-qaadfapp01.extrastores.com:7511/InventoryAdjustmentBean/InventoryAdjustmentService?WSDL")
public class InventoryAdjustmentService
    extends Service
{

    private final static URL INVENTORYADJUSTMENTSERVICE_WSDL_LOCATION;
    private final static WebServiceException INVENTORYADJUSTMENTSERVICE_EXCEPTION;
    private final static QName INVENTORYADJUSTMENTSERVICE_QNAME = new QName("http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", "InventoryAdjustmentService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://exvm-qaadfapp01.extrastores.com:7511/InventoryAdjustmentBean/InventoryAdjustmentService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTORYADJUSTMENTSERVICE_WSDL_LOCATION = url;
        INVENTORYADJUSTMENTSERVICE_EXCEPTION = e;
    }

    public InventoryAdjustmentService() {
        super(__getWsdlLocation(), INVENTORYADJUSTMENTSERVICE_QNAME);
    }

    public InventoryAdjustmentService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORYADJUSTMENTSERVICE_QNAME, features);
    }

    public InventoryAdjustmentService(URL wsdlLocation) {
        super(wsdlLocation, INVENTORYADJUSTMENTSERVICE_QNAME);
    }

    public InventoryAdjustmentService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORYADJUSTMENTSERVICE_QNAME, features);
    }

    public InventoryAdjustmentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryAdjustmentService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventoryAdjustmentPortType
     */
    @WebEndpoint(name = "InventoryAdjustmentPort")
    public InventoryAdjustmentPortType getInventoryAdjustmentPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", "InventoryAdjustmentPort"), InventoryAdjustmentPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryAdjustmentPortType
     */
    @WebEndpoint(name = "InventoryAdjustmentPort")
    public InventoryAdjustmentPortType getInventoryAdjustmentPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/InventoryAdjustmentService/v1", "InventoryAdjustmentPort"), InventoryAdjustmentPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORYADJUSTMENTSERVICE_EXCEPTION!= null) {
            throw INVENTORYADJUSTMENTSERVICE_EXCEPTION;
        }
        return INVENTORYADJUSTMENTSERVICE_WSDL_LOCATION;
    }

}
