package com.extra.restservice.util;

public class ConstantSchema {

	public static final String SELECT_BY_ID_QUERY = "select oms_cust_ord_no from oms_cust_ord_head where STATUS = 'S' and ORD_PAYMENT_STATUS = 'S' and CUST_ORDER_NO IN (:customerOrderNo)";
	public static final String GET_NOON_REQUEST_INSERT_PARAM = "select SYSTEM_REQUIRED_IND from oms_system_parameters where PARAMETER_ID = (:PARAMETER_ID) and PARAMETER_NAME = (:PARAMETER_NAME)";
	
	/*public static final String INSERT_OMS_RETRUN_REQ = "insert into EXTRADEV.OMS_RETURN_REQ(RET_REQ_ID,RET_ID,CUST_ORDER_NO,STATUS,RETURN_LOC_ID,RETURN_DATE_TIME,REFUND_OPTION,REFUND_COMPLT_IND,REFUND_AMOUNT,COMMENTS,RETURN_STATUS,ORIG_REFUND_AMT,CREATE_DATETIME,LAST_UPDATE_DATETIME) values "
			+ "(:RET_REQ_ID,:RET_ID,:CUST_ORDER_NO,:STATUS,:RETURN_LOC_ID,:RETURN_DATE_TIME,:REFUND_OPTION,:REFUND_COMPLT_IND,:REFUND_AMOUNT,:COMMENTS,:RETURN_STATUS,ORIG_REFUND_AMT,:CREATE_DATETIME,:LAST_UPDATE_DATETIME)";
	
	public static final String INSERT_OMS_RETURN_REQ_ITEM= "insert into EXTRADEV.OMS_RETURN_REQ_ITEM(RET_ID,ITEM,LINE_NO,RET_QTY,ORIG_RET_QTY,ITEM_COMMENTS,RECEIVED_QTY,CANCEL_QTY,STATUS,CREATE_DATETIME,LAST_UPDATE_DATETIME) values "
			+ "(:RET_ID,:ITEM,:LINE_NO,:RET_QTY,:ORIG_RET_QTY,:ITEM_COMMENTS,:RECEIVED_QTY,:CANCEL_QTY,:STATUS,:CREATE_DATETIME,:LAST_UPDATE_DATETIME)";*/
	public static final String INSERT_OMS_RMA_RCV_DETAIL= "insert into OMS_RMA_RCV_DTL(RMA_ID,PROCESS_SEQ_NO,MESSAGE_ID,CUST_ORDER_NO,OMS_CUST_ORD_NO,ORDER_REQUESTOR_TYPE,ORDER_REQUESTOR_ID,ITEM,LINE_ITEM_NBR,RECEIVED_QTY,RTLOG_PUB_IND,CREATE_DATETIME) values "
			+ "(:RMA_ID,:PROCESS_SEQ_NO,:MESSAGE_ID,:CUST_ORDER_NO,:OMS_CUST_ORD_NO,:ORDER_REQUESTOR_TYPE,:ORDER_REQUESTOR_ID,:ITEM,:LINE_ITEM_NBR,:RECEIVED_QTY,:RTLOG_PUB_IND,:CREATE_DATETIME)";
    public static final String SELECT_RMA_SEQ_NEXT="SELECT RMA_REQ_ID_SEQ.nextval FROM DUAL";
    public static final String SELECT_OMS_RMA_ID_SEQ_NEXT="SELECT OMSDEV.NOON_RMA_ID_SEQ.nextval FROM DUAL";
    public static final String FETCH_RMI_ID_OMS_RETRUN_REQ="select RMA_ID from OMS_RETRUN_REQ where (:customerOrderNo)";
    public static final String NOON_RMA_SEQ_NEXT="SELECT OMSDEV.NOON_RMA_SEQ.NEXTVAL FROM DUAL";
    
    public static final String INSERT_OMS_RMA_REQ = "insert into OMS_RMA_REQ(OMS_CUST_ORD_NO, RMA_REQ_ID,RMA_ID,Cust_order_no ,SUB_CUST_ORDER_NO,STATUS,RETURN_LOC_ID,RETURN_DATE_TIME,Refund_Option,REFUND_COMPLT_IND,REFUND_AMOUNT,COMMENTS, RETURN_STATUS, ORIG_REFUND_AMT,RESTOCK_PERCENTAGE,RESTOCK_AMOUNT,CREATE_DATETIME,LAST_UPDATE_DATETIME) values "
			+ "(:OMS_CUST_ORD_NO, :RMA_REQ_ID,:RMA_ID,:Cust_order_no ,:SUB_CUST_ORDER_NO,:STATUS,:RETURN_LOC_ID,:RETURN_DATE_TIME,:Refund_Option,:REFUND_COMPLT_IND,:REFUND_AMOUNT,:COMMENTS, :RETURN_STATUS,:ORIG_REFUND_AMT,:RESTOCK_PERCENTAGE,:RESTOCK_AMOUNT,:CREATE_DATETIME,:LAST_UPDATE_DATETIME)";
    public static final String INSERT_OMS_RMA_REQ_ITEM="insert into OMS_RMA_REQ_ITEM(RMA_ID,ITEM,LINE_NO,RMA_QTY,ORIG_RMA_QTY,ITEM_COMMENTS,RECEIVED_QTY,CANCEL_QTY,STATUS,CREATE_DATETIME,LAST_UPDATE_DATETIME) values "
			+ "(:RMA_ID,:ITEM,:LINE_NO,:RMA_QTY,:ORIG_RMA_QTY,:ITEM_COMMENTS,:RECEIVED_QTY,:CANCEL_QTY,:STATUS,:CREATE_DATETIME,:LAST_UPDATE_DATETIME)";
    
    public static final String INSERT_NOON_REQUEST= "insert into noon_return_request(CUSTOMER_ORDER_NO,RETURN_REQ_ID,RETURN_LOC_ID,REFUND_AMOUNT,ITEM,ORDER_QTY,LINE_NO,CREATE_DATE_TIME) values "
			+ "(:CUSTOMER_ORDER_NO,:RETURN_REQ_ID,:RETURN_LOC_ID,:REFUND_AMOUNT,:ITEM,:ORDER_QTY,:LINE_NO,sysdate)";
}
