user_name=RMS14
password=retQAtrex123
url=jdbc:oracle:thin:@exvm-qarmsdb01.extrastores.com:1521/RMSQA.extrastores.com
driver=oracle.jdbc.driver.OracleDriver


#user_name=RMS14
#password=kcv123retlv
#url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
#driver=oracle.jdbc.driver.OracleDriver

#QA
webservice_url = http://192.168.41.193:7615/ReceivingPublishingBean/ReceivingPublishingService?WSDL

#PROD
#webservice_url = http://192.168.50.132:7615/ReceivingPublishingBean/ReceivingPublishingService?WSDL