#CHARAN
#RMS DB Details_QA

#oms.db.jdbc-url=jdbc:oracle:thin:@exvm-qarmsdb01.extrastores.com:1521/RMSQA.extrastores.com
#oms.db.user=OMSDEV
#oms.db.password=Logic123

#RMS DB Details_PROD

oms.db.jdbc-url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
oms.db.user=OMSDEV
oms.db.password=Z0b0JYUB

#ORDER_EMAIL
ORDER.NOTIFICATION.FROM.EMAIL=ORDER_FROM_EMAIL
ORDER.NOTIFICATION.ORDER.EMAIL.TEMPLATE=ORDER_EMAIL_TEMPLATE
ORDER.NOTIFICATION.NORMAL=NORMAL
ORDER.NOTIFICATION.REMINDER=REMINDER
ORDER.NOTIFICATION.FROM.PHONE.NUMBER=ORDER_FROM_PHONE_NUMBER
ORDER.NOTIFICATION.ORDER.SMS.TEMPLATE=ORDER_SMS_TEMPLATE
##ORDER.NOTIFICATION.ORDER.SMS.API=https://qa-communication-v1.uk-e1.cloudhub.io/communication/sms
##ORDER.NOTIFICATION.ORDER.EMAIL.API=https://qa-communication-v1.uk-e1.cloudhub.io/communication/email

ORDER.NOTIFICATION.ORDER.SMS.API=https://prod-communication-v1.uk-e1.cloudhub.io/communication/sms
ORDER.NOTIFICATION.ORDER.EMAIL.API=https://prod-communication-v1.uk-e1.cloudhub.io/communication/email


xml.file.loc.store=./xmls/store/
xml.file.loc.inv=./xmls/inventory/
xml.file.loc.trickle=./xmls/trickle/

#TestToken
mytesttoken="test token"


