
package com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1;

import com.logicinfo.oms.beans.OMSUtilCommons;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "FulfillmentOrderReversePickService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", wsdlLocation = "http://licrpap14-extra.logicindia.com:17019/FulfillmentOrderReversePickBean/FulfillmentOrderReversePickService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FFulfillmentOrderReversePickService%2Fv1%7DFulfillmentOrderReversePickService")
public class FulfillmentOrderReversePickService
    extends Service
{

    private final static URL FULFILLMENTORDERREVERSEPICKSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.FulfillmentOrderReversePickService.class.getName());

    static {
        URL url = null;
        try {
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("SIM_FULFILL_REVERSE_PICK");
            URL baseUrl;
            baseUrl = com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1.FulfillmentOrderReversePickService.class.getResource(".");
           // url = new URL(baseUrl, "http://licrpap14-extra.logicindia.com:17019/FulfillmentOrderReversePickBean/FulfillmentOrderReversePickService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FFulfillmentOrderReversePickService%2Fv1%7DFulfillmentOrderReversePickService");
           url = new URL(baseUrl,wsdlUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://licrpap14-extra.logicindia.com:17019/FulfillmentOrderReversePickBean/FulfillmentOrderReversePickService?WSDL#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FFulfillmentOrderReversePickService%2Fv1%7DFulfillmentOrderReversePickService', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        FULFILLMENTORDERREVERSEPICKSERVICE_WSDL_LOCATION = url;
    }

    public FulfillmentOrderReversePickService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FulfillmentOrderReversePickService() {
        super(FULFILLMENTORDERREVERSEPICKSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", "FulfillmentOrderReversePickService"));
    }

    /**
     * 
     * @return
     *     returns FulfillmentOrderReversePickPortType
     */
    @WebEndpoint(name = "FulfillmentOrderReversePickPort")
    public FulfillmentOrderReversePickPortType getFulfillmentOrderReversePickPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", "FulfillmentOrderReversePickPort"), FulfillmentOrderReversePickPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FulfillmentOrderReversePickPortType
     */
    @WebEndpoint(name = "FulfillmentOrderReversePickPort")
    public FulfillmentOrderReversePickPortType getFulfillmentOrderReversePickPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/FulfillmentOrderReversePickService/v1", "FulfillmentOrderReversePickPort"), FulfillmentOrderReversePickPortType.class, features);
    }

}
