package com.oracle.retail.sim.integration.services.fulfillmentorderreversepickservice.v1;
// This source file is generated by Oracle tools.
// Contents may be subject to change.
// For reporting problems, use the following:
// Generated by Oracle JDeveloper 11g Release 2 11.1.2.4.0.6436

public class FulfillmentOrderReversePickPortClient
{
  public static void main(String [] args)
  {
    FulfillmentOrderReversePickService fulfillmentOrderReversePickService = new FulfillmentOrderReversePickService();
    FulfillmentOrderReversePickPortType fulfillmentOrderReversePickPortType = fulfillmentOrderReversePickService.getFulfillmentOrderReversePickPort();
    // Add your code to call the desired methods.
  }
}
