
package com.oracle.retail.sim.integration.services.postransactionservice.v1;


import com.logicinfo.oms.beans.OMSUtilCommons;

import java.net.MalformedURLException;
import java.net.URL;

import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.soap.SOAPException;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "POSTransactionService", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", wsdlLocation = "http://exvm-qaadfapp01.extrastores.com:7511/POSTransactionBean/POSTransactionService?wsdl#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FPOSTransactionService%2Fv1%7DPOSTransactionService")
public class POSTransactionService
    extends Service
{

    private final static URL POSTRANSACTIONSERVICE_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(com.oracle.retail.sim.integration.services.postransactionservice.v1.POSTransactionService.class.getName());

    static {
        URL url = null;
        try
        {
            URL baseUrl;
            
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("POS_TRANSACTION");
            baseUrl = com.oracle.retail.sim.integration.services.postransactionservice.v1.POSTransactionService.class.getResource(".");
            // url = new URL(baseUrl, "http://exvm-qaadfapp01.extrastores.com:7511/POSTransactionBean/POSTransactionService?wsdl#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FPOSTransactionService%2Fv1%7DPOSTransactionService");
            url = new URL(baseUrl,wsdlUrl);
              
        } 
        catch (MalformedURLException e)
        {
            logger.warning("Failed to create URL for the wsdl Location: 'http://exvm-qaadfapp01.extrastores.com:7511/POSTransactionBean/POSTransactionService?wsdl#%7Bhttp%3A%2F%2Fwww.oracle.com%2Fretail%2Fsim%2Fintegration%2Fservices%2FPOSTransactionService%2Fv1%7DPOSTransactionService', retrying as a local file");
            logger.warning(e.getMessage());
        } catch (SOAPException e) {
        }
        POSTRANSACTIONSERVICE_WSDL_LOCATION = url;
    }

    public POSTransactionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public POSTransactionService() {
        super(POSTRANSACTIONSERVICE_WSDL_LOCATION, new QName("http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", "POSTransactionService"));
    }

    /**
     * 
     * @return
     *     returns POSTransactionPortType
     */
    @WebEndpoint(name = "POSTransactionPort")
    public POSTransactionPortType getPOSTransactionPort() {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", "POSTransactionPort"), POSTransactionPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns POSTransactionPortType
     */
    @WebEndpoint(name = "POSTransactionPort")
    public POSTransactionPortType getPOSTransactionPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", "POSTransactionPort"), POSTransactionPortType.class, features);
    }

}
