<?xml version='1.0' encoding='UTF-8'?>
<definitions xmlns:wsaw="http://www.w3.org/2006/05/addressing/wsdl" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.xmlsoap.org/wsdl/" targetNamespace="http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1" name="POSTransactionService">
  <types>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1" schemaLocation="POSTransactionService1.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/services/exception/v1" schemaLocation="POSTransactionService2.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/PosTrnDesc/v1" schemaLocation="POSTransactionService3.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/PosTrnColDesc/v1" schemaLocation="POSTransactionService4.xsd"/>
    </xsd:schema>
    <xsd:schema>
      <xsd:import namespace="http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1" schemaLocation="POSTransactionService5.xsd"/>
    </xsd:schema>
  </types>
  <message name="processPOSTransactions">
    <part name="parameters" element="tns:processPOSTransactions"/>
  </message>
  <message name="processPOSTransactionsResponse">
    <part name="parameters" element="tns:processPOSTransactionsResponse"/>
  </message>
  <message name="IllegalArgumentWSFaultException">
    <part xmlns:ns1="http://www.oracle.com/retail/integration/services/exception/v1" name="fault" element="ns1:IllegalArgumentWSFaultException"/>
  </message>
  <message name="ValidationWSFaultException">
    <part xmlns:ns2="http://www.oracle.com/retail/integration/services/exception/v1" name="fault" element="ns2:ValidationWSFaultException"/>
  </message>
  <message name="IllegalStateWSFaultException">
    <part xmlns:ns3="http://www.oracle.com/retail/integration/services/exception/v1" name="fault" element="ns3:IllegalStateWSFaultException"/>
  </message>
  <message name="ping">
    <part name="parameters" element="tns:ping"/>
  </message>
  <message name="pingResponse">
    <part name="parameters" element="tns:pingResponse"/>
  </message>
  <portType name="POSTransactionPortType">
    <operation name="processPOSTransactions">
      <input wsaw:Action="http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1/POSTransactionPortType/processPOSTransactionsRequest" message="tns:processPOSTransactions"/>
      <output message="tns:processPOSTransactionsResponse"/>
      <fault message="tns:IllegalArgumentWSFaultException" name="IllegalArgumentWSFaultException"/>
      <fault message="tns:ValidationWSFaultException" name="ValidationWSFaultException"/>
      <fault message="tns:IllegalStateWSFaultException" name="IllegalStateWSFaultException"/>
    </operation>
    <operation name="ping">
      <input wsaw:Action="http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1/POSTransactionPortType/pingRequest" message="tns:ping"/>
      <output message="tns:pingResponse"/>
    </operation>
  </portType>
  <binding name="POSTransactionPortBinding" type="tns:POSTransactionPortType">
    <wsaw:UsingAddressing/>
    <soap:binding transport="http://schemas.xmlsoap.org/soap/http" style="document"/>
    <operation name="processPOSTransactions">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
      <fault name="IllegalArgumentWSFaultException">
        <soap:fault name="IllegalArgumentWSFaultException" use="literal"/>
      </fault>
      <fault name="ValidationWSFaultException">
        <soap:fault name="ValidationWSFaultException" use="literal"/>
      </fault>
      <fault name="IllegalStateWSFaultException">
        <soap:fault name="IllegalStateWSFaultException" use="literal"/>
      </fault>
    </operation>
    <operation name="ping">
      <soap:operation soapAction=""/>
      <input>
        <soap:body use="literal"/>
      </input>
      <output>
        <soap:body use="literal"/>
      </output>
    </operation>
  </binding>
  <service name="POSTransactionService">
    <port name="POSTransactionPort" binding="tns:POSTransactionPortBinding">
      <soap:address location="http://exvm-qaadfapp01.extrastores.com:7511/POSTransactionBean/POSTransactionService"/>
    </port>
  </service>
</definitions>