
package com.oracle.retail.sim.integration.services.postransactionservice.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess;
import com.oracle.retail.integration.base.bo.postrncoldesc.v1.PosTrnColDesc;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "POSTransactionPortType", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1")
@XmlSeeAlso({
    com.oracle.retail.integration.base.bo.invocationsuccess.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.postrncoldesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.base.bo.postrndesc.v1.ObjectFactory.class,
    com.oracle.retail.integration.services.exception.v1.ObjectFactory.class,
    com.oracle.retail.sim.integration.services.postransactionservice.v1.ObjectFactory.class
})
public interface POSTransactionPortType {


    /**
     * 
     * @param posTrnColDesc
     * @return
     *     returns com.oracle.retail.integration.base.bo.invocationsuccess.v1.InvocationSuccess
     * @throws IllegalStateWSFaultException
     * @throws ValidationWSFaultException
     * @throws IllegalArgumentWSFaultException
     */
    @WebMethod
    @WebResult(name = "InvocationSuccess", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/InvocationSuccess/v1")
    @RequestWrapper(localName = "processPOSTransactions", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", className = "com.oracle.retail.sim.integration.services.postransactionservice.v1.ProcessPOSTransactions")
    @ResponseWrapper(localName = "processPOSTransactionsResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", className = "com.oracle.retail.sim.integration.services.postransactionservice.v1.ProcessPOSTransactionsResponse")
    public InvocationSuccess processPOSTransactions(
        @WebParam(name = "PosTrnColDesc", targetNamespace = "http://www.oracle.com/retail/integration/base/bo/PosTrnColDesc/v1")
        PosTrnColDesc posTrnColDesc)
        throws IllegalArgumentWSFaultException, IllegalStateWSFaultException, ValidationWSFaultException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "ping", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", className = "com.oracle.retail.sim.integration.services.postransactionservice.v1.Ping")
    @ResponseWrapper(localName = "pingResponse", targetNamespace = "http://www.oracle.com/retail/sim/integration/services/POSTransactionService/v1", className = "com.oracle.retail.sim.integration.services.postransactionservice.v1.PingResponse")
    public String ping(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
