
package retail.siebel.com.soaintegration;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.extra_services.OrderStatus;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IStatus", targetNamespace = "http://www.extra.com/Services/OmsStatus")
@XmlSeeAlso({
    com.extra.services.omsstatus.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    org.datacontract.schemas._2004._07.extra_services.ObjectFactory.class
})
public interface IStatus {


    /**
     * 
     * @param orderStatus
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "UpdateOrderStatus", action = "http://www.extra.com/Services/OmsStatus/IStatus/UpdateOrderStatus")
    @WebResult(name = "UpdateOrderStatusResult", targetNamespace = "http://www.extra.com/Services/OmsStatus")
    @RequestWrapper(localName = "UpdateOrderStatus", targetNamespace = "http://www.extra.com/Services/OmsStatus", className = "com.extra.services.omsstatus.UpdateOrderStatus")
    @ResponseWrapper(localName = "UpdateOrderStatusResponse", targetNamespace = "http://www.extra.com/Services/OmsStatus", className = "com.extra.services.omsstatus.UpdateOrderStatusResponse")
    public String updateOrderStatus(
        @WebParam(name = "orderStatus", targetNamespace = "http://www.extra.com/Services/OmsStatus")
        OrderStatus orderStatus);

}
