
package retail.siebel.com.soaintegration;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import com.logicinfo.oms.beans.OMSUtilCommons;

import javax.xml.soap.SOAPException;


/**
 * This class was generated by the JAX-WS RI.
 * Oracle JAX-WS 2.1.5
 * Generated source version: 2.1
 *
 */
@WebServiceClient(name = "Status", targetNamespace = "http://www.extra.com/Services/OmsStatus", wsdlLocation = "http://192.168.40.89/eXtra.Services.Oms/Status.svc?singleWsdl#%7Bhttp%3A%2F%2Fwww.extra.com%2FServices%2FOmsStatus%7DStatus")
public class Status
    extends Service
{

    private final static URL STATUS_WSDL_LOCATION;
    private final static Logger logger = Logger.getLogger(retail.siebel.com.soaintegration.Status.class.getName());

    static {
        URL url = null;
        try {
            URL baseUrl;
            
            String wsdlUrl = OMSUtilCommons.getWebServiceURL("SOA_CO_STATUS_UPDATE");
            baseUrl = retail.siebel.com.soaintegration.Status.class.getResource(".");
            //url = new URL(baseUrl, "http://192.168.40.89/eXtra.Services.Oms/Status.svc?singleWsdl#%7Bhttp%3A%2F%2Fwww.extra.com%2FServices%2FOmsStatus%7DStatus");
            url = new URL(baseUrl, wsdlUrl);
        } catch (MalformedURLException e) {
            logger.warning("Failed to create URL for the wsdl Location: 'http://192.168.40.89/eXtra.Services.Oms/Status.svc?singleWsdl#%7Bhttp%3A%2F%2Fwww.extra.com%2FServices%2FOmsStatus%7DStatus', retrying as a local file");
            logger.warning(e.getMessage());
        }
        catch (SOAPException e) {
            logger.warning("---------------");
        }
        STATUS_WSDL_LOCATION = url;
    }

    public Status(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Status() {
        super(STATUS_WSDL_LOCATION, new QName("http://www.extra.com/Services/OmsStatus", "Status"));
    }

    /**
     * 
     * @return
     *     returns IStatus
     */
    @WebEndpoint(name = "BasicHttpBinding_IStatus")
    public IStatus getBasicHttpBindingIStatus() {
        return super.getPort(new QName("http://www.extra.com/Services/OmsStatus", "BasicHttpBinding_IStatus"), IStatus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStatus
     */
    @WebEndpoint(name = "BasicHttpBinding_IStatus")
    public IStatus getBasicHttpBindingIStatus(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.extra.com/Services/OmsStatus", "BasicHttpBinding_IStatus"), IStatus.class, features);
    }

    /**
     * 
     * @return
     *     returns IStatus
     */
    @WebEndpoint(name = "NetTcpBinding_IStatus")
    public IStatus getNetTcpBindingIStatus() {
        return super.getPort(new QName("http://www.extra.com/Services/OmsStatus", "NetTcpBinding_IStatus"), IStatus.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IStatus
     */
    @WebEndpoint(name = "NetTcpBinding_IStatus")
    public IStatus getNetTcpBindingIStatus(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.extra.com/Services/OmsStatus", "NetTcpBinding_IStatus"), IStatus.class, features);
    }

}
