<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:tns="http://www.oracle.com/retail/integration/base/bo/StrFordDesc/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0" targetNamespace="http://www.oracle.com/retail/integration/base/bo/StrFordDesc/v1">
  <xs:element name="StrFordCust">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="customer_id" type="xs:string"/>
        <xs:element name="delivery_first_name" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_phonetic_first_name" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_last_name" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_phonetic_last_name" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_preferred_name" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_company_name" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_address1" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_address2" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_address3" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_county" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_city" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_state" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_postal_code" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_country" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_phone" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_first_name" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_phonetic_first_name" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_last_name" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_phonetic_last_name" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_preferred_name" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_company_name" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_address1" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_address2" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_address3" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_county" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_city" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_state" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_postal_code" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_country" type="xs:string" minOccurs="0"/>
        <xs:element name="billing_phone" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="StrFordDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="int_fulfillment_order_id" type="xs:long"/>
        <xs:element name="ext_fulfillment_order_id" type="xs:string"/>
        <xs:element name="customer_order_id" type="xs:string"/>
        <xs:element name="order_type" type="tns:str_ford_type"/>
        <xs:element name="status" type="tns:str_ford_status"/>
        <xs:element name="create_date" type="xs:dateTime"/>
        <xs:element name="release_date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="delivery_date" type="xs:dateTime" minOccurs="0"/>
        <xs:element name="delivery_type" type="tns:str_ford_delivery_type"/>
        <xs:element name="delivery_carrier_code" type="xs:string" minOccurs="0"/>
        <xs:element name="delivery_service_code" type="xs:string" minOccurs="0"/>
        <xs:element name="allow_partial_delivery" type="xs:boolean"/>
        <xs:element name="comments" type="xs:string" minOccurs="0"/>
        <xs:element ref="tns:StrFordCust" minOccurs="0"/>
        <xs:element ref="tns:StrFordItm" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="StrFordItm">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="line_id" type="xs:long"/>
        <xs:element name="item_id" type="xs:string"/>
        <xs:element name="description" type="xs:string" minOccurs="0"/>
        <xs:element name="substitute_item_id" type="xs:string" minOccurs="0"/>
        <xs:element name="preferred_uom" type="xs:string"/>
        <xs:element name="standard_uom" type="xs:string"/>
        <xs:element name="order_qty" type="xs:decimal"/>
        <xs:element name="picked_qty" type="xs:decimal"/>
        <xs:element name="delivered_qty" type="xs:decimal"/>
        <xs:element name="canceled_qty" type="xs:decimal"/>
        <xs:element name="remaining_qty" type="xs:decimal"/>
        <xs:element name="reserved_qty" type="xs:decimal"/>
        <xs:element name="allow_substitution" type="xs:boolean"/>
        <xs:element name="create_date" type="xs:dateTime"/>
        <xs:element name="last_update_date" type="xs:dateTime"/>
        <xs:element name="comments" type="xs:string" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="str_ford_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="LAYAWAY"/>
      <xs:enumeration value="PICKUP_AND_DELIVERY"/>
      <xs:enumeration value="CUSTOMER_ORDER"/>
      <xs:enumeration value="PENDING_PURCHASE"/>
      <xs:enumeration value="SPECIAL_ORDER"/>
      <xs:enumeration value="WEB_ORDER"/>
      <xs:enumeration value="UNKNOWN"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="str_ford_status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NEW"/>
      <xs:enumeration value="IN_PROGRESS"/>
      <xs:enumeration value="COMPLETED"/>
      <xs:enumeration value="CANCELED"/>
      <xs:enumeration value="UNKNOWN"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="str_ford_delivery_type">
    <xs:restriction base="xs:string">
      <xs:enumeration value="PICKUP"/>
      <xs:enumeration value="SHIPMENT"/>
      <xs:enumeration value="UNKNOWN"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>