<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:tns="http://www.oracle.com/retail/integration/base/bo/StrAdjModVo/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0" targetNamespace="http://www.oracle.com/retail/integration/base/bo/StrAdjModVo/v1">
  <xs:element name="StrAdjItmMod">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="line_id" type="xs:long" minOccurs="0"/>
        <xs:element name="item_id" type="xs:string"/>
        <xs:element name="reason_id" type="xs:long"/>
        <xs:element name="quantity" type="xs:decimal"/>
        <xs:element name="case_size" type="xs:decimal"/>
        <xs:element name="added_uin_col" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="removed_uin_col" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="StrAdjModVo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="adjustment_id" type="xs:long" minOccurs="0"/>
        <xs:element name="store_id" type="xs:long"/>
        <xs:element name="reference_id" type="xs:long" minOccurs="0"/>
        <xs:element name="template_id" type="xs:long" minOccurs="0"/>
        <xs:element name="comments" type="xs:string" minOccurs="0"/>
        <xs:element ref="tns:StrAdjItmMod" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="removed_line_id_col" type="xs:long" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>