<?xml version='1.0' encoding='UTF-8'?>
<xs:schema xmlns:tns="http://www.oracle.com/retail/integration/base/bo/StrAdjTpHdDesc/v1" xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" version="1.0" targetNamespace="http://www.oracle.com/retail/integration/base/bo/StrAdjTpHdDesc/v1">
  <xs:element name="StrAdjTpHdDesc">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="template_id" type="xs:long"/>
        <xs:element name="description" type="xs:string"/>
        <xs:element name="status" type="tns:str_adj_status"/>
        <xs:element name="status_date" type="xs:dateTime"/>
        <xs:element name="create_user_name" type="xs:string"/>
        <xs:element name="item_count" type="xs:long"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="str_adj_status">
    <xs:restriction base="xs:string">
      <xs:enumeration value="IN_PROGRESS"/>
      <xs:enumeration value="COMPLETED"/>
      <xs:enumeration value="CANCELED"/>
      <xs:enumeration value="UNKNOWN"/>
      <xs:enumeration value="NO_VALUE"/>
    </xs:restriction>
  </xs:simpleType>
</xs:schema>