package oracle.retail.sim.common.integration;

public enum RibSimMessageType implements SimMessageType {
  ASNIN_CRE("ASNInCre", RibSimMessageFamily.ASNIN),
  ASNIN_DEL("ASNInDel", RibSimMessageFamily.ASNIN),
  ASNIN_MOD("ASNInMod", RibSimMessageFamily.ASNIN),
  ASNOUT_CRE("ASNOutCre", RibSimMessageFamily.ASNOUT),
  CLASS_CRE("ClassCre", RibSimMessageFamily.MERCHHIER),
  CLASS_MOD("ClassMod", RibSimMessageFamily.MERCHHIER),
  CLASS_DEL("ClassDel", RibSimMessageFamily.MERCHHIER),
  CLRPRCCHG_CRE("ClrPrcChgCre", RibSimMessageFamily.CLRPRCCHG),
  CLRPRCCHG_DEL("ClrPrcChgDel", RibSimMessageFamily.CLRPRCCHG),
  CLRPRCCHG_MOD("ClrPrcChgMod", RibSimMessageFamily.CLRPRCCHG),
  DLVYSLT_CRE("DlvySltCre", RibSimMessageFamily.DLVYSLT),
  DLVYSLT_DEL("DlvySltDel", RibSimMessageFamily.DLVYSLT),
  DLVYSLT_MOD("DlvySltMod", RibSimMessageFamily.DLVYSLT),
  DEPT_CRE("DeptCre", RibSimMessageFamily.MERCHHIER),
  DEPT_MOD("DeptMod", RibSimMessageFamily.MERCHHIER),
  DEPT_DEL("DeptDel", RibSimMessageFamily.MERCHHIER),
  DIFF_CRE("DiffCre", RibSimMessageFamily.DIFFS),
  DIFF_DEL("DiffDel", RibSimMessageFamily.DIFFS),
  DIFF_MOD("DiffMod", RibSimMessageFamily.DIFFS),
  DIFFTYPE_CRE("DiffTypeCre", RibSimMessageFamily.SEEDDATA),
  DIFFTYPE_DEL("DiffTypeDel", RibSimMessageFamily.SEEDDATA),
  DIFFTYPE_MOD("DiffTypeMod", RibSimMessageFamily.SEEDDATA),
  DSDRECEIPT_CRE("DSDReceiptCre", RibSimMessageFamily.DSDRECEIPT),
  DSDRECEIPT_MOD("DSDReceiptMod", RibSimMessageFamily.DSDRECEIPT),
  FULFILORD_CRE("FulfilOrdStDlvCre", RibSimMessageFamily.FULFILORD),
  FULFILORD_DEL("FulfilOrdReqDel", RibSimMessageFamily.FULFILORD),
  FULFILORDCFM_CRE("FulfilOrdCfmCre", RibSimMessageFamily.FULFILORDCFM),
  FULFILORDCFMCNC_CRE("FulfilOrdCfmCncCre", RibSimMessageFamily.FULFILORDCFMCNC),
  INVADJUST_CRE("InvAdjustCre", RibSimMessageFamily.INVADJUST),
  INVREQ_CRE("InvReqCre", RibSimMessageFamily.INVREQ),
  ITEMBOM_CRE("ItemBOMCre", RibSimMessageFamily.ITEMS),
  ITEMBOM_DEL("ItemBOMDel", RibSimMessageFamily.ITEMS),
  ITEMBOM_MOD("ItemBOMMod", RibSimMessageFamily.ITEMS),
  ITEM_CRE("ItemCre", RibSimMessageFamily.ITEMS),
  ITEM_DEL("ItemDel", RibSimMessageFamily.ITEMS),
  ITEMHDR_MOD("ItemHdrMod", RibSimMessageFamily.ITEMS),
  ITEMTCKT_CRE("ItemTcktCre", RibSimMessageFamily.ITEMS),
  ITEMTCKT_MOD("ItemTcktMod", RibSimMessageFamily.ITEMS),
  ITEMTCKT_DEL("ItemTcktDel", RibSimMessageFamily.ITEMS),
  ITEMSUPCTY_CRE("ItemSupCtyCre", RibSimMessageFamily.ITEMS),
  ITEMSUPCTY_DEL("ItemSupCtyDel", RibSimMessageFamily.ITEMS),
  ITEMSUPCTY_MOD("ItemSupCtyMod", RibSimMessageFamily.ITEMS),
  ITEMSUPCTYMFR_CRE("ISCMfrCre", RibSimMessageFamily.ITEMS),
  ITEMSUPCTYMFR_DEL("ISCMfrDel", RibSimMessageFamily.ITEMS),
  ITEMSUPCTYMFR_MOD("ISCMfrMod", RibSimMessageFamily.ITEMS),
  ITEMSUPCTYDIM_CRE("ISCDimCre", RibSimMessageFamily.ITEMS),
  ITEMSUPCTYDIM_MOD("ISCDimMod", RibSimMessageFamily.ITEMS),
  ITEMSUPCTYDIM_DEL("ISCDimDel", RibSimMessageFamily.ITEMS),
  ITEMIMAGE_CRE("ItemImageCre", RibSimMessageFamily.ITEMS),
  ITEMIMAGE_MOD("ItemImageMod", RibSimMessageFamily.ITEMS),
  ITEMIMAGE_DEL("ItemImageDel", RibSimMessageFamily.ITEMS),
  ITEMSUP_CRE("ItemSupCre", RibSimMessageFamily.ITEMS),
  ITEMSUP_DEL("ItemSupDel", RibSimMessageFamily.ITEMS),
  ITEMSUP_MOD("ItemSupMod", RibSimMessageFamily.ITEMS),
  ITEMUPC_CRE("ItemUPCCre", RibSimMessageFamily.ITEMS),
  ITEMUPC_DEL("ItemUPCDel", RibSimMessageFamily.ITEMS),
  ITEMUPC_MOD("ItemUPCMod", RibSimMessageFamily.ITEMS),
  ITEMLOC_CRE("ItemLocCre", RibSimMessageFamily.ITEMLOC),
  ITEMLOC_MOD("ItemLocMod", RibSimMessageFamily.ITEMLOC),
  ITEMLOC_DEL("ItemLocDel", RibSimMessageFamily.ITEMLOC),
  ITEMLOCREPL_MOD("ItemLocReplMod", RibSimMessageFamily.ITEMLOC),
  ITEMUDALOV_CRE("ItemUDALOVCre", RibSimMessageFamily.ITEMS),
  ITEMUDALOV_MOD("ItemUDALOVMod", RibSimMessageFamily.ITEMS),
  ITEMUDALOV_DEL("ItemUDALOVDel", RibSimMessageFamily.ITEMS),
  ITEMUDAFF_CRE("ItemUDAFFCre", RibSimMessageFamily.ITEMS),
  ITEMUDAFF_MOD("ItemUDAFFMod", RibSimMessageFamily.ITEMS),
  ITEMUDAFF_DEL("ItemUDAFFDel", RibSimMessageFamily.ITEMS),
  ITEMUDADATE_CRE("ItemUDADateCre", RibSimMessageFamily.ITEMS),
  ITEMUDADATE_MOD("ItemUDADateMod", RibSimMessageFamily.ITEMS),
  ITEMUDADATE_DEL("ItemUDADateDel", RibSimMessageFamily.ITEMS),
  MULTIBUYPROMO_CRE("MultiBuyPromoCre", RibSimMessageFamily.PRMPRCCHG),
  MULTIBUYPROMO_DEL("MultiBuyPromoDel", RibSimMessageFamily.PRMPRCCHG),
  MULTIBUYPROMO_MOD("MultiBuyPromoMod", RibSimMessageFamily.PRMPRCCHG),
  PRMCNLITEMLOC_CRE("PrmCnlItemLocCre", RibSimMessageFamily.PRMPRCCHG),
  PARTNER_CRE("PartnerCre", RibSimMessageFamily.PARTNER),
  PARTNER_DEL("PartnerDel", RibSimMessageFamily.PARTNER),
  PARTNER_MOD("PartnerMod", RibSimMessageFamily.PARTNER),
  PARTNERDTL_CRE("PartnerDtlCre", RibSimMessageFamily.PARTNER),
  PARTNERDTL_DEL("PartnerDtlDel", RibSimMessageFamily.PARTNER),
  PARTNERDTL_MOD("PartnerDtlMod", RibSimMessageFamily.PARTNER),
  PO_CRE("POCre", RibSimMessageFamily.ORDER),
  PO_DEL("PODel", RibSimMessageFamily.ORDER),
  PODTL_CRE("PODtlCre", RibSimMessageFamily.ORDER),
  PODTL_DEL("PODtlDel", RibSimMessageFamily.ORDER),
  PODTL_MOD("PODtlMod", RibSimMessageFamily.ORDER),
  POHDR_MOD("POHdrMod", RibSimMessageFamily.ORDER),
  RCVUNITADJ_CRE("RcvUnitAdjCre", RibSimMessageFamily.RCVUNITADJ),
  RCVUNITADJ_MOD("RcvUnitAdjMod", RibSimMessageFamily.RCVUNITADJ),
  RECEIPT_CRE("ReceiptCre", RibSimMessageFamily.RECEIVING),
  RECEIPT_ORD_CRE("ReceiptOrdCre", RibSimMessageFamily.RECEIVING),
  REGPRCCHG_CRE("RegPrcChgCre", RibSimMessageFamily.REGPRCCHG),
  REGPRCCHG_DEL("RegPrcChgDel", RibSimMessageFamily.REGPRCCHG),
  REGPRCCHG_MOD("RegPrcChgMod", RibSimMessageFamily.REGPRCCHG),
  RELITEM_CRE("RelItemHeadCre", RibSimMessageFamily.ITEMS),
  RELITEM_MOD("RelItemHeadMod", RibSimMessageFamily.ITEMS),
  RELITEM_DEL("RelItemHeadDel", RibSimMessageFamily.ITEMS),
  RELITEMDTL_CRE("RelItemDetCre", RibSimMessageFamily.ITEMS),
  RELITEMDTL_DEL("RelItemDetDel", RibSimMessageFamily.ITEMS),
  RELITEMDTL_MOD("RelItemDetMod", RibSimMessageFamily.ITEMS),
  RTV_CRE("RTVCre", RibSimMessageFamily.RTV),
  RTVREQ_CRE("RTVReqCre", RibSimMessageFamily.RTVREQ),
  RTVREQ_MOD("RTVReqMod", RibSimMessageFamily.RTVREQ),
  RTVREQ_DEL("RTVReqDel", RibSimMessageFamily.RTVREQ),
  RTVREQDTL_CRE("RTVReqDtlCre", RibSimMessageFamily.RTVREQ),
  RTVREQDTL_DEL("RTVReqDtlDel", RibSimMessageFamily.RTVREQ),
  RTVREQDTL_MOD("RTVReqDtlMod", RibSimMessageFamily.RTVREQ),
  SHIPINFO_CRE("ShipInfoCre", RibSimMessageFamily.SHIPINFO),
  SO_CRE("SOCre", RibSimMessageFamily.STOCKORDER),
  SODTL_CRE("SODtlCre", RibSimMessageFamily.STOCKORDER),
  SODTL_DEL("SODtlDel", RibSimMessageFamily.STOCKORDER),
  SODTL_MOD("SODtlMod", RibSimMessageFamily.STOCKORDER),
  SOHDR_DEL("SOHdrDel", RibSimMessageFamily.STOCKORDER),
  SOHDR_MOD("SOHdrMod", RibSimMessageFamily.STOCKORDER),
  SOSTATUS_CRE("SOStatusCre", RibSimMessageFamily.SOSTATUS),
  STKCOUNTSCH_CRE("StkCountSchCre", RibSimMessageFamily.STKCOUNTSCH),
  STKCOUNTSCH_MOD("StkCountSchMod", RibSimMessageFamily.STKCOUNTSCH),
  STKCOUNTSCH_DEL("StkCountSchDel", RibSimMessageFamily.STKCOUNTSCH),
  STORE_CRE("StoreCre", RibSimMessageFamily.STORES),
  STORE_DEL("StoreDel", RibSimMessageFamily.STORES),
  STORE_MOD("StoreMod", RibSimMessageFamily.STORES),
  STOREDTL_CRE("StoreDtlCre", RibSimMessageFamily.STORES),
  STOREDTL_MOD("StoreDtlMod", RibSimMessageFamily.STORES),
  STOREDTL_DEL("StoreDtlDel", RibSimMessageFamily.STORES),
  SUBCLASS_CRE("SubclassCre", RibSimMessageFamily.MERCHHIER),
  SUBCLASS_MOD("SubclassMod", RibSimMessageFamily.MERCHHIER),
  SUBCLASS_DEL("SubclassDel", RibSimMessageFamily.MERCHHIER),
  UDA_CRE("UDAHdrCre", RibSimMessageFamily.UDAS),
  UDA_MOD("UDAHdrMod", RibSimMessageFamily.UDAS),
  UDA_DEL("UDAHdrDel", RibSimMessageFamily.UDAS),
  UDA_VALUE_CRE("UDAValCre", RibSimMessageFamily.UDAS),
  UDA_VALUE_MOD("UDAValMod", RibSimMessageFamily.UDAS),
  UDA_VALUE_DEL("UDAValDel", RibSimMessageFamily.UDAS),
  VENDORADDR_CRE("VendorAddrCre", RibSimMessageFamily.VENDOR),
  VENDORADDR_DEL("VendorAddrDel", RibSimMessageFamily.VENDOR),
  VENDORADDR_MOD("VendorAddrMod", RibSimMessageFamily.VENDOR),
  VENDOR_CRE("VendorCre", RibSimMessageFamily.VENDOR),
  VENDOR_DEL("VendorDel", RibSimMessageFamily.VENDOR),
  VENDORHDR_MOD("VendorHdrMod", RibSimMessageFamily.VENDOR),
  VENDOROU_CRE("VendorOUCre", RibSimMessageFamily.VENDOR),
  VENDOROU_DEL("VendorOUDel", RibSimMessageFamily.VENDOR),
  WH_CRE("WHCre", RibSimMessageFamily.WH),
  WH_DEL("WHDel", RibSimMessageFamily.WH),
  WH_MOD("WHMod", RibSimMessageFamily.WH);
  
  private final String code;
  
  private final SimMessageFamily family;
  
  RibSimMessageType(String paramString1, SimMessageFamily paramSimMessageFamily) {
    this.code = paramString1;
    this.family = paramSimMessageFamily;
  }
  
  public String getCode() {
    return this.code;
  }
  
  public SimMessageFamily getFamily() {
    return this.family;
  }
  
  public String toString() {
    return this.code;
  }
}


/* Location:              C:\Users\aibrahim\eclipse-workspace\sim-client\lib\sim-common.jar!\oracle\retail\sim\common\integration\RibSimMessageType.class
 * Java compiler version: 7 (51.0)
 * JD-Core Version:       1.1.3
 */