db.jndi.oms=jdbc/oms
db.jndi.rms=jdbc/rms

#rms.oralce.base.api.url=http://192.168.41.194:7117/FulfillOrderBean/FulfillOrderService
#sim.oralce.base.api.url=http://exvm-qaadfapp01.extrastores.com:7511/StoreFulfillmentOrderBean/StoreFulfillmentOrderService
#jwt.secret=eXtrastokensecret
#carrera.api.url=http://192.168.41.193:7701/CarreraTransferCreation
#rms.datasource.jdbc-url=jdbc:oracle:thin:@192.168.41.187:1521/RMSQA.extrastores.com
#rms.datasource.username=rms14
#rms.datasource.password=retQAtrex123

#mule.addr.api.url = https://dev-address-management-api-v1.uk-e1.cloudhub.io
#mule.addr.api.username = b2cd771d293f40638c2977f21e440375
#mule.addr.api.password = 21551a5c7fE54A51b297422611113d80

#
mule.addr.api.url = https://prod-address-management-api-v1.uk-e1.cloudhub.io
mule.addr.api.username = fc1c8130bbac41ab9a5fa730a5976473
mule.addr.api.password = 4Fd0C1a75d49452Ea040a815791A2FA6

#

rms.oralce.base.api.url=http://prodrms-app1.extrastores.com:7117/FulfillOrderBean/FulfillOrderService
sim.oralce.base.api.url=http://prodadf-app2.extrastores.com:7511/StoreFulfillmentOrderBean/StoreFulfillmentOrderService
jwt.secret=eXtrastokensecret
carrera.api.url=http://192.168.50.132:7701/CarreraTransferCreation
rms.datasource.jdbc-url=jdbc:oracle:thin:@192.168.50.111:1521/RMSPRD.extrastores.com
rms.datasource.username=rms14
rms.datasource.password=kcv123retlv