SELECT I.ITEM, I.LINE_NO, I.SHIP_CLASSIFICATION, I.QTY_ORDERED_SUOM, I.CUM_QTY_DELIVERED, I.QTY_CANCELLED, I.QTY_RETURNED,
    F.SOURCE_LOC,F.SOURCE_LOC_TYPE,
    CASE WHEN F.SOURCE_LOC_TYPE = 'ST' THEN (SELECT STORE_NAME3 FROM STORE S WHERE S.STORE = F.SOURCE_LOC)
        WHEN F.SOURCE_LOC_TYPE = 'WH' THEN (SELECT WH_NAME FROM WH W WHERE W.WH = F.SOURCE_LOC)END , 
        F.FULFILL_LOC,
    CASE WHEN F.FULFILL_LOC_TYPE = 'S' THEN (SELECT STORE_NAME3 FROM STORE S WHERE S.STORE = F.FULFILL_LOC)
        WHEN F.FULFILL_LOC_TYPE = 'V' THEN 'Virtual Ware House' END, F.FULFILL_LOC_TYPE
FROM OMS_CUST_ORD_ITEM I 
    LEFT OUTER JOIN OMS_CO_FULFILL_DETAIL F ON F.ITEM = I.ITEM AND F.LINE_NO = I.LINE_NO AND F.OMS_CUST_ORD_NO = I.OMS_CUST_ORD_NO;