package oracle.retail.sim.client.screen.fulfillmentorderpick;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import oracle.retail.sim.client.core.ClientWrapperFactory;
import oracle.retail.sim.client.core.SimScreenModel;
import oracle.retail.sim.client.screen.reportformat.SimClientPrintUtility;
import oracle.retail.sim.common.business.BOFactory;
import oracle.retail.sim.common.business.BusinessException;
import oracle.retail.sim.common.configutil.StoreConfigKeys;
import oracle.retail.sim.common.core.locale.StringHelper;
import oracle.retail.sim.common.fulfillmentorder.FulfillmentOrderMessageText;
import oracle.retail.sim.common.fulfillmentorderpick.FulfillmentOrderBin;
import oracle.retail.sim.common.fulfillmentorderpick.FulfillmentOrderPick;
import oracle.retail.sim.common.fulfillmentorderpick.FulfillmentOrderPickLineItem;
import oracle.retail.sim.common.fulfillmentorderpick.FulfillmentOrderPickStatus;
import oracle.retail.sim.common.fulfillmentorderpick.GenerateBinsOptions;
import oracle.retail.sim.common.report.ReportFormat;
import oracle.retail.sim.common.report.ReportRequest;
import oracle.retail.sim.common.report.RetailStoreFormatPrinter;
import oracle.retail.sim.common.security.PermissionKey;
import oracle.retail.sim.service.core.ClientServiceFactory;

/********************************************************************************************************
 * Bin Detail Dialog Model
 * <p>
 * Copyright 2004, 2013, Oracle. All rights reserved.
 *******************************************************************************************************/
public class BinDetailDialogModel extends SimScreenModel {

    private FulfillmentOrderPick pick;

    /**
     * Sets the current Fulfillment Order Pick
     * @param pick The current Fulfillment Order Pick.
     */
    public void setPick(FulfillmentOrderPick pick) {
        this.pick = pick;
    }

    /**
     * Returns the current Fulfillment Order Pick.
     * @return The current Fulfillment Order Pick.
     */
    public FulfillmentOrderPick getPick() {
        return pick;
    }

    /**
     * Returns whether the Bin Ids on Fulfillment Order Picks are generated by SIM
     * @return True if the Bin Ids are generated by SIM, otherwise false.
     */
    public boolean isBinsSystemGenerated() {
        return GenerateBinsOptions.SYSTEM == GenerateBinsOptions.toValue(getStoreString(StoreConfigKeys.GENERATE_BINS));
    }

    /**
     * Returns whether the Bin Ids on Fulfillment Order Picks are generated by SIM
     * @return True if the Bin Ids are generated by SIM, otherwise false.
     */
    public boolean isBinsManuallyEntered() {
        return GenerateBinsOptions.MANUAL == GenerateBinsOptions.toValue(getStoreString(StoreConfigKeys.GENERATE_BINS));
    }

    /**
     * Returns true if the Pick has all the required number of Bins captured.
     * @return True if the Pick has all the required number of Bins captured, otherwise false.
     */
    public boolean isBinsCaptured() {
        for (FulfillmentOrderPickLineItem lineItem : pick.getLineItems()) {
            if (lineItem.getBin() == null || StringHelper.isNullOrEmpty(lineItem.getBin().getBinId())) {
                return false;
            }
        }
        return true;
    }

    /**
     * Returns whether the Bin dialog is in a view only state.
     * @return True if the Bin dialog is in a view only state, otherwise false.
     */
    public boolean isViewOnly() {
        if (!hasPermission(PermissionKey.PC_EDIT_CUSTOMER_ORDER_PICK) && !pick.isNew()) {
            return true;
        }
        if (isBinsSystemGenerated()) {
            return true;
        }
        if (pick.getStatus() == FulfillmentOrderPickStatus.CANCELED || pick.getStatus() == FulfillmentOrderPickStatus.COMPLETED) {
            return true;
        }
        return false;
    }

    /**
     * Returns all Fulfillment Order Bins on the current Pick mapped to their respective Fulfillment Order Id.
     * @return A Map with Fulfillment Order ID as a key and the Fulfillment Order Bin for that order as the value.
     */
    public Map<Long, FulfillmentOrderBinWrapper> getBinMap(boolean isEditable) {
        Map<Long, FulfillmentOrderBinWrapper> binMap = new HashMap<>(getNumberOfBins());
        for (FulfillmentOrderPickLineItem lineItem : pick.getLineItems()) {
            FulfillmentOrderBin bin = BOFactory.createFulfillmentOrderBin();
            if (lineItem.getBin() != null) {
                bin.doSetBinId(lineItem.getBin().getBinId());
                bin.doSetId(lineItem.getBin().getId());
            }
            bin.doSetFulfillmentOrderId(lineItem.getFulfillmentOrderId());
            bin.doSetFulfillmentOrderPickId(pick.getId());
            FulfillmentOrderBinWrapper wrapper = ClientWrapperFactory.createFulfillmentOrderBinWrapper(bin, isEditable);
            binMap.put(lineItem.getFulfillmentOrderId(), wrapper);
        }
        return binMap;
    }

    /**
     * Returns the number of Bins required to be populated.
     * @return The total number of Bins required to be populated.
     */
    public int getNumberOfBins() {
        List<Long> fulfillmentOrderIds = new ArrayList<>();
        for (FulfillmentOrderPickLineItem lineItem : pick.getLineItems()) {
            if (!fulfillmentOrderIds.contains(lineItem.getFulfillmentOrderId())) {
                fulfillmentOrderIds.add(lineItem.getFulfillmentOrderId());
            }
        }
        return fulfillmentOrderIds.size();
    }

    public void saveBins(List<FulfillmentOrderBinWrapper> wrappers) throws Exception {
        List<FulfillmentOrderBin> bins = new ArrayList<>();

        // Check for null entries
        for (FulfillmentOrderBinWrapper wrapper : wrappers) {
            if (StringHelper.isNullOrEmpty(wrapper.getBinId())) {
                throw new BusinessException(FulfillmentOrderMessageText.INVALID_BINS_QUANTITY, getNumberOfBins());
            }
            bins.add(wrapper.getBin());
        }

        // Check for duplicate entries
        for (FulfillmentOrderBinWrapper wrapper : wrappers) {
            for (FulfillmentOrderBinWrapper otherWrapper : wrappers) {
                if (wrapper.getBinId().equals(otherWrapper.getBinId()) && wrapper.getBin() != otherWrapper.getBin()) {
                    throw new BusinessException(FulfillmentOrderMessageText.DUPLICATE_BIN_ID, wrapper.getBinId());
                }
            }
        }

        // Now update them in the DB
        bins = ClientServiceFactory.getFulfillmentOrderPickServices().updateFulfillmentOrderBins(bins);

        // Now map them to the Pick
        for (FulfillmentOrderPickLineItem lineItem : pick.getLineItems()) {
            for (FulfillmentOrderBin bin : bins) {
                if (bin.getFulfillmentOrderId().equals(lineItem.getFulfillmentOrderId())) {
                    lineItem.doSetBin(bin);
                    break;
                }
            }
        }
    }

    public void printLabels(List<FulfillmentOrderBinWrapper> wrappers) throws Exception {
        Long storeId = getStoreId();
        List<RetailStoreFormatPrinter> formatPrinters = SimClientPrintUtility.selectFormatPrinter(storeId, ReportFormat.CUSTOMER_ORDER_BIN_LABEL);
        if (formatPrinters != null && formatPrinters.size() > 0) {
            List<ReportRequest> requests = new ArrayList<ReportRequest>();
            for (FulfillmentOrderBinWrapper wrapper : wrappers) {
                requests.add(BOFactory.createFulfillmentOrderBinReportRequest(wrapper.getBinId(), wrapper.getFulfillmentOrderId()));
            }
            SimClientPrintUtility.printReportRequests(requests, formatPrinters, FulfillmentOrderMessageText.BIN_LABELS_PRINTED);
        }
    }
}
