package extra.retail.sim.common.report;

import oracle.retail.sim.common.core.SimEnum;

/**
 * ExtraReportFormat.java aibrahim 2024
 */
public enum ExtraReportFormat implements SimEnum<String> {

	AGSN("REPORT_FORMAT_AGSN"),
	CUSTOMER_ORDER("REPORT_FORMAT_CUSTOMER_ORDER"),
	CUSTOMER_ORDER_BIN_LABEL("REPORT_FORMAT_CUSTOMER_ORDER_BIN_LABEL"),
	CUSTOMER_ORDER_DELIVERY("REPORT_FORMAT_CUSTOMER_ORDER_DELIVERY"),
	CUSTOMER_ORDER_DELIVERY_BOL("REPORT_FORMAT_CUSTOMER_ORDER_DELIVERY_BOL"),
	CUSTOMER_ORDER_PICK("REPORT_FORMAT_CUSTOMER_ORDER_PICK"),
	CUSTOMER_ORDER_REVERSE_PICK("REPORT_FORMAT_CUSTOMER_ORDER_REVERSE_PICK"),
	CUSTOMER_ORDER_PICK_DISCREPANCY("REPORT_FORMAT_CUSTOMER_ORDER_PICK_DISCREPANCY"),
	DIRECT_DELIVERY("REPORT_FORMAT_DIRECTDELIVERY"),
	DIRECT_DELIVERY_DISCREPANT_ITEMS("REPORT_FORMAT_DIRECT_DELIVERY_DISCREPANT_ITEMS"),
	INVENTORY_ADJUSTMENT("REPORT_FORMAT_INVENTORY_ADJUSTMENT"),
	ITEM_DETAIL("REPORT_FORMAT_ITEMDETAIL"),
	ITEM_REQUEST("REPORT_FORMAT_ITEMREQUEST"),
	ITEM_BASKET("REPORT_FORMAT_ITEM_BASKET"),
	ITEM_TICKET("REPORT_FORMAT_ITEM_TICKET"),
	QR_CODE_TICKET("REPORT_FORMAT_QR_CODE_TICKET"),
	PRE_SHIPMENT("PRE_SHIPMENT"),
	MANIFEST("MANIFEST"),
	SHELF_REPLENISHMENT("REPORT_FORMAT_SHELF_REPLENISHMENT"),
	SHELF_LABEL("REPORT_FORMAT_SHELF_LABEL"),
	QR_CODE_LABEL("REPORT_FORMAT_QR_CODE_LABEL"),
	STOCK_COUNT_ALL_ITEM("REPORT_FORMAT_STOCKCOUNTALLLOC"),
	STOCK_COUNT_EXPORT("REPORT_FORMAT_STOCKCOUNT_EXPORT"),
	STOCK_COUNT("REPORT_FORMAT_STOCKCOUNT"),
	STOCK_COUNT_NOF("REPORT_FORMAT_STOCKCOUNT_NOF"),
	STORE_ORDER("REPORT_FORMAT_STOREORDER"),
	STOCK_RETURN("REPORT_FORMAT_RETURN"),
	STOCK_RETURN_BOL("REPORT_FORMAT_RETURN_BOL"),
	TRANSFER("REPORT_FORMAT_TRANSFER"),
	TRANSFER_BOL("REPORT_FORMAT_TRANSFER_BOL"),
	WAREHOUSE_DELIVERY("REPORT_FORMAT_WAREHOUSEDELIVERY"),
	ODD_HANDOVER_TO_COURIER("REPORT_FORMAT_ODD_HANDOVER_TO_COURIER");

	private final String code;

	ExtraReportFormat(String code) {
		this.code = code;
	}

	public String getCode() {
		return this.code;
	}

	public String toString() {
		return this.code;
	}

	public static ExtraReportFormat toValue(String code) {
		if (code != null) {
			for (ExtraReportFormat reportFormat : values()) {
				if (reportFormat.code.equals(code)) {
					return reportFormat;
				}
			}
		}
		return null;
	}
}
