db.username=OMSDEV
db.password=Logic123
db.url=jdbc:oracle:thin:@192.168.41.187:1521/RMSQA.extrastores.com
db.driver=oracle.jdbc.driver.OracleDriver

oms.cancal.api.url = http://192.168.41.193:7701/omscancellation

lock.filename = global.lock

feign.client.config.cancelService.loggerLevel = FULL
logging.level.com.extra.oms.service.OrderCancelService = debug