<?xml version='1.0' encoding='UTF-8'?>
<xs:schema version="1.0" targetNamespace="http://com.logicinfo.oms/model/" xmlns:tns="http://com.logicinfo.oms/model/"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="coPaymentConf">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element name="entity_id" minOccurs="1" nillable="false">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="application_Id" minOccurs="1" nillable="false">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="SIEBEL_CRM"/>
                        <xs:enumeration value="E-COMMERCE"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="comments" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="240"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="request_datetimestamp" type="xs:dateTime" minOccurs="1"/>
            <xs:element name="customer_order_no" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="48"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="customer_sub_order_no" minOccurs="0">
                 <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="payment_datetime" minOccurs="1" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="coPaymentConfResponse">
        <xs:sequence>
            <xs:element name="entity_id" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="application_id" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="30"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="comments" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="240"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="request_datetimestamp" type="xs:dateTime" minOccurs="1" nillable="true"/>
            <xs:element name="response_datetimestamp" type="xs:dateTime" minOccurs="1" nillable="true"/>
               <xs:element name="customer_order_no" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="48"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="oms_customer_ord_no" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                        <xs:minExclusive value="0"/>
                        <xs:totalDigits value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="message_status" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
			<xs:element name="message_code" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="20"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
			<xs:element name="message_desc" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="200"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="customer_order_response_items" type="tns:customerOrderResponseItems" nillable="true"
                        minOccurs="0" maxOccurs="100"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="customerOrderResponseItems">
        <xs:sequence>
         <xs:element name="line_no" minOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt"/>
                </xs:simpleType>
              </xs:element>
            <xs:element name="item" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="25"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="order_qty_suom" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minExclusive value="0"/>
                        <xs:fractionDigits value="04"/>
                        <xs:totalDigits value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
          
            <xs:element name="fulfill_qty_suom" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        
                        <xs:fractionDigits value="04"/>
                        <xs:totalDigits value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
			<xs:element name="status" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="AVAILABLE"/>
                        <xs:enumeration value="FAILED"/>
                        <xs:enumeration value="UNAVAILABLE"/>                
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
			<xs:element name="status_message" minOccurs="0">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="200"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
             <xs:element name="customerOrderResponseItemFulfillment" type="tns:customerOrderResponseItemFulfillment" nillable="true"
                        minOccurs="0" maxOccurs="100"/>
                    </xs:sequence>
    </xs:complexType>
     <xs:complexType name="customerOrderResponseItemFulfillment">
        <xs:sequence>
         <xs:element name="fulfill_order_no" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                                      
                        <xs:totalDigits value="3"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>  
            <xs:element name="item" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="25"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
             
            <xs:element name="order_qty_suom" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                        <xs:minExclusive value="0"/>
                        <xs:fractionDigits value="04"/>
                        <xs:totalDigits value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
             <xs:element name="fulfill_qty_suom" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:decimal">
                       
                        <xs:fractionDigits value="04"/>
                        <xs:totalDigits value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
          <xs:element name="tsf_no" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                        <xs:minExclusive value="0"/>                       
                        <xs:totalDigits value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="po_no" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                        <xs:minExclusive value="0"/>                       
                        <xs:totalDigits value="12"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
             <xs:element name="source_loc_type" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="source_loc" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                        <xs:minExclusive value="0"/>                       
                        <xs:totalDigits value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="fulfill_loc" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                        <xs:minExclusive value="0"/>                       
                        <xs:totalDigits value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
               <xs:element name="fulfill_loc_type" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="RMS_resv_qty" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                                         
                        <xs:totalDigits value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="RMS_resv_loc" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                                            
                        <xs:totalDigits value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="RMS_resv_loc_type" minOccurs="1" nillable="true">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="2"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="backorder_qty" minOccurs="1" nillable="true">
                 <xs:simpleType>
                    <xs:restriction base="xs:unsignedInt">
                                         
                        <xs:totalDigits value="10"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>

        </xs:sequence>
    </xs:complexType>
    <xs:element name="PaymentConf" type="tns:coPaymentConf"/>
    <xs:element name="PaymentConfResponse" type="tns:coPaymentConfResponse"/>
</xs:schema>
