<?xml version="1.0" encoding="UTF-8" ?>
<definitions targetNamespace="http://com.logicinfo.oms/model/" name="PaymentConfirmationWebService" xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:tns="http://com.logicinfo.oms/model/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
             xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <types>
    <xsd:schema>
      <xsd:import schemaLocation="PaymentConfirmation.xsd" namespace="http://com.logicinfo.oms/model/"/>
    </xsd:schema>
  </types>
  <message name="PaymentConf">
    <part name="input" element="tns:PaymentConf"/>
  </message>
  <message name="PaymentConfResponse">
    <part name="return" element="tns:PaymentConfResponse"/>
  </message>
  <portType name="PaymentConfirmationWebService">
    <operation name="processPaymentConf">
      <input message="tns:PaymentConf"/>
      <output message="tns:PaymentConfResponse"/>
    </operation>
  </portType>
  <binding name="PaymentConfirmationWebService" type="tns:PaymentConfirmationWebService">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <operation name="processPaymentConf">
      <soap12:operation style="document" soapAction=""/>
      <input>
        <soap12:body use="literal" />
      </input>
      <output>
        <soap12:body use="literal" />
      </output>
    </operation>
  </binding>
  <service name="PaymentConfirmationWebService">
    <port name="PaymentConfirmationWebService" binding="tns:PaymentConfirmationWebService">
      <soap12:address location="http://localhost:7101/services/OMS/SADADPaymentConfirmation/SADADPaymentConfirmationWebService"/>
    </port>
  </service>
</definitions>
