package com.logicinfo.oms.model;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Timestamp;
import java.util.Date;

import javax.xml.soap.SOAPException;

import org.apache.commons.lang.math.NumberUtils;
import org.apache.log4j.Logger;

import com.logicinfo.oms.beans.OMSUtilCommons;
import com.logicinfo.oms.ejb.OMSUtilSessionEJB;
import com.logicinfo.oms.ejb.OmsCoCancelHead;
import com.logicinfo.oms.ejb.OmsCoCancelItem;
import com.logicinfo.oms.ejb.OmsCustOrdLog;
import com.logicinfo.oms.ejb.OmsCustOrdLogItem;
import com.logicinfo.oms.ejb.OmsRtlogPublishLog;
import com.logicinfo.oms.util.OMSConstants;
import com.logicinfo.oms.util.OMSUtil;

public class OmsPersistence {

	private final static Logger log = Logger.getLogger(com.logicinfo.oms.model.OmsPersistence.class.getName());

	private final static String CHECK_PO_ORDER_QUERY = "select count(*) from OMS_CO_FULFILL_DETAIL F, OMS_CUST_ORD_HEAD C, OMS_CO_CANCEL_REGION CR where F.OMS_CUST_ORD_NO = C.OMS_CUST_ORD_NO and F.SOURCE_LOC_TYPE = 'SU' AND C.STATUS = 'S' and CR.REQUESTOR_ID = C.ORDER_REQUESTOR_ID and C.CUST_ORDER_NO = ? AND F.ITEM IN (:item) ";

	public OmsPersistence() {
		super();
	}

	public void persistOmsCoCancelHead(CustomerOrderCancellation input, BigDecimal omsCustOrderNo) throws SOAPException {
		OMSUtilSessionEJB session = OMSUtil.doLookup();
		log.info("**persistOmsCoCancelHead start**");
		try {
			OmsCoCancelHead omsCoCancelHead = new OmsCoCancelHead();
			omsCoCancelHead.setEntityId(input.getEntityId());
			omsCoCancelHead.setApplicationId(input.getApplicationId());
			omsCoCancelHead.setCustOrdNo((input.getCustOrderNo()));
			if (input.getSubCustOrderNo() == null) {
				omsCoCancelHead.setSubCustOrdNo("1");
			} else {
				omsCoCancelHead.setSubCustOrdNo((input.getSubCustOrderNo()));
			}
			omsCoCancelHead.setCancelReqstLocId(new BigDecimal(input.getCancellationRequestorId()));
			omsCoCancelHead.setCancelReqId(new BigDecimal(input.getCancellationId()));
			omsCoCancelHead.setRefundOption(input.getRefundPreference());
			Long requestorId = NumberUtils.toLong(input.getCancellationRequestorId());
			StringBuilder items = new StringBuilder();
			for (CustomerOrderCancellationItems item: input.getCancellationItems()) {
				if (items.length() > 0) {
					items.append(", ");
				}
				items.append('\'').append(item.getItem()).append('\'');
			}
			log.info("Requestor Id for the omsCustOrderNo -> " + omsCustOrderNo + " is " + requestorId);
			if (!"HybrisCancellation".equalsIgnoreCase(input.getComments()) && requestorId >= 20000 && requestorId < 30000 /* For BH */ && isPOOrder(input.getCustOrderNo(), items.toString())) {
				omsCoCancelHead.setRefundCompltInd("Z");
			} else if (input.getRefundPreference().equals("CLEARING")) {
				omsCoCancelHead.setRefundCompltInd("Y");
			} else {
				omsCoCancelHead.setRefundCompltInd("N");
			}
			omsCoCancelHead.setRefindAmount(input.getRefundAmount());
			omsCoCancelHead.setComments(input.getComments());
			omsCoCancelHead.setCanReqDatetime(new Timestamp(new Date().getTime()));
			omsCoCancelHead.setCreateDatetime(new Timestamp(new Date().getTime()));
			omsCoCancelHead.setStatus("N");
			session.persistOmsCoCancelHead(omsCoCancelHead);
			log.info("Successfully persisted into OmsCoCancelHead");
		} catch (Exception e) {
			String errString = OMSUtilCommons.formErrorDescription(OMSConstants.ERR_TABLE_INSERT, "1", new String[] { "oms_co_cancel_head" });
			log.error(errString, e);
			throw new SOAPException(errString);
		}
	}

	public OmsCoCancelItem persistOmsCoCancelItem(CustomerOrderCancellationItems item, BigDecimal omsCancelId, BigDecimal omsCustOrdNo) throws SOAPException {
		OMSUtilSessionEJB session = OMSUtil.doLookup();
		log.info("*****Start persistOmsCoCancelItem *****");
		OmsCoCancelItem omsCoCancelItem = new OmsCoCancelItem();
		try {
			omsCoCancelItem.setItem(item.getItem());
			omsCoCancelItem.setComments(item.getItemComments());
			omsCoCancelItem.setCancelReqQty(item.getCancelQtySuom());
			omsCoCancelItem.setLineNo(new BigDecimal(item.getLineNo()));
			omsCoCancelItem.setCreateDatetime(new Timestamp(new Date().getTime()));
			omsCoCancelItem.setCancelConfQty(BigDecimal.ZERO);
			omsCoCancelItem.setOmsCancelId(omsCancelId); // generated by sequence
			session.persistOmsCoCancelItem(omsCoCancelItem);
			log.info("Successfully persisted into OmsCoCancelItem");
		} catch (Exception e) {
			log.error("Failed in persistOmsCoCancelItem. error=" + e);
			String errString = OMSUtilCommons.formErrorDescription(OMSConstants.ERR_TABLE_INSERT, "1", new String[] { "oms_co_cancel_item" });
			log.error(errString);
			throw new SOAPException(errString);
		}
		return omsCoCancelItem;
	}

	public void persistCustOrdLogItem(CustomerOrderCancellationItems item, long fulilmentOrdNo, BigDecimal logSeqNo) throws SOAPException {
		log.info("Inside persistOmsCustOrdLogItem method");
		OMSUtilSessionEJB session = OMSUtil.doLookup();
		try {
			OmsCustOrdLogItem omsCustOrdLogItem = new OmsCustOrdLogItem();
			omsCustOrdLogItem.setItem(item.getItem());
			omsCustOrdLogItem.setQty(item.getCancelQtySuom());
			omsCustOrdLogItem.setCreateDatetime(new Timestamp(new Date().getTime()));
			omsCustOrdLogItem.setFulfillOrderNo(new BigDecimal(fulilmentOrdNo));
			omsCustOrdLogItem.setLineNo(new BigDecimal(item.getLineNo()));
			omsCustOrdLogItem.setLogSeqNo(logSeqNo);
			session.persistOmsCustOrdLogItem(omsCustOrdLogItem);
			log.info("Successfully persisted into OmsCustOrdLogItem");
		} catch (Exception e) {
			String errString = OMSUtilCommons.formErrorDescription(OMSConstants.ERR_TABLE_INSERT, "1", new String[] { "oms_cust_ord_log_item" });
			log.error(errString);
			throw new SOAPException(errString);
		}
	}

	public void persistOmsRtlogPublishLog(CustomerOrderCancellationItems item, BigDecimal omsCancelId, BigDecimal omsCustOrderNo, CustomerOrderCancellation input) throws SOAPException {
		OMSUtilSessionEJB session = OMSUtil.doLookup();
		try {
			OmsRtlogPublishLog omsRtlogPublishLog = new OmsRtlogPublishLog();
			omsRtlogPublishLog.setItem(item.getItem());
			omsRtlogPublishLog.setOmsCustOrdNo(omsCustOrderNo);
			// omsRtlogPublishLog.setFulfillOrderNo(new BigDecimal(fulilmentOrdNo));//not
			// needed
			if (!"HybrisCancellation".equalsIgnoreCase(input.getComments()) && input.getCancellationRequestorId().startsWith("2") /* For BH */ && isPOOrder(input.getCustOrderNo(), "'" + item.getItem() + "'")) {
				omsRtlogPublishLog.setPublishedInd("Z");
			} else {
				omsRtlogPublishLog.setPublishedInd("N"); // need to confirm its value
			}
			omsRtlogPublishLog.setCreateDatetime(new Timestamp(new Date().getTime()));
			omsRtlogPublishLog.setTranType("ORC");
			omsRtlogPublishLog.setLineNo(new BigDecimal(item.getLineNo()));
			omsRtlogPublishLog.setQty(item.getCancelQtySuom()); // need to confirm
			omsRtlogPublishLog.setOmsCancelId(omsCancelId);
			omsRtlogPublishLog.setLocation(new BigDecimal(input.getCancellationRequestorId()));
			session.persistOmsRtlogPublishLog(omsRtlogPublishLog);
			log.info("Successfully persisted into OmsRtlogPublishLog");
		} catch (Exception e) {
			String errString = OMSUtilCommons.formErrorDescription(OMSConstants.ERR_TABLE_INSERT, "1", new String[] { "oms_rtlog_publish_log" });
			log.error(errString);
			throw new SOAPException(errString);
		}
	}

	public void persistOmsCustOrdLog(BigDecimal omsCancelId, BigDecimal omsCustOrderNo, String eventId) throws SOAPException {
		log.info("Inside persistOmsCustOrdLog method");
		OMSUtilSessionEJB session = OMSUtil.doLookup();
		try {
			OmsCustOrdLog omsCustOrdLog = new OmsCustOrdLog();
			omsCustOrdLog.setEventId(eventId);
			omsCustOrdLog.setOmsCustOrdNo(omsCustOrderNo);
			omsCustOrdLog.setCreateDatetime(new Timestamp(new Date().getTime()));
			omsCustOrdLog.setOmsCancelId(omsCancelId);
			// omsCustOrdLog.setOmsDlvConfId(omsDlvConfId);
			// omsCustOrdLog.setEventComments(eventComments);//not needed
			session.persistOmsCustOrdLog(omsCustOrdLog);
			log.info("Successfully persisted into OmsCustOrdLog");
		} catch (Exception e) {
			String errString = OMSUtilCommons.formErrorDescription(OMSConstants.ERR_TABLE_INSERT, "1", new String[] { "oms_cust_ord_log" });
			log.error(errString);
			throw new SOAPException(errString);
		}
	}

	private boolean isPOOrder(String customerNo, String items) {
		boolean hasPOOrder = false;
		Connection connection = null;
		PreparedStatement statement = null;
		ResultSet rs = null;
		try {
			connection = OMSUtil.createDBConnection(OMSConstants.DS_OMS_STRING);
			statement = connection.prepareStatement(CHECK_PO_ORDER_QUERY.replace(":item", items));
			statement.setString(1, customerNo);
			rs = statement.executeQuery();
			if (rs.next()) {
				hasPOOrder = rs.getInt(1) > 0;
			}
			log.info("is PO order for customerNo " + customerNo + " is " + hasPOOrder);
		} catch (Exception e) {
			log.warn("Issue while checking the order for fullfilment type PO", e);
		} finally {
			try {
				if (rs != null && !rs.isClosed()) {
					rs.close();
				}
			} catch (Exception e) {
			}
			try {
				if (statement != null && !statement.isClosed()) {
					statement.close();
				}
			} catch (Exception e) {
			}
			try {
				if (connection != null && !connection.isClosed()) {
					connection.close();
				}
			} catch (Exception e) {
			}
		}
		return hasPOOrder;
	}
}
